### PR TITLE
TTS module "bing" - implement new Azure TTS REST-API

### PR DESCRIPTION
**Pull request by domcross**
## Description
Implement new [Azure Cognitive Speech Service TTS REST-API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech) 

Original implementation was outdated as Microsoft depracated the old API.

## How to test
Configure mycroft.conf to use TTS module "bing" and set value "api_key".
As per default "service_region" is "centralus" and "voice_name" is "en-US-JennyNeural". 
Change these accordingly to your needs and taste.

## Contributor license agreement signed?
CLA [X] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2775))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2775))

**Comment by krisgesling** [comment]
Hey Dom, this has been implemented as a TTS Plugin by @dalgwen:
https://github.com/dalgwen/mycroft-tts-plugin-azure

As we're moving in this direction we'll defer to that and probably pull this out of core. Am I correct that the existing Bing TTS service has been completely deprecated?

**Comment by domcross** [comment]
>Am I correct that the existing Bing TTS service has been completely deprecated?

Bing TTS service has been renamed to Azure cognitive speech service, high quality "neural voices" were added and the REST-API was modified in some details. 
The python-bing-tts package that was used here has seen its last update two years ago and does not reflect these changes.

**Pull request closed without merging**
