### PR TITLE
#525 -- Updating Mimic version to 1.2.0

### PR DESCRIPTION
**Pull request by aatchison**
I've also set --enable-shared flag for future Pymimic support

### CODE REVIEW

**Comment by aatchison** [comment]
I'm having difficulties compiling Mimic on 16.04, hold off on this merge.
https://github.com/MycroftAI/mimic/issues/95

**Comment by aatchison** [comment]
https://github.com/MycroftAI/mimic/issues/95

**Comment by forslund** [comment]
The new build system does not put the binary in the bin folder instead it puts it in the current directory. You either need to update the mimic path in [tts_mimic.py](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/tts/mimic_tts.py#L32). to
```python
BIN = config.get("path", join(MYCROFT_ROOT_PATH, 'mimic', 'mimic'))
```

or create the bin directory and build mimic there:
```bash
mkdir bin
cd bin
../configure --with-audio=alsa --enable-shared
```

The second option might be preferred since it won't break anything.

The build host scripts should be updated to also include libicu-dev (for utf-8 support). Debian based distros has the package `libicu-dev` if I recall correctly.

**Comment by forslund** [comment]
`make install` is needed to copy the mimic executable to `bin/mimic`

**Comment by forslund** [comment]
Seems like `libicu-dev` package is missing from the travis config

**Comment by aatchison** [comment]
I'm kind of at a loss as to why this is failing travis

**Comment by aatchison** [comment]
The dev_setup script works just fine on my laptop. No virtualenv root problems...
Would someone else mind testing this?

**Comment by aatchison** [comment]
@forslund Would you have any ideas regarding this Mimic build failure error?

`./.libs/libttsmimic.so: undefined reference to `uregex_matches_48'
./.libs/libttsmimic.so: undefined reference to `ucasemap_utf8ToLower_48'
./.libs/libttsmimic.so: undefined reference to `u_errorName_48'
./.libs/libttsmimic.so: undefined reference to `uregex_close_48'
./.libs/libttsmimic.so: undefined reference to `uregex_setUText_48'
./.libs/libttsmimic.so: undefined reference to `uregex_reset_48'
./.libs/libttsmimic.so: undefined reference to `ucasemap_utf8ToUpper_48'
./.libs/libttsmimic.so: undefined reference to `utext_openUTF8_48'
./.libs/libttsmimic.so: undefined reference to `ucasemap_open_48'
./.libs/libttsmimic.so: undefined reference to `uregex_openC_48'
./.libs/libttsmimic.so: undefined reference to `ucasemap_close_48'
collect2: ld returned 1 exit status
make[1]: *** [compile_regexes] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/travis/build/MycroftAI/mycroft-core/mimic'
make: *** [all-recursive] Error 1
The command "VIRTUALENV_ROOT=${VIRTUAL_ENV} ./dev_setup.sh" failed and exited with 2 during .
Your build has been stopped.`

**Comment by aatchison** [comment]
I have this problem with ./dev_setup.sh and mimic with an Ubuntu 14.04 VM:
```
checking for unicode/ustring.h... no
configure: error: Unable to detect ICU installation
```

**Comment by forslund** [comment]
@aatchison, it looks like libicu isn't found correctly try adding the package `libicu-dev` to the list of apt packages that are installed when travis builds mimic. [here](https://github.com/MycroftAI/mycroft-core/blob/dev/.travis.yml#L4).

**Comment by forslund** [comment]
@aatchison see my first comment. libicu needs to be added to the `build_host_setup_*.sh` scripts. For debian based distros this is the package `libicu-dev`

**Comment by aatchison** [comment]
Thank you sir.

**Comment by aatchison** [comment]
The build is now passing. Now I just need approval.

**Pull request merged**
