### PR TITLE
Windows porting [WORK IN PROGRESS] [DO NOT REVIEW]

### PR DESCRIPTION
**Pull request by NoamDev**
Issue: #2627

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @NoamDev, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2629/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2629/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2629/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2629/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2629/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2629/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2629/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2629/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2629/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2629/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2629/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2629/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2629/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2629/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2629/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2629))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2629/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2629/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2629/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2629/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2629/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2629/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2629/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2629/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2629/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2629/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2629/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2629/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2629/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2629/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2629/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2629)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2629/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2629/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2629/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2629/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2629/logs/enclosure.log)

**Comment by forslund** [comment]
Closing PR since we're archiving the repo

**Pull request closed without merging**
