### PR TITLE
Fix Voight kampff reset of patched config

### PR DESCRIPTION
**Pull request by forslund**
## Description
This resets a configuration patch by adding a custom cleanup function. This moves the entire config patching and resetting into the steps/configuration.py file keeping it all together in one place.

This also fixes issue with test cases following a case setting the system units would reset the config despite not needing to. This resulted in quite cluttered see [here](https://hudson.mycroft.team/blue/organizations/jenkins/mycroft-core/detail/PR-2736/3/pipeline) for example

## How to test
Make sure VK test passes and reset message is only shown on test cases that patches the config.

## Contributor license agreement signed?
CLA [ Yes ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
As I read more of the context I see that there may be a better way of handling this. Adding the work in progress label while I research a bit more.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2742))

**Comment by krisgesling** [comment]
Thanks for digging into this, and also for not just removing the logging line :joy:

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2742))

**Comment by forslund** [comment]
Updated the procedure to use a custom cleanup. This keeps all the config logic in a single location and fixes the redundant config patch clearing.

**Review by krisgesling — APPROVED** [review]
`context.add_cleanup()` :boom:

Also nice to have the config methods brought together - beautiful stuff!

**Pull request merged**
