### PR TITLE
Replace hard coded data directory path in echo

### PR DESCRIPTION
**Pull request by gauravjuvekar**
Source of a lot of confusion because of permissions errors

### CODE REVIEW

**Comment by penrods** [comment]
Hello, @gauravjuvekar, thank you for helping with the Mycroft project! We welcome
everyone into the community and greatly appreciate your help as we work to
build an AI for Everyone.
  
To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by forslund** [comment]
Hi @gauravjuvekar have you been able to sign the CLA or are you having any trouble?

**Comment by gauravjuvekar** [comment]
@forslund I requested the CLA on mycroft site right now. I'll ping when I have signed it.

**Comment by gauravjuvekar** [comment]
@penrods @forslund 
Signed the CLA

**Comment by forslund** [comment]
Excellent, when we get the confirmation we'll merge this. Thank you!

**Comment by forslund** [comment]
Sorry for the delay. The e-mail got lost but was found last night.

**Comment by forslund** [comment]
The PR was sent while a getpip-bug hindered building and is why Travis failed.

Merging this.

Many thanks @gauravjuvekar!

**Pull request merged**
