### PR TITLE
Added executable bit to arch setup

### PR DESCRIPTION
**Pull request by ParkerMc**
The title says it all.

### CODE REVIEW

**Comment by aatchison** [comment]
LGTM, I can't test on Archlinux but this has no ill effect on the dev_setup.sh

**Comment by ParkerMc** [comment]
Just FYI for some reason it added the fix for #360 and in dev_setup.sh it changed  `pip install -r requirements.txt` to `pip2 install -r requirements.txt` it should work on all linux systems but I have not tested it yet.

**Comment by aatchison** [comment]
I tested only our build and development environments, and all seems well. I
can't attest to the arch setup though.

Thanks for the new commit.

**Comment by ParkerMc** [comment]
Ok I just wanted to make sure I did not mess something up. Thanks for working on Mycroft it is fun to play around with.

**Comment by aatchison** [comment]
Thanks for contributing and I'm glad you are having fun!

**Pull request merged**
