### PR TITLE
Add Yandex TTS support

### PR DESCRIPTION
**Pull request by UltraCoderRU**
## Description
[Yandex](https://yandex.com) is a the russian biggest cloud platform. Yandex [SpeechKit](https://cloud.yandex.com/docs/speechkit/) is, probably, the best STT/TTS service for Russian language. So, I believe it's a good idea to add Yandex TTS support to Mycroft.
Curently I chose authorization with API key, because there is no need for renew key.

## How to test
1. Register an account at Yandex.
2. Create billing account: https://cloud.yandex.com/docs/billing/quickstart/#create_billing_account
You can activate free period in console.
3. Create first "folder" in cloud.
4. Create service account for you Mycroft instance with role `editor`: https://cloud.yandex.com/docs/iam/operations/sa/create
5. Create API key for service account: https://cloud.yandex.com/docs/iam/operations/api-key/create
6. Edit `mycroft.conf`:
```
"tts": {
  "module": "yandex",
  "yandex": {
    "lang": "en-US",
    "api_key": "YOUR_API_KEY",
    "voice": "oksana", #optional
    "emotion": "good" #optional
  }
}
```
You can find list of available values [here](https://cloud.yandex.com/docs/speechkit/tts/request#body_params).

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @UltraCoderRU, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Thanks, looks very useful. When the CLA is signed I'll look at getting this merged.

**Comment by UltraCoderRU** [comment]
@forslund May be I missed something. I signed CLA yesterday twice, but didn't receive any email. Is it automatic process or not?

**Comment by forslund** [comment]
It's not 100% automatic, Let me know if you haven't received the mail tomorrow and I'll prod the responsible party.

**Comment by UltraCoderRU** [comment]
@forslund Still no email.

**Comment by forslund** [comment]
Sorry for not responding, I did poke the responsible party. You should have gotten an email (well about 9 days ago). If not let me know and I'll poke harder at the responsible party.

**Comment by UltraCoderRU** [comment]
@forslund Thanks, I recieved email a week ago and signed document.

**Comment by forslund** [comment]
Ok I will check on the status of it...

**Comment by forslund** [comment]
Been looking at it and it looks good. The thing I've noticed is the year in the copyright notice should be 2019.

Appart from that I haven't been able to test it at all with a live account.

**Comment by forslund** [comment]
Many thanks for this. Merging now!

**Pull request merged**
