### PR TITLE
Fix: show text delegate as per autofit label refactor

### PR DESCRIPTION
**Pull request by AIIX**
## Description

- Fixes SYSTEM Text delegate used by show text method as per the autofit label refactor https://github.com/MycroftAI/mycroft-gui/pull/111/files

## How to test
self.gui.show_text("some example text")

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by krisgesling** [comment]
Great stuff - thanks!

I was just giving it a test run and all is working as expected. 

I wondered what you (or anyone following along) thought about a few tweaks?
- make the rectangle containing the text transparent 
- provide settable backgroundColor and text color via sessionData
- add a margin for content in the event that the card bg color is not black
- don't set font family so that it respects the device default
- if a title is provided, set the body text to normal font weight


```qml
import QtQuick.Layouts 1.4
import QtQuick 2.4
import QtQuick.Controls 2.0
import org.kde.kirigami 2.4 as Kirigami

import Mycroft 1.0 as Mycroft

Mycroft.CardDelegate {
    id: systemTextFrame
    skillBackgroundColorOverlay: "#000000"
    cardBackgroundOverlayColor: sessionData.backgroundColor || "#000000"

    property bool hasTitle: sessionData.title.length > 0 ? true : false
    property int contentMargin: Mycroft.Units.gridUnit * 2

    contentItem: Rectangle {
        color: "transparent"

        ColumnLayout {
            anchors.fill: parent
            anchors.topMargin: contentMargin
            anchors.leftMargin: contentMargin
            anchors.rightMargin: contentMargin
            anchors.bottomMargin: contentMargin

            Mycroft.AutoFitLabel {
                id: systemTextFrameTitle
                wrapMode: Text.Wrap
                visible: hasTitle
                enabled: hasTitle
                Layout.fillWidth: true
                Layout.fillHeight: true
                font.weight: Font.Bold
                text: sessionData.title
                color: sessionData.color || "white"
            }

            Mycroft.AutoFitLabel {
                id: systemTextFrameMainBody
                wrapMode: Text.Wrap
                Layout.fillWidth: true
                Layout.fillHeight: true
                font.weight: hasTitle ? Font.Normal : Font.Bold
                text: sessionData.text
                color: sessionData.color || "white"
            }
        }
    }
}
```

**Comment by AIIX** [comment]
I haven't tested it but if it works for you then would make sense as another pull request, as all these tweaks would require the changes to be added to self.gui.show_text call in gui api itself maybe as non mandatory args the skill authors can optionally add to the show_text call in the skills

**Comment by krisgesling** [comment]
Yeah I think it would be good to have optional args in the function call.

I think we do need to remove the blue rectangle at least, I'm guessing this was left in from testing. I'll do a new PR for the rest.

**Review by krisgesling — APPROVED** [review]

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-3065))

**Pull request merged**
