### PR TITLE
Implement GitHub Actions for linting and unit tests

### PR DESCRIPTION
**Pull request by chrisveilleux**
## Description
Build upon the work done in [PR 2764](https://github.com/MycroftAI/mycroft-core/pull/2764) to replace Travis CI with GitHub Actions.  Moved code coverage from coveralls to codecov due to some issues coveralls has with pytest and GitHub Actions.

## How to test
You can see the results of the GitHub Actions workflow in [draft PR 2817](https://github.com/MycroftAI/mycroft-core/pull/2817).  The "build" and "coverage" badges in README.md were replaced with GitHub Actions and codecov badges.

## Contributor license agreement signed?
CLA [Y]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2819))

**Comment by forslund** [comment]
Awesome! Should the `.travis.yml` and `.coveralls.yml` be removed as part of this as well?

**Comment by chrisveilleux** [comment]
> Awesome! Should the `.travis.yml` and `.coveralls.yml` be removed as part of this as well?

Good call, Åke.  Will remove.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2819)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2819/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2819/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2819/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2819/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2819/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2819))

**Review by krisgesling — APPROVED** [review]
All looks good and we are ready to roll!

**Pull request merged**
