### PR TITLE
Some swedish additions

### PR DESCRIPTION
**Pull request by c0r73x**
## Description
Added the functions nice_time_sv etc.

## How to test
Tests are located in test_format_sv.py

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @c0r73x, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Tack så mycket!

The time changes works very well, the pronounce number doesn't quite work 100% (but is a great improvement) If you want to check on it while waiting for the CLA (getting the mail sent out is a manual process if you don't get an e-mail let me know and I'll poke my colleague handling it) you can try

```python
>>> pronounce_number(10000001, lang='sv-se')
'tioochmillionerer en'

>>> pronounce_number(1.1, lang='sv-se')
'en komma en noll'
```
I would probably not have pronounced the trailing "noll"

**Comment by c0r73x** [comment]
I fixed the "Tiomiljarder en" but the "en komma en noll" is saying the same in all languages except English. An easy way to fix it is to set all languages to default places=1 to get the English behavior.

**Comment by c0r73x** [comment]
I was looking at adding the duration parsing aswell. But it's very strange because it seems that there are alot of code that isn't language specific that are located in the file parse_en... Shouldn't alot of these functions and even the _ReplaceableNumber class be moved to the parse_common file to ease the duration parsing for other languages?

**Comment by forslund** [comment]
The "en komma en noll" isn't too big of an issue. The CLA seems to have arrived. I'm technically on vacation but I'll try to review it again and hopefully get it merged sometime during the week. (Going camping near Oxelöund before heading north :) )

Än en gång, stort tack för ditt bidrag.

**Comment by c0r73x** [comment]
Inga problem ;) (trevlig semester, fel sida sverige dock :P)

I will look into moving some functions from the parse_en to parse_common to ease the translation, it's abit frustrating not to be able to say things like "set a timer for 3 minutes" in your own language.

**Comment by forslund** [comment]
Ok, I've tested it again and looked over the code briefly and it looks good. I'll merge this now and look forward to the restructuring you're suggesting!

En än gång, stort tack för ditt bidrag.

**Pull request merged**
