### PR TITLE
Fix#1986

### PR DESCRIPTION
**Pull request by andlo**
## Description
fix for #1986 

## Contributor license agreement signed?
CLA [ X ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
@forslund Would it be better to create the folder if it doesn't exist or just log a message like it does here?

Either way, it's better than throwing an exception so we can go ahead an pull it in. @andlo Can you fix this PEP8 issue?:
```
mycroft/skills/settings.py:266:5: E303 too many blank lines (2)
```
Thanks!

**Comment by forslund** [comment]
I don't know the logic here enough to answer that.

I would assume it'd be best to create the folder if needed (I think that's done for the hash file). I'm not quite sure of the logic in here if the failure is expected, The exception generated here is currently caught at [L389](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/settings.py#L389) basically skipping all steps after the failed uuid file write. So there _may_ (and I don't really know) be consequences if the exception is caught and the following code is executed without an uuid file.

**Comment by forslund** [comment]
Hi Andlo, thanks for this. @penrods went ahead and added the creation of the skills directory before trying to write the uuid-file. Do you think we should add this check as well?

**Comment by andlo** [comment]
Not nessasaraly - depends on what happens if creating the directory fails....

**Comment by forslund** [comment]
The same as it did previously: Get caught by this except statement: https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/skills/settings.py#L393

**Comment by andlo** [comment]
Then I think @penroids solution will fix the issue. Ill close this then.

**Pull request closed without merging**
