### PR TITLE
#655 - i18n: spanish stt based on local pocketsphinx

### PR DESCRIPTION
**Pull request by SoloVeniaASaludar**
In order to allow mycroft in Spanish it is necessary a valid STT.
See issue #655 for details.

### CODE REVIEW

**Comment by JarbasAI** [comment]
mycroft uses speech recognition lib, it has support for pocket sphinx, couldnt you just do

```
class PocketSphinxSTT(STT):
    def __init__(self):
        super(PocketSphinxSTT, self).__init__()

    def execute(self, audio, language=None):
        self.lang = language or self.lang
        return self.recognizer.recognize_sphinx(audio, self.lang)

```

https://github.com/Uberi/speech_recognition

**Comment by SoloVeniaASaludar** [comment]
Unfortunately, it is not easy, I've tried it ;-). A minor is that addition of a new SST needs changes in stt/__init__.py. 

Worst, coexistence of two PocketSphinx (local recognizer for wakeup word and stt) causes a lot of troubles. Instead, use a single instance of the STT engine increases a lot the recognition accuracy, because Pocketsphinx uses the sound recorded while waiting the wakeup word to optimize his noise/echo filters.

Finally, if we use the local STT, detection of end of record is also improved, compared with the energy levels/thresholds used when STT is remote.
 
All together, I think this pull request is an option we should explore.

**Comment by augustnmonteiro** [comment]
Please rebase : D

**Comment by yannick56** [comment]
@SoloVeniaASaludar

Hello,

Because there are severals patchs, can you give the urls for the patchs in this ticket that I need to apply on the latest Mycroft Core source code ?
I can rediff (redo) the patchs for the lines if required.
I want to apply them on the mycroft source code and finish the howto doc for french here : https://github.com/MycroftAI/mycroft-core/wiki/Mycroft-in-French .

Thank you for your help.

**Comment by JarbasAI** [comment]
how to use this in english?

RuntimeError: Decoder_set_keyphrase returned -1

**Comment by bussdee** [comment]
I followed the instructions on [German Language Support](https://mycroft.ai/documentation/language-support/german/) and the last step told is to change listener.py and pocketsphinx_audio_consumer.py  ... linked to this page.

What do i need to change in those files now? 
(GitHub-Newbie)

**Pull request closed without merging**
