### PR TITLE
Adding support for Python3

### PR DESCRIPTION
**Pull request by the-kid89**
This is the first pull request to start adding support for Python3.

My first step was to make sure that all the unit tests would run without throwing errors. The next step is to get all the unittests passing and find any further Python2-3 errors.

This is for ticket https://github.com/MycroftAI/mycroft-core/issues/366

### CODE REVIEW

**Comment by the-kid89** [comment]
This still needs to be tested on Python2 as well. I would like to propose the addition of `tox` to allow for easier testing of multiple Python versions.

**Comment by aatchison** [comment]
Briliant. One thing though, would you merging your PR against the dev branch? We need to update our contribution docs but that's part of the new process.

**Comment by the-kid89** [comment]
I can do that.

**Comment by BenjaminHCCarr** [comment]
any news on this?
banging on r0.8 which is hard against python2  for OSX homebrew.
if py3 becomes an option that is very interesting. Any chance someone can review and merge/comment?

**Comment by the-kid89** [comment]
I have been crazy busy with work and have not been able to work on it at the moment. I do plan on continuing to work on it in the future when I have a little bit of time again.

**Comment by BenjaminHCCarr** [comment]
@the-kid89 thanks for the reply, have you gotten private feedback from the review team? Totally understand time constraints, just hoping that someone is munching on your code after you re-branched to `-dev`.

**Comment by ethanaward** [comment]
This is similar to #604, but it looks like this fixes more Python 2 to 3 changes. Could you rebase this and try to get the CI unit tests running on it?

**Comment by penrods** [comment]
Hello, @the-kid89 , thank you for helping with the Mycroft project!  We have been tackling some of Python 3 changes slowly, so this PR may or may not get merged.  However I know you have been involved with the project in various ways and I would like to get you included in the Contributor list (https://github.com/MycroftAI/contributors) and under the Mycroft Project CLA (Contributor Licensing Agreement).

The CLA legally protects yourself, the project, and users of Mycroft technologies.  The agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by forslund** [comment]
Hi @the-kid89. Thanks for this work, we're starting our move towards Python3 support and it would be great if you'd like to help since you seem to know a bit on the subject.

Are you Ok with closing this branch since it has a lot of conflicts?

**Comment by the-kid89** [comment]
Yeah that would be fine. I ended up running out of free time to work on this. Life has been getting in the way of all the things.

**Pull request closed without merging**
