### PR TITLE
Shellcheck dev_setup.sh

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
Hit an [issue in a Github Actions install of Mycroft-core](https://github.com/MycroftAI/skill-homeassistant/runs/4451242699#step:30:1) where it was unable to evaluate a conditional. This fixes that specific issue along with a range of suggestions from shellcheck.

## How to test
run `shellcheck dev_setup.sh`
install mycroft using `dev_setup.sh`

## Contributor license agreement signed?
- [x] CLA

### CODE REVIEW

**Comment by krisgesling** [comment]
Also feel free to push additional fixes straight onto this branch

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-3048))

**Comment by forslund** [comment]
In reverse order:
4. The sed expression doesn't need to be spread out on three lines, with a single line this becomes nice and easy
3. Not sure what the best way is but it sounds like `command -v` should be the way to go
2. These seem to be due to using space separated string as commandline arguments, [BashFAQ](http://mywiki.wooledge.org/BashFAQ/050) disapproves of this and recommends an array instead.
1. Easiest and nicest solution is in my opinion to split it into 2 lines

I pushed commits for 1,2 and 4. I suck at shellscripting so another pair of eyes on those changes might be a good idea.

**Comment by PureTryOut** [comment]
`which` is indeed not standard. Debian is even going to drop it soon, there was quite a lively discussion about that recently. `command -v` is the only standard that can be relied upon to work the same across all distros and shells.

**Comment by krisgesling** [comment]
hmm doesn't look like you can add an individual file from outside the included directory. So I've dropped that commit for now.

I'll try find some time to do a clean up of the rest of the scripts since most of it is quite straight forward.

**Comment by krisgesling** [comment]
:facepalm: did a silly on the commit history - will fix it later today

**Comment by forslund** [comment]
May be worth looking at #3030 before doing the rest of the scripts. It adds some shellcheck setup which may be useful. I've been planning to go through the scripts folder but have been waiting for that PR to be reviewed.

**Comment by krisgesling** [comment]
Closing in favor of #3090

**Pull request closed without merging**
