### PR TITLE
The command to run unittests was wrong documented

### PR DESCRIPTION
**Pull request by notdefine**
## Description
Make venv-activate.sh compatible with sh and zsh

## How to test
$  if [ "$0" == "$BASH_SOURCE" ]; then echo "a"; fi
Error: sh: 1: [: sh: unexpected operator

$  if [[ "$0" == "$BASH_SOURCE" ]]; then echo "a"; fi
Succed

## Contributor license agreement signed?
CLA [X] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @notdefine, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Hi, thanks for fixing this. Your change is absolutely correct. As soon as the CLA is received we can merge this. Let us know if there's any issues with the CLA process. (There may be until after new years before you get the CLA email since we're all away on holidays)

(Sort of irrelevant: I Think the body of the PR description might have come from the other PR)

**Comment by notdefine** [comment]
The CLA is signed. greetings

**Comment by krisgesling** [comment]
CLA received, thanks Thomas :)

**Comment by forslund** [comment]
Once again. a big thanks for fixing this.

**Pull request merged**
