### PR TITLE
Improved Italian translations.

### PR DESCRIPTION
**Pull request by Test-4860**
Improved Italian translations.

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @Test-4860, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2623))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2623))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2623))

**Comment by krisgesling** [comment]
Hi @Test-4860 thanks for contributing some updates to our Italian translations. 

Have you had a chance to fill out the CLA form? Let me know if I've missed seeing it.

**Comment by krisgesling** [comment]
Hi there, as we haven't heard back from you and have no CLA, I'm going to close this one. 

If you weren't already aware, we have a translation platform at translate.mycroft.ai where you can contribute to our translation efforts without completing a CLA.

Thanks

**Pull request closed without merging**
