### PR TITLE
bugfix/issue-940 change LOGGER to logger

### PR DESCRIPTION
**Pull request by Mn0491**
==== Fixed Issues ====
fixed issue 940
https://github.com/MycroftAI/mycroft-core/issues/940

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
Just curious, why weren't checks failing under `test/audio/test_niterface.py:TestInterface?

**Comment by Mn0491** [comment]
the test does not call the deprecated wait_while_speaking function. it goes straight to the new function.

**Comment by augustnmonteiro** [comment]
@Mn0491 please use the lowercase one, most classes are using lowercase : D

**Comment by Mn0491** [comment]
@augustnmonteiro done!

**Pull request merged**
