### PR TITLE
Recognize "confirm[ed]" as a word for "yes"

### LINKED ISSUE #2189: Confirmation questions don't respond to "confirm"
# Steps to reproduce

1. Have Mycroft installed
2. Say, "Hey Mycroft" and wait for the acknowledgement sound
3. Say, "install bedtime stories" (or whatever skill)
4. Mycroft will say, "Confirming: would you like to install \<skill> by \<author>"?
5. Say, "confirm"

# Expected behavior

Mycroft interprets "confirm" or "confirmed" as a confirmation for the installation.

# Actual behavior

Mycroft only recognizes "yes" and cancels the installation if you say "confirm".

# Version information

Enclosure is Pycroft. Mycroft is running mycroft-core version 19.02, release 13.

This seems pretty straightforward to reproduce but if this is _supposed_ to already work or something I would be happy to generate debugging information.

### PR DESCRIPTION
**Pull request by strugee**
## Description

Fixes #2189 (at least, I think)

Note: I didn't do any testing since I just made this PR in the GitHub web UI and it seemed simple enough that I didn't bother.

## Contributor license agreement signed?

CLA is in progress, I'm waiting for a HelloSign email.

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @strugee, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Thanks, looks like a good update. When the CLA lands I'll merge it.

**Comment by strugee** [comment]
@forslund are CLA agreement emails sent out manually? If not I didn't get mine for some reason.

I don't know what Mycroft policy is but honestly this change is so trivial it probably isn't even copyrightable so you might be able to merge it anyway. If you want to just wait until I sign the CLA though I understand!

**Comment by forslund** [comment]
The CLA policy is rather strict I'm afraid. The CLA is sent out manually, did you get an e-mail otherwise I'll have to talk to the person handling it...

**Comment by strugee** [comment]
@forslund I got a reminder email; maybe I just missed the original. Signed.

**Comment by forslund** [comment]
CLA is in, merged!

**Pull request merged**
