### PR TITLE
External enable/disable intent

### PR DESCRIPTION
**Pull request by JarbasAI**
Allow intents to be enabled or disabled from outside the skill itself

needed for example in my intent_layers helper class to control what intents are active

### CODE REVIEW

**Comment by augustnmonteiro** [comment]
@JarbasAI thank you that's a cool feature, can you fix the tests so we can merge it :)

**Comment by JarbasAl** [comment]
rebased

**Comment by JarbasAl** [comment]
https://github.com/JarbasAl/mycroft_jarbas_utils  needs this PR

**Comment by forslund** [comment]
Will review tomorrow!

**Comment by forslund** [comment]
Could have sworn I posted a message earlier. Looks and works good. Only thing I'd like to change is the name of the messages. `mycroft.skill.enable_intent` and `mycroft.skill.disable_intent`.

**Comment by forslund** [comment]
With the update it looks good. I'll rebase it and squash it into a single commit and get it merged in the morning.

**Comment by forslund** [comment]
Merged via #1524, closing.

**Pull request closed without merging**
