### PR TITLE
extract number scientific notation support

### PR DESCRIPTION
**Pull request by JarbasAl**
## Description

extract_number_en now supports scientific notation

Partially solves #1647 

## How to test
check unittests

## Contributor license agreement signed?
CLA [yes ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by JarbasAI** [comment]
any idea why this passes python 3.4 and 3.5 but fails in python 3.6 ?

**Comment by forslund** [comment]
From a glance it looks like a floating point issue

**Comment by JarbasAl** [comment]
any idea how i can fix this? i wanted to include it in a new PR (all possible number pronunciations)

**Comment by penrods** [comment]
The issue is that you are probably getting a result like:

    666000000.00000000000000001 != 6660000000.0

Using == or != on floats is never really safe or reliable.  Instead it should be more like this:

```python
def assertEqualFloat(self, test, expected, epsilon=None):
    epsilon = epsilon or 0.0000001
    if test > expected+epsilon or test < expected-epsilon:
        self.fail("Value {} was not equal to {} within {}".format(test, expected, epsilon)
```

Then change the tests to:
```python
    self.assertEqualFloat(extract_number("666 times 10 raised to the ninth"),
                             666e9)
```

**Comment by forslund** [comment]
```
6.66*10⁹:					6660000000
extract_number Python3.5:	6660000000.0
extract_number Python3.6:	666000000.0
```

It seems the extract number comes up short on python 3.6

**Comment by forslund** [comment]
Some more tests on python 3.6, it seems the ninth gets replaced with eight:
`ten eight power`

**Comment by JarbasAl** [comment]
closing and remaking against https://github.com/MycroftAI/lingua-franca

**Pull request closed without merging**
