### PR TITLE
Fix Mimic build on Fedora

### PR DESCRIPTION
**Pull request by countcretinos**
## Description
See mycroftai/mimic1#196

## How to test
Run `dev_setup.sh` on Fedora and opt-in to build Mimic locally.

## Contributor license agreement signed?
CLA [X] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @countcretinos, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Thanks @countcretinos, looks good I'll merge it when the CLA is signed. Let me know if you have any issues with the process.

**Comment by forslund** [comment]
Hi @countcretinos, I don't see your name in the list of contributors yet, did you have any issues with signing the CLA? Or has it gotten lost at our end somehow?

**Comment by countcretinos** [comment]
I did sign it but I did again now.

**Comment by krisgesling** [comment]
Hey @countcretinos I haven't seen it come through our system. Just to confirm this was at: https://mycroft.ai/cla/ ?

If you can email me your name to kris.gesling@mycroft.ai then I'll get a CLA sent out.

**Comment by forslund** [comment]
Hi @countcretinos did you try to re-submit the CLA email request?

**Comment by countcretinos** [comment]
> Hi @countcretinos did you try to re-submit the CLA email request?

Hi, yes I did it couple of days back, but haven't got a reply.

**Comment by krisgesling** [comment]
Hey @countcretinos I sent you an email a few days ago but doesn't seem to have gotten through.

In terms of pseudo-anonymous contributions, you can see that many people in our contributors list are listed only by their Github handle. This is a checkbox on the CLA that you can tick. However we do require a name and physical address (not just an email) for the CLA itself. Our lawyers tell us that this is required so unfortunately it's something we have to collect.

The CLA document is sent out via Hellosign.com, and you complete it along with a digital signature. We then review this within the browser and have an independent script that updates the contributors list. So your personal information never leaves HelloSign.com and only your Github handle is used to identify your contributions.

If you can email me your name and whether the contributions is being made as an individual or through an employer to kris.gesling@mycroft.ai I can send out the correct CLA. 

Thanks

**Comment by krisgesling** [comment]
Hey Count, sorry that this turned into a bit of a saga. 

Are you keen to try the CLA process one more time or shall I close this PR?

**Comment by countcretinos** [comment]
> Hey Count, sorry that this turned into a bit of a saga.
> 
> Are you keen to try the CLA process one more time or shall I close this PR?

Yeah. Let's try it again :)

**Comment by krisgesling** [comment]
Cool, why don't we by-pass the form to remove one potential issue. Can you email me directly (kris.gesling@mycroft.ai). We need your name (but this can be kept anonymous) and whether the contribution is being made as an individual or through an employer. Then I can send out the correct agreement for signing.

**Comment by krisgesling** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: 
CLA received!!

Thanks for persevering :)

**Pull request merged**
