### PR TITLE
Update test_file_utils.py

### PR DESCRIPTION
**Pull request by abnsy**
Method has no argument

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @albernsrya, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2924))

**Comment by krisgesling** [comment]
Hi Albern, thanks for helping out with the project.

This does look a little strange. I just checked the [unittest docs](https://docs.python.org/3/library/unittest.html#unittest.TestCase.tearDownClass) and it also states that it should be decorated as a classmethod.

I'm curious if you saw any issues that led you to this or if you just noticed it while reading the code?

**Comment by albernsrya** [comment]
hello thanks for your feedback kris, I read the code and figured this out

**Comment by krisgesling** [comment]
As per the other thread, we need CLA's for all contributions. 

Please shout out if you're open to signing.

**Pull request closed without merging**
