### PR TITLE
Add support of the Google Cloud TTS

### PR DESCRIPTION
**Pull request by dsborets**
Add support of the Google Cloud TTS https://cloud.google.com/text-to-speech

Sample config:
```
"google_cloud": {
      "file_format": "mp3",
      "lang": "en_GB",
      "service_account_info": {
         "type": "service_account",
         "project_id": "<project id>",
         "private_key_id": "<private key id>",
         "private_key": "<private key>"
         "client_email": "<client email>",
         "client_id": "<client id>",
         "auth_uri": "https://accounts.google.com/o/oauth2/auth",
         "token_uri": "https://oauth2.googleapis.com/token",
         "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
         "client_x509_cert_url": "<client cert URL>"
      }
    }
```

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @dsborets, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2895))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2895))

**Comment by forslund** [comment]
Hi, this is really awesome.

The project is moving towards more of a plugin based system so these don't need to be included in core. Last I heard many of the existing ones are planned to be removed and replaced by plugins (see #2701).

The docs for the plugins are here: https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/plugins and an example of a TTS-plugin can be found here: https://github.com/JarbasLingua/jarbas-tts-plugin-voicerss

**Comment by dsborets** [comment]
Ok, got it. I'll create a plugin instead. Is there any particular repo for plugins?

**Comment by JarbasAl** [comment]
@dsborets the closest would be https://github.com/ChanceNCounter/awesome-mycroft-community

i think there are plans to add plugins to the official marketplace also

**Comment by krisgesling** [comment]
Hi @dsborets thanks for your efforts to add support for Google Cloud TTS. 

I'll close this PR as a plugin is the best way to go for this now and it sounds like you're already heading down that path. Hopefully the documentation and other plugins have provided some good guidance.

**Comment by tolnai** [comment]
@dsborets , I just came across this PR as I was looking for how to enable google cloud TTS for mycroft. Did you eventually create a plugin version of your changes? (I couldn't find any.)

**Pull request closed without merging**
