### PR TITLE
Added License to File Headers

### PR DESCRIPTION
**Pull request by ryanleesipes**
Added GPL license headers to each file.

### CODE REVIEW

**Comment by ryanleesipes** [comment]
@jdorleans or @aatchison please review, make sure it looks okay and doesn't break anything. Also make sure it meets the PEP8 guidelines.

**Comment by ryanleesipes** [comment]
Deals with issue #3

**Comment by aatchison** [comment]
Did we only need to add these headers to __init__.py files?

**Comment by ryanleesipes** [comment]
Should have been all .py files. Can you verify?

On Mon, May 23, 2016, 3:31 PM aatchison <notifications@github.com> wrote:

> Did we only need to add these headers to *init*.py files?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MycroftAI/mycroft-core/pull/35#issuecomment-221087020>
>
-- 
Ryan Sipes
CTO, Mycroft A.I.
https://mycroft.ai
785-979-6091

**Comment by aatchison** [comment]
Yeah, not all of them:
https://github.com/MycroftAI/mycroft-core/blob/bugfix/issues-3/mycroft/client/enclosure/mouth.py

**Comment by aatchison** [comment]
You should re-base as well.

**Comment by ryanleesipes** [comment]
Alright, rebased and fixed it so that there is a space between the license and the other content of the files.

**Comment by aatchison** [comment]
cool
Travis is building . I'll pull down and check too

**Comment by aatchison** [comment]
A few pep8 issues

`pep8 mycroft test
mycroft/skills/weather/owm_repackaged/__init__.py:20:1: E265 block comment should start with '# '
mycroft/skills/weather/owm_repackaged/__init__.py:32:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/__init__.py:33:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:24:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:25:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:27:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:28:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:32:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:33:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:34:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:35:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:36:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owm25.py:37:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owmhttpclient.py:32:1: E402 module level import not at top of file
mycroft/skills/weather/owm_repackaged/owmhttpclient.py:33:1: E402 module level import not at top of file
mycroft/pairing/__init__.py:19:1: W391 blank line at end of file`

**Comment by aatchison** [comment]
Check this out:
http://stackoverflow.com/questions/1523427/what-is-the-common-header-format-of-python-files

**Comment by aatchison** [comment]
This seems like a tricky one!

**Comment by ryanleesipes** [comment]
*Le Sigh*

**Comment by ikeydoherty** [comment]
I'm unsure why you've not used "#comment" style, which would not cause failures like that

**Comment by ryanleesipes** [comment]
I will do that.

**Comment by ikeydoherty** [comment]
Sorry to cause this much pain for you @ryanleesipes =)

**Comment by ryanleesipes** [comment]
Killing this for a clean PR with only one Commit that should solve all our problems :smile:

**Pull request closed without merging**
