### PR TITLE
Enable snowboy to use several wakeword models

### PR DESCRIPTION
**Pull request by dalgwen**
Snowboy could use several wakeword models, not only the first one.

## Description
Fix [#2498](https://github.com/MycroftAI/mycroft-core/issues/2498)

## How to test
Use snowboy, with several hotword model at the same time.
Every one of them should wake mycroft.

## Contributor license agreement signed?
CLA [ ]
Not yet, I'm in processing. But I think that for a change this small, it will not be a problem ;-)

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @dalgwen, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by dalgwen** [comment]
I forgot to mention [snowboy code documentation](https://github.com/Kitt-AI/snowboy/blob/master/include/snowboy-detect.h) to back this modification :

// " In the case that more than one hotword exist in the
  // provided models, RunDetection() will return the index of the hotword, if
  // the corresponding hotword is triggered."

**Comment by forslund** [comment]
Thanks @dalgwen looks nice and simple. Will merge once the CLA is received. (We're require it for all contributions no matter how small so we are consistent)

**Comment by dalgwen** [comment]
It's OK, I just signed the CLA. 👍

**Comment by krisgesling** [comment]
Thanks @dalgwen. 

Received the CLA. Merging now.

**Pull request merged**
