### PR TITLE
Added audio accuracy test

### PR DESCRIPTION
**Pull request by Wolfgange3311999**
This adds a new command, `./start.sh audioaccuracytest` that will run the listener through a set of audio files and verify that it can find the wake word.

To run it, place some audio files with the wake word in `audio-test/data/query-after/`. The folder is under query-after since audio files are also being collected with the query before even though they are not currently being tested since the listener isn't setup to work like that.

### CODE REVIEW

**Comment by aatchison** [comment]
Going to check this out, very good.

**Comment by aatchison** [comment]
Wow, this is cool. I'm going to record some more wavs and see if my pirate voice works.

**Comment by aatchison** [comment]
If she builds, lgtm

**Comment by Wolfgange3311999** [comment]
By the way, [here's some sample audio files we put together](https://github.com/Wolfgange3311999/mycroft-core/tree/sample-audio-files) for anyone else who wants to test it.

**Pull request merged**
