### PR TITLE
Handle Mimic missing properly

### PR DESCRIPTION
**Pull request by forslund**
## Description
I got an error report on chat with the following error:

```
Traceback (most recent call last):
  File "/home/roy/mycroft-core/mycroft/tts/tts.py", line 519, in create
    tts.validator.validate()
  File "/home/roy/mycroft-core/mycroft/tts/tts.py", line 435, in validate
    self.validate_connection()
  File "/home/roy/mycroft-core/mycroft/tts/mimic_tts.py", line 189, in validate_connection
    LOG.info("Failed to find mimic at: " + BIN)
TypeError: can only concatenate str (not "NoneType") to str
2020-10-08 16:49:47.127 | ERROR    | 51541 | __main__:on_error:34 | Audio service failed to launch (TypeError('can only concatenate str (not "NoneType") to str')).
```

So the error message in the exception handler throws an exception making the real exception not show.

I also went through the module with pylint and fixed the issues that could be fixed without breaking backwards compatibility.

## How to test
Make sure Mimic still works and unittests works. You can also set `BIN` to `None` and check that the correct exception is shown.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2718))

**Comment by krisgesling** [comment]
Still a possible error. Steps to reproduce:
1. remove mimic directory
2. launch Mycroft with internet
3. disconnect internet
4. speak a request

```
Traceback (most recent call last):
  File "/home/gez/mycroft-core/mycroft/audio/speech.py", line 95, in handle_speak
    mute_and_speak(chunk, ident, listen)
  File "/home/gez/mycroft-core/mycroft/audio/speech.py", line 132, in mute_and_speak
    mimic_fallback_tts(utterance, ident, listen)
  File "/home/gez/mycroft-core/mycroft/audio/speech.py", line 148, in mimic_fallback_tts
    tts.execute(utterance, ident, listen)
  File "/home/gez/mycroft-core/mycroft/tts/tts.py", line 321, in execute
    self._execute(sentence, ident, listen)
  File "/home/gez/mycroft-core/mycroft/tts/tts.py", line 351, in _execute
    wav_file, phonemes = self.get_tts(sentence, wav_file)
  File "/home/gez/mycroft-core/mycroft/tts/mimic_tts.py", line 159, in get_tts
    '-t', sentence])
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Strangely in `get_tts()` neither `sentence` nor `wav_file` are `None` or `NoneType` values.

**Comment by forslund** [comment]
Likely the mimic path is None... The issue is that the fallback_tts object shouldn't be created at all in this case since the validation should fail (since mimic doesn't exist) will investigate

**Comment by forslund** [comment]
So the root issue seem to be that the fallback_tts was never validated. I moved things around a little and added the validation for the fallback.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2718))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2718))

**Review by krisgesling — APPROVED** [review]
Looks good, thanks Ake!

**Pull request merged**
