### PR TITLE
Replace emitter/ws with bus

### PR DESCRIPTION
**Pull request by forslund**
## Description
Replaces emitter and ws variables/members with bus since these are used to interact with Mycroft messagebus. the fact that they are websocket/event emitters are of litte interest in the grander scheme of things.

## How to test
Make sure it looks somewhat nice and is functional.

## Contributor license agreement signed?
CLA [Yes]

### CODE REVIEW

**Comment by AIIX** [comment]
oh..that broke a grand ton of display stuff on my skills between 18.02 to 18.08, applying changes to my skills now, for anyone else who comes across this the change seems basically from usage of: "self.enclosure.ws.emit(Message())" to "self.enclosure.bus.emit(Message())"

**Comment by forslund** [comment]
Sorry about that @AIIX. Where are you using code like that, from skills? if that's the case you should use `self.bus` directly (we also kept the old `self.emitter` around for backwards compatibility)

**Comment by forslund** [comment]
Good eyes. Corrected this in #1760

**Comment by JarbasAl** [comment]
mpg123 service missing a lot of self. also, theres plenty of "bus" around that throw errors, audio service will fail to play because of this

**Pull request merged**
