### PR TITLE
Speak skill

### PR DESCRIPTION
**Pull request by jasonehines**

### CODE REVIEW

**Comment by ethanaward** [comment]
@jasonehines: Your intent test is failing. Looking at it, it's because you define the SpeakIntent as requiring a `Words` entity, and then never supply something that can be matched to a `Words` entity in the utterance in your intent test.

**Comment by jasonehines** [comment]
@ethanaward I think it's correct now.

**Comment by aatchison** [comment]
I'm checking it out now.

**Comment by aatchison** [comment]
This is really, fun! lgtm.

**Pull request merged**
