### PR TITLE
Pt-PT translation

### PR DESCRIPTION
**Pull request by JarbasAI**
all parsing and formatting for pt-pt with all unittests passing

### CODE REVIEW

**Comment by forslund** [comment]
Can you look over the pep8 issues?

mycroft/util/parse.py:1063:80: E501 line too long (83 > 79 characters)
mycroft/util/parse.py:1136:5: E265 block comment should start with '# '
mycroft/util/parse.py:1137:5: E265 block comment should start with '# '
mycroft/util/parse.py:1250:9: E266 too many leading '#' for block comment
mycroft/util/parse.py:1349:19: E127 continuation line over-indented for visual indent
mycroft/util/parse.py:1350:19: E127 continuation line over-indented for visual indent
mycroft/util/parse.py:1675:35: E127 continuation line over-indented for visual indent
mycroft/util/parse.py:1675:80: E501 line too long (81 > 79 characters)
mycroft/util/parse.py:1679:35: E127 continuation line over-indented for visual indent
mycroft/util/parse.py:1679:80: E501 line too long (81 > 79 characters)
mycroft/util/parse.py:1683:35: E127 continuation line over-indented for visual indent
mycroft/util/parse.py:1683:80: E501 line too long (81 > 79 characters)
mycroft/util/parse.py:1693:37: E127 continuation line over-indented for visual indent
mycroft/util/parse.py:1707:46: E127 continuation line over-indented for visual indent
mycroft/util/parse.py:1727:37: E131 continuation line unaligned for hanging indent
mycroft/util/parse.py:1728:33: E131 continuation line unaligned for hanging indent
mycroft/util/parse.py:1735:37: E131 continuation line unaligned for hanging indent
mycroft/util/parse.py:1736:33: E131 continuation line unaligned for hanging indent
mycroft/util/parse.py:1751:33: E131 continuation line unaligned for hanging indent
mycroft/util/parse.py:1754:33: E122 continuation line missing indentation or outdented
mycroft/util/parse.py:1764:33: E131 continuation line unaligned for hanging indent
mycroft/util/parse.py:1767:33: E122 continuation line missing indentation or outdented
mycroft/util/parse.py:1804:80: E501 line too long (83 > 79 characters)
mycroft/util/parse.py:1805:37: E131 continuation line unaligned for hanging indent
mycroft/util/parse.py:1810:80: E501 line too long (118 > 79 characters)
mycroft/util/parse.py:1812:29: E122 continuation line missing indentation or outdented
mycroft/util/parse.py:1812:80: E501 line too long (80 > 79 characters)
mycroft/util/parse.py:1815:80: E501 line too long (80 > 79 characters)
mycroft/util/parse.py:1819:80: E501 line too long (89 > 79 characters)
mycroft/util/parse.py:1836:80: E501 line too long (87 > 79 characters)
mycroft/util/parse.py:1915:80: E501 line too long (80 > 79 characters)
mycroft/util/parse.py:1922:80: E501 line too long (80 > 79 characters)
mycroft/util/parse.py:2133:1: W391 blank line at end of file

**Comment by JarbasAI** [comment]
making some unit tests, do not merge yet :) 

currently failing due to some unicode problems! need to better handle things like "três" which is 3

```
/home/user/jarbas_stable/JarbasAI/mycroft/util/parse.py:1063: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
======================================================================
FAIL: test_extractnumber_pt (__main__.TestNormalize)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/jarbas_stable/JarbasAI/test/unittests/util/test_parse_pt.py", line 48, in test_extractnumber_pt
    lang="pt"), 3.0/4.0)
AssertionError: 0.25 != 0.75

```

also failing in the pt equivalent of
```
 self.assertEqual(extractnumber("one cup and a half"), 1.5)
        self.assertEqual(extractnumber("one and a half cups"), 1.5)
        self.assertEqual(extractnumber("one and one half cups"), 1.5)
```

**Comment by forslund** [comment]
@JarbasAI there are issues I'm sure. For example the other day we fixed a reading error when dialog files included unicode.

The major parts like adapt and padatious should have good unicode support.

`from __future__ import unicode_literals` will turn default strings into unicode which might be good here. (pip install future may need to be installed)

**Comment by JarbasAI** [comment]
all numbers fixed plus some additions like "seven point/dot 8"

**Comment by JarbasAI** [comment]
all unit tests ready, also added methods for getting gender of a word

all suggestions welcome, will fix the pep8 stuff tomorrow, the auto reformat of my ide missed a few

**Comment by yannick56** [comment]
@jarbasai

Hello,

Because there are severals patchs for Pt-PT support in Mycroft, can I apply the patchs in this ticket on the latest Mycroft Core source code ?
Or is there fix that you need to apply before on it to fix several problems ?
I want to apply them with french specific part on the mycroft source code and add the support for french language in Mycroft.
The previous try at the following url does not work : https://github.com/MycroftAI/mycroft-core/wiki/Mycroft-in-French .

Thank you for your help.

**Comment by JarbasAI** [comment]
@yannick56 the PR is functional, it complains of pep8 errors, the code works fine and can be merged

you may have to fix some conflicts during merge because the headers changed i think

**Comment by yannick56** [comment]
@JarbasAI

Hello,

Because you send several times the same patch with changes for the same file in this Github ticket number, do you have an archive (tar ou gz ou zip) that include all the latest release for your patchs for pt-br ?
With this, it will be more easy for me to create the required patchs for the Mycroft's french support.

Thank you for your help.

**Comment by yannick56** [comment]
Hello JarbasAI

I want to add a new language support in mycroft-core.
Can you add in the wiki, the steps for debugging language processing by python when a developper add a new language in mycroft-core ? wiki page here  : https://github.com/MycroftAI/mycroft-core/wiki/Adding-a-new-language ?
In your big patch for util/parse.py, what are the python functions for portuguese that I need to reuse first for adding a new language and next test first ?
Can you write a list for the steps ?
With a number for each functions in this list and the number 1 for the first python functions to add in mycroft-core's parse.py file and test first.

Thank you for your help.

Best regards.

**Pull request merged**
