### PR TITLE
Feature/issue 89

### PR DESCRIPTION
**Pull request by the7erm**
Please review.

### CODE REVIEW

**Comment by clusterfudge** [comment]
The correct implementation here is to have a single dialog file with multiple entries. Please refer to the [MustacheDialogRenderer implementation](https://github.com/MycroftAI/mycroft-core/blob/master/mycroft/dialog/__init__.py#L57-L81).

**Comment by the7erm** [comment]
Oops sorry about that.  I didn't realize it chose a random string.

**Comment by clusterfudge** [comment]
No worries. There's some stuff about this in the sdk docs that haven't been published yet *cough* @ryanleesipes *cough*

**Comment by ryanleesipes** [comment]
OOPS! @ethanaward can we make sure to include this in the skills docs?

**Comment by ryanleesipes** [comment]
@clusterfudge the aforementioned documentation was just merged into docs, should see it appear on https://docs.mycroft.ai once it pulls down the update and applies it.

**Comment by ryanleesipes** [comment]
Remove randint and we are gtg.

**Comment by the7erm** [comment]
> Remove randint and we are gtg.
Done

**Comment by clusterfudge** [comment]
Merging.

BLAM!

**Pull request merged**
