### PR TITLE
Update to pyee 8.1.0

### PR DESCRIPTION
**Pull request by forslund**
## Description
pyee 8.1.0 adds a small change to make the once call to be more safe in
multithreaded environments.

This switches back from the now deprecated BaseEventEmitter to the
standard EventEmitter.

Before this PR can be merged [Adapt PR #117](https://github.com/MycroftAI/adapt/pull/117) also needs to be merged to sync the requirements.

The update should a tleast improve on the behaviour reported in #2695 if not fix it all together.

## How to test
Ensure that unit tests and integration tests succeeds.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2724))

**Comment by krisgesling** [comment]
That's awesome, thanks for chasing this upstream!

**Comment by j1nx** [comment]
Don't forget to bump the requirement in mycroft-messagebus-client as well.

**Comment by forslund** [comment]
Thanks for the reminder @j1nx!

**Comment by krisgesling** [comment]
Hey Ake, I wanted to check on the `WIP` label. 

Is that because we need to merge the other updates also or are you still testing this?

**Comment by forslund** [comment]
Yes I labled it WIP since it needs Adapt to be updated to match before merging this one. The messagebus change is not mandatory.

**Comment by forslund** [comment]
Adapt version has been poked, now the pyee versions of core and adapt is synced.

**Comment by krisgesling** [comment]
Hey I just noticed there's still a `BaseEventEmitter` in the wake word tests:
https://github.com/forslund/mycroft-core/blob/feature/pyee-8.1.0/test/wake_word/wake_word_test.py#L103

Assuming this just got missed or is there a specific reason for it remaining?

**Comment by forslund** [comment]
Good eyes, that's an omission on my part. Didn't search the test folder apparently. Will update

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2724))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2724))

**Comment by forslund** [comment]
Updated fixing the wake_word test. (I noticed we/I seem to have broken the wake_word test. I only rarely get successes...will open an issue for this.)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2724))

**Review by krisgesling — APPROVED** [review]
:tada:

**Pull request merged**
