### PR TITLE
multiple hotwords

### PR DESCRIPTION
**Pull request by JarbasAI**
remake of #997 

Listening for common words could be useful

proposal:

- add any number of hot words to config
- hot word can be any engine (snowboy/pocketsphinx/precise)
- hot word can trigger listening or not
- hot word can play a sound or not
- hot word can be treated as full utterance or not

### CODE REVIEW

**Comment by JarbasAI** [comment]
not sure why this is failing, will investigate

should i make save wake words also save hot words? make a separate config for this? should these also be uploaded for precise? this can come in other PR, or i can make the changes

**Comment by renekliment** [comment]
Hey. Is there any progress on this? I would love for this to get merged. Thank you.

**Comment by methomas98** [comment]
Are there any updates on this? I was hoping to use multiple wake words

**Comment by JarbasAl** [comment]
i will rebase this PR later, right now you can use multiple_wake words with [Voice Satellite](https://github.com/OpenJarbas/HiveMind-voice-sat). It is basically a standalone version of the listener

**Pull request closed without merging**
