### PR TITLE
upgrade Lingua Franca to v0.2.2

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
Update requirements to latest Lingua Franca v0.2.2 - see the [release notes](https://github.com/MycroftAI/lingua-franca/releases/tag/0.2.2). Primarily bug fixes.

## How to test
Run unit tests

## Contributor license agreement signed?
- [x] CLA (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
Did some extra random manual tests and all seems to be in order unless Jenkins finds something.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2654))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2654))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2654))

**Pull request merged**
