### PR TITLE
Migrate to Github Actions

### PR DESCRIPTION
**Pull request by marvin-w**
## Description

Migrates Travis CI to Github Actions.

Open tasks:
- [ ] Coveralls

## How to test

Check Github Actions Runs.

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @marvin-w, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2764))

**Comment by marvin-w** [comment]
Hm, is there a way we can test this without merging it? 

Without coveralls: https://github.com/marvin-w/mycroft-core/actions/runs/362296161
With coveralls: https://github.com/marvin-w/mycroft-core/actions/runs/362314096

**Comment by forslund** [comment]
We could push your branch to a test-branch on this repo maybe, add the test branch to the list of used branches and create a PR?

**Comment by marvin-w** [comment]
Sounds good

**Comment by forslund** [comment]
https://github.com/MycroftAI/mycroft-core/actions/runs/366043215

**Comment by marvin-w** [comment]
Cool, I'll have a look again after work

**Comment by krisgesling** [comment]
Hey @marvin-w, thanks for your work on this already. It certainly proved to be more challenging than I anticipated. 

As Travis-CI.org will shutdown quite soon, Chris has started playing around with it in PR #2817 to see if he can get it all working. That PR is really just to work out what's needed as it's the easiest way to test the config. Once he's nailed down the issues he'll do a new clean PR that includes your commit. We always want to make sure that your efforts are recognized.

I'll leave this PR open in case you're still working on it as well, and if there's any other tricks you worked out while experimenting we'd love to hear about them.

**Comment by marvin-w** [comment]
@krisgesling The only issue that was left here was the coveralls issue. But it turned out this was an upstream issue in the action itself: https://github.com/AndreMiras/coveralls-python-action/issues/7

With this included you could use this as is. Of course you would have to adjust it to your specific needs and features. I kind of forgot this PR sorry.

**Comment by chrisveilleux** [comment]
@marvin-w I have cherry-picked this commit into the feature/github-actions-ci branch in Mycroft-core.  I will make a few changes to it, but will use most of your work.  Thank you for your contribution.

**Comment by chrisveilleux** [comment]
Closing in favor of PR 2819, which includes the commit in this PR.

**Pull request closed without merging**
