### PR TITLE
Fix pip url for Python > 3.6

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
Fixes the url to fetch pip from on versions of Python > 3.6

## How to test
Ensure all Github Actions complete showing it installs correctly.

## Contributor license agreement signed?
- [x] CLA

### CODE REVIEW

**Comment by krisgesling** [comment]
Can't believe I missed it in PR #3073 - but we were grabbing the Python3.6 pip in both branches of the conditional.

Surprising that all the tests were passing still.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-3080))

**Comment by forslund** [comment]
Doh!

I assume this worked since python >=3.7 is backwards compatible with older pip code.

It was meant to be

``` if "${VIRTUALENV_ROOT}/bin/${opt_python}" --version | grep " 3.6" > /dev/null; then```

so the output isn't printed.

**Review by forslund — CHANGES_REQUESTED** [review]
I think the redirection to /dev/null should be added to the grep as was originally intended

**Review by forslund — APPROVED** [review]

**Comment by forslund** [comment]
Best get this in and hide my copy pasta :). The /dev/null fix can be done separately, it's more important that this works as intended.

**Pull request merged**
