### PR TITLE
Catalan translation added

### PR DESCRIPTION
**Pull request by kayron8**
Catalan translation added

### CODE REVIEW

**Comment by forslund** [comment]
Thanks! I'm going to look into what's the causes the date test to fail.

**Comment by forslund** [comment]
Ok, I've checked it over and the problem is that there's no catalan function for `nice_time()` (required by `nice_date_time()`.

Since the date_time.json and date_time_test.json isn't translated it looks like you can simply delete those files to stop the test from trying to run against those languages.

`git rm mycroft/res/text/ca-es/date_time*`

and then commit and push to the branch.

**Comment by forslund** [comment]
Gràcies! Looks good now! Merging

**Comment by kayron8** [comment]
De res (your welcome) :) Thank you for taking time to locate the problem and how to fix it, it's very appreciated. Sorry for the inconvenience, I'm still a newbie on GitHub :S

**Pull request merged**
