### PR TITLE
Feature/kivy display

### PR DESCRIPTION
**Pull request by ken-mycroft**
## Description
Fixes message bus timing bug

## How to test
Verify you no longer see None type object has no method send in the log file

## Contributor license agreement signed?
Yes

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @ken-mycroft, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by JarbasAl** [comment]
how does this impact existing QT gui?
what is a screen?
how do i define a screen?
how is a screen displayed in QT?
Hoe is QML displayed here?
do i have to choose a gui? 
are my 40+ skills supported or am i supposed to rewrite them?
is this optional, do i have to guess what api i should use if they are incompatible? do i write QML or screens?
do i need to duplicate work for every gui or take sides?

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2717))

**Comment by JarbasAl** [comment]
this seem to import some of mark2-skill functionality
add startup actions
add support for kivy

sounds like 2 or even 3 separate PRs to me....

**Comment by krisgesling** [comment]
Pretty sure this was a mistake, so going to close it for now.

**Pull request closed without merging**
