### PR TITLE
#680 - error in msm script

### PR DESCRIPTION
**Pull request by SoloVeniaASaludar**
See issue #680

### CODE REVIEW

**Comment by penrods** [comment]
Hey, thanks for this fix!  Did you intentionally delete the copyright line?

**Comment by SoloVeniaASaludar** [comment]
Yes, I do. Is not mycroft open-source?

**Comment by penrods** [comment]
It is!  But having a copyright does not stop it from being open source.  In fact, by granting the copyright to Mycroft you are insuring it remains open source.

Think of it this way:  If one doesn't explicitly grant the copyright to the project, then it is ambiguous.  That means if something occurs that requires a court to make a decision, then they have to reach out to *everyone* who has contributed to that non-copyrighted project, which could be hundreds or thousand of people.

See: http://www.infoworld.com/article/2839560/open-source-software/sticking-a-license-on-everything.html

**Comment by SoloVeniaASaludar** [comment]
Of course they must have a license (or be public domain) but this license must respect the four freedoms. "All rights reserved", the supressed phrase, does not.
In fact, usual source files in mycroft starts with a header, copyleft, in perfect agreement with foss.

**Comment by penrods** [comment]
I didn't notice that the original checkin held the "all rights reserved" phrase.  Please leave that for us to correct in an independent PR.  I'm reviewing all of the copyright and licensing (it's a big messy process), and we want to be clean when we change anything related to this to prevent legal confusion.  If Mycroft has reserved rights, you aren't able to legally make that change.  Make sense?

**Comment by SoloVeniaASaludar** [comment]
Done.

(PS: it is perfectly legal I suggest any change.)

**Comment by penrods** [comment]
Of course, no qualms about your suggestion -- it exposed a problem to me.  And while I don't honestly think it would cause any long term damage, I'd rather not have it look like you were the one who changed the license, even if it was just for a second.  I've been through a stupid lawsuit before and I don't want to repeat it.

Thanks again for the fix and for pointing this out!

**Pull request merged**
