### PR TITLE
mycroft-use script to switch builds

### PR DESCRIPTION
**Pull request by ajuhl**
mycroft-use is a script that allows you to change builds between stable, unstable, and github checkout
mycroft-use [unstable | stable | github]

### CODE REVIEW

**Comment by forslund** [comment]
Looks like a useful script but it feels a bit out of place here in core. I wonder if it should be in the enclosure-picroft repo or among the scripts used when building the Mark-1 Image?

What do you think?

**Comment by penrods** [comment]
I debated where to recommend it go.  This will be useful in Picroft and on the Mark 1.  I also think under Ubuntu and other package installs.  I'm open for a better suggestion.

**Comment by penrods** [comment]
It will soon allow switching to a Github install, too.  So this is valuable to most devs.

**Comment by forslund** [comment]
I would suggest to add the script when building apt-packages so keeping it
together with the packaging scripts would make sense to me.

Den 20 juni 2017 23:48 skrev "Steve Penrod" <notifications@github.com>:

**Comment by penrods** [comment]
Hmm, yeah that makes sense.  Gotta do a package install first, but that isn't horrible.

**Comment by aatchison** [comment]
I kind of feel like this would be better on picroft. Since we don't have a similar thing for the mark 1 though, I'm not sure. Let me think about this. Also, a package installation includes init scripts, so it would run automatically and would cause trouble with a dev setup. I guess that it might be best in the core repo.

**Comment by penrods** [comment]
I talked to Austin about making the changes to switch the init scripts from package to Github.  Should be doable without too much effort.

**Comment by ajuhl** [comment]
The github fix works with the default github path, but I will need to test to make sure it works when given a custom path.

**Comment by penrods** [comment]
This got pulled in with modifications:

https://github.com/MycroftAI/mycroft-core/pull/1073

**Pull request closed without merging**
