### PR TITLE
Ability to play sound instead of utterance

### PR DESCRIPTION
**Pull request by dalgwen**
==== Fixed Issues ====
issue-2755 -  Ability to play sound instead of an utterance

PULL REQUEST EDITED TO MATCH SOME COMMENTS : this is now a broader PR, with the ability to use sound for all "final" dialog, and not only error one. Several sounds could be used (all those listed in the "sounds" parameter)
This PR is also extended to allow skill developper to use their own sound

====  Tech Notes ====
- Add a new method report_outcome for skills to declare if the utterance passed in parameter is final. For the parameter ("outcome_type"), the possible values are constrained by those available in the "sounds" dictionnary parameter in mycroft.conf.
    With the second parameter "custom_sound" (path to a wav or mp3),  skills can use their own sound, and not only the basic "sounds" from Mycroft. Note : I thought about merging the two parameters, but I think they serve different purposes (one is more a meta information about the utterance, the other is a custom sound for broader use). But I could change this, of course.
    Add corresponding new method parameters in the speak method

- How Mycroft choose between a sound and the utterance with the report_outcome method  ? : 
.. If the utterance is empty (None), the sound will be used. It's the way for the skill developper to force sound.
.. If uterrance is set and outcome_type or custom_sound is set, then Mycroft will check the new parameters (skills_pref_sound to check if the current skills is in the list, or always_pref_sound for a global parameter). If one of this parameter matches, then the sound will be used.
.. In all other cases, the uterrance will be used.

- Add a new error sound. (quite horrible, sorry. It's the wakeword sound, reversed)

- Change some TTS : they originally overrode a method they should not, in my opinion. If my guess is good they should override the inner "_execute" method and not the main public one. I could need some educated guess from the reviewer for this point.

- Implementation choice, not sure of my choice : The sound is played in the TTS module. It could be played upper in the stack but I did this in order to keep the functionality close to its replacement. And also using the queue seems to me the proper way to replace an uterrance.

TODO ? : 
- The "dont_understand" sound I made is horrible. If someone has a better one... Please be my guest !
- in the "sounds" parameter list available by default, one sound doesn't seem to be in the filesystem ('end_listening')
- To add other sounds to complete the range of choices.

====  Documentation Notes ====
Two new parameters can force Mycroft to do feedback with a brief sound instead of a complete utterance :
skills.skills_pref_sound: a list of skills who should use sound. Use the class name.
always_pref_sound: boolean to force Mycroft to use sound for feedback, wherever it is possible.
Skill developers must use the "report_outcome" method, or the speak method with the "outcome_type" or "custom_sound" to use this functionality

==== Localization Notes ====
NONE

==== Environment Notes ====
NONE

==== Protocol Notes ====
NONE

## Description
fixes #issue-2755

## How to test
Modify a skill (for example, fallback-unknown), to use "report_outcome" instead of speak_dialog. Or use "outcome_type"/"custom_sound" parameter with the speak method
Example :
`self.speak('unknown', outcome_type='dont_understand')`
`self.report_outcome('dialog', outcome_type='dont_understand')`
Activate the replacement sound for this skill, either by the global configuration parameter (always_pref_sound) or by white listing the "UnknownSkill" in the list parameter skills.skills_pref_sound (class name)
Make mycroft says this dialog in fallback-unknown by asking him something nonsensical.
Instead of the unknown dialog, Mycroft should play 'dont_understand' the sound.

Do the same but with the parameter 'custom_sound' to play any sound on the file system.

## Contributor license agreement signed?
CLA [X]

### CODE REVIEW

**Comment by forslund** [comment]
I was wondering if a simpler solution could be to have a special method in skills

```python
    def report_error(self, dialog, data):
        if _should_play_error():
            wait_while_speaking()
            play_wav(error_wav) # where error_wav is found somehow :)
        else:
            self.speak_dialog(dialog, data)
```

It's simpler but not as nice as your version, enqueuing the error sound in the tts playback queue like that.

I also wonder if we'd want a similar method as above with your changes to give a nice wrapper that just calls speak_dialog with the error flag set.

**Comment by dalgwen** [comment]
No problem, I let you (or other experienced mycroft developer) decide what is best, between simplicity or use of the playback queue mecanism.
Just tell me what to do and I will be happy to commit some modifications (or you can do it yourself if you rather ; I'm not very knowledgeable of the usual process ?)

**Comment by krisgesling** [comment]
Hey, thanks for this great PR. This is an area that I think will expand significantly over time and it would be great to provide Skill developers with a range of consistent sounds to help users understand the outcome of their queries.

The most direct example would be a "success" sound. Though I can also see use cases for things like:
- action taken eg sound increase or decrease on the Mark 1
- adding or removing things from a list - more subtle than success and whilst both actions are considered successful, they are two distinct actions
- turning on some {thing}
- email sent
- etc

I also like the option for users to force the short response, however I think the by-product of this will be more Skills using the short sounds instead of dialog.

At the moment I'm leaning toward a new method rather than adding an argument primarily because it can be used without dialog and still make logical sense. Eg when used with dialog it seems roughly equivalent:
```
self.speak_dialog(dialog, data, is_error=True)
self.report_error(dialog, data)
```

However when used to intentionally only play the error sound it would be either:
```
self.speak_dialog(None, is_error=True)
self.report_error()
```

An alternative would be to have a single method, something like:
```
report_outcome(type="error", dialog, data)
```

**Comment by krisgesling** [comment]
I've just started a poll on the forums and chat to get a sense of how other dev's would prefer to trigger this sort of thing:
- https://community.mycroft.ai/t/short-sound-to-indicate-error/9750
- https://chat.mycroft.ai/community/pl/h5fcozioki8nppxduyunscmjko

**Comment by lnguyenh** [comment]
How about a `self.sound(type='error')` that would echo the existing `self.speak()`, and clearly keeping sound and speech separated and up to the developer to decide which he wants, or even combine?
Or even possibly `self.sound.confirm()`,  `self.sound.error()`, ..., a bit like `self.log.info()` and `self.log.warning()`

**Comment by MichaIng** [comment]
Probably an additional backend for "regular" logs would be an alternative, so aside of file logging, allow to set an optional log level (none/off by default) for "acoustic" log output, with a flag to either give a signal sound only or speak the error log text. So regular logging is done as before, and it's up to the admin to enable acoustic log notification a spoken log entries.

The bonus is that errors of mycroft-core can be made acoustic as well, as currently in cases there is no feedback at all when some internal error happened. The downside is that this does not allow developers to force that generic error output. Also Python error trances and such would need to be excluded, to not have it speaking code, so only the log text string.

**Comment by ChanceNCounter** [comment]
I've fooled around with "multiple" sounds in the past, and it was pretty fun. I never got anything in a PR-able state, but I had an error sound, a cancellation sound, and a success sound, in addition to the wake sound.

So I'm just here to +1 that idea.

**Comment by krisgesling** [comment]
the `self.sound()` is an interesting one, and perhaps something that should also get added. What I like about having the speech and sound explicitly combined is that in the future we could do some more intelligent decisions around which type of response makes the most sense in that situation.

Some quick examples that come to mind are:
- a user has explicitly defined a preference
- the physical context of where a device is deployed makes one or another more appropriate
- newer users might need more verbose output, but don't need to hear the same thing over and over again.

**Comment by ChanceNCounter** [comment]
How about:

* A tone for the wake sound
* A lower tone for STT returned "silence"/on dismissal
* A higher tone for STT success
* Speak "I don't understand" on complete intent failure
* A buzz for "an error occurred in X skill" and set a shortish-lived flag for `thatSkill.recent_error`
* Speak "An error occurred..." if the same skill raises an error while the flag is set

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2756)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2756/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2756/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2756/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2756/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2756/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2756))

**Comment by dalgwen** [comment]
4 months later... Sorry !
I made some changes in order to integrate some of your comments. (description is also updated)
The PR is now broader, with
- not only error sound, but also all "confirmations"
- the ability to queue any sound.

**Comment by JarbasAl** [comment]
playing sounds in the speak methods feels wrong, i dont think this belongs in TTS at all, why not add a standalone method for this? there is already the `acknowledge` method which seems to be very much in line with the intent of this PR

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2756))

**Comment by dalgwen** [comment]
> playing sounds in the speak methods feels wrong, i dont think this belongs in TTS at all, why not add a standalone method for this? there is already the `acknowledge` method which seems to be very much in line with the intent of this PR

I liked the idea of using the queue located in the TTS. Seems less 'anarchic' ?
And also, it seemed logical to let the responsabilty of playing sound to the audio module ; and the `acknowledge` method didn't do this. Keeping separation of role could be important in the future (we could imagine just a light client for processing voice and audio in a "satellite"  embedded device ?)
But I agree with you on this, using TTS for this feels "off". I would rather create a class upper in the stack, something like a sound producer, parent of TTS and this ? But it is too broad a refactor for me.

Anyway, if all senior dev in this project converge on a choice, whatever it is, I'd be happy to rewrite.

**Comment by JarbasAl** [comment]
changing the `acknowledge` method or adding a new generic one to replace it (+deprecation warning) makes more sense to me, the new method `play_sound`(?) would account for all sound use cases instead of only playing the acknowledge sound, the signature of the `speak` method is already big enough, a new method could have as many parameters as needed

using the playback queue is not a bad idea, but that also feels like a broader PR, where the playback queue should be taken out of TTS into the audio service directly, then used to queue all sort of sound files

keep in mind the playback of music is special, speech/sounds should play over the music and have their own queue, so when i say to move the playback queue out of the TTS engine (probably into `mycroft.audio.speech`) i don't mean to merge it with `mycroft.audio.audioservice`

note that i am simply a community member, so take what i say with a grain of salt, someone from the mycroft team may disagree with my view. That said i think this could be done into 2 separate PRs, you can just focus on adding the `play_sound`(?) method

**Comment by krisgesling** [comment]
Agree this is part of a broader rewrite of how audio output is managed in Mycroft. Jarbas articulated many of the important points above. 

But sticking to this PR, I'd say we really need to document how we expect this to work, what the supported outcomes are, etc.

Having multiple ways to trigger the same thing provides choice, but it also adds complexity and confusion. I don't really want to merge this feature until we think that through properly.

**Comment by dalgwen** [comment]
OK. It started with my need to provide user some way to get rid of long error utterance.
But it is clear it is now waaayyy too large for my shoulders. I will close this pull request and wait for other folks to progress on this subject.

Thanks for your comments

**Comment by krisgesling** [comment]
Hey, I think it is a big shift and sorry we couldn't take on this bit in isolation.

It's great to have stimulated discussion on it though!

**Pull request closed without merging**
