### PR TITLE
error in mic.py causes no phrase longer to 3 seconds can be used

### PR DESCRIPTION
**Pull request by SoloVeniaASaludar**
Error in mic.py causes no phrase longer to 3 seconds can be recorded.
See issue #595 for details.

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
I should have probably put this in the code beforehand to explain it, but that line, `recorded_too_much_silence = num_chunks > max_chunks_of_silence` is checking whether or not it should continue waiting for more audio even though it hears silence. It should act like a timer since it essentially prevents quiet noise less than 3 seconds from being recorded. However, the moment the user speaks, the noise will go above 0 and thus will indeed record more than 3 seconds. [Here's a better explanation](https://gist.github.com/MatthewScholefield/fb66d02e315d27a08094e1162dc31ba1#recording-the-query). (Specifically, the last part of `Recording the Query` talks about this).

However, if you were having issues with that part, it means there's something else going wrong. Either way, we should still test your changes and see if they work better on different devices than the original.

**Comment by SoloVeniaASaludar** [comment]
Hi,

Thanks for your answer.

After 3 seconds from method start, the condition "recorded_too_much_silence" pass from false to true. For this reason, the if condition:

```
if quiet_enough and (was_loud_enough or recorded_too_much_silence):
                phrase_complete = True

```

is, after 3 seconds, equivalent to:
```

if quiet_enough:
                phrase_complete = True
```

In this situation, after these initial three seconds, the record finish any time that "quiet_enough" becomes true. And "quiet_enough" is related only to the characteristics of current chunk and noise threshold. In my test, near than in all chunks "quiet_enough" is true.

**Comment by MatthewScholefield** [comment]
Well, the problem is that in the beginning, we are certain the user has not spoken. Because of this, we can wait with a fair amount of certainty for the user to speak. However, the longer we wait, there's more of a chance that the algorithm is incorrect and that the user has indeed spoken but possibly did not trigger enough noise. For this reason, it would be annoying to sit there waiting in the case that the user has actually already said their sentence. So, we can only use this little trick in the first three seconds. This is what I meant by the last set of parenthesis: `(however, after a reasonable time limit, the listener will timeout and return even if still waiting for some noise and was_loud_enough is still False).`

As for your problem with `quiet_enough` should not always be `True`. If this is the case, it probably means there's a problem with the way we track the threshold. Can you try getting the original code to work by only changing `self.multiplier`? Otherwise, I think I have another idea to improve the threshold. I can give you a version later today to test.

**Comment by SoloVeniaASaludar** [comment]
In the issue you can see a full trace of the energy, noise and threshold levels during the test.

**Comment by penrods** [comment]
I was also working on several things around the wake-up word in my PR #647.  I believe those changes make this unnecessary.

**Comment by SoloVeniaASaludar** [comment]
yes, changes in #647 are very related. Can I suggest a "cosmetic" change, that made things more easy to follow ? Instead of:

```
            if quiet_enough:
                silence_duration += sec_per_buffer
                if silence_duration < self.MIN_SILENCE_AT_END:
                    quiet_enough = False  # gotta be silent for min of 1/4 sec
            else:
                silence_duration = 0
             recorded_too_much_silence = num_chunks > max_chunks_of_silence
             if quiet_enough and (was_loud_enough or recorded_too_much_silence):
                 phrase_complete = True

``` 
use:

```
            if quiet_enough:
                silence_duration += sec_per_buffer
            else:
                silence_duration = 0
             recorded_too_much_silence = num_chunks > max_chunks_of_silence
             recorded_enough_silence =  silence_duration >= self.MIN_SILENCE_AT_END:
             if recorded_enough_silence and (was_loud_enough or recorded_too_much_silence):
                 phrase_complete = True

```

**Pull request closed without merging**
