### PR TITLE
build script for Solus

### PR DESCRIPTION
**Pull request by jasonehines**
I created a build script for Solus.

(I hope I did this correctly, it's been awhile since I used git)

### CODE REVIEW

**Comment by aatchison** [comment]
Nice to see you again @jasonehines! I would try out but I'm not running Solus anywhere.

**Comment by jasonehines** [comment]
Thanks. It worked on my Solus install.

**Comment by jasonehines** [comment]
Don't merge this.

I created a fresh VM of Solus to make sure I didn't miss any dependencies, but I missed something. I'll fix it this afternoon.

**Comment by jasonehines** [comment]
@aatchison is there a way to update this with git? Sorry, I'm not that great with git.

**Comment by aatchison** [comment]
You should be able to make a new commit the branch and push. It will update the PR. 😉

**Comment by jasonehines** [comment]
Oh, Cool.

**Comment by jasonehines** [comment]
This should be good to go now.

**Comment by MatthewScholefield** [comment]
I will test this in a moment. Also, glad to see another Solus user around here :). Just looking at the script, should there be a second `-y` on the other `eopkg` call? (As a side note, I think `-c system.devel` can be combined with other package names)

**Comment by jasonehines** [comment]
@MatthewScholefield I'm going to test combining them in a clean install using a virtual machine.

**Comment by jasonehines** [comment]
@MatthewScholefield nice catch.

**Comment by jasonehines** [comment]
I've totally forgotten how to do that in git. What command should I be looking for?

**Comment by MatthewScholefield** [comment]
I could be wrong but I think you'd do something like git checkout upstream/dev filename

**Comment by jasonehines** [comment]
I hope I did that correctly. Let me know if I didn't.

**Comment by jasonehines** [comment]
well I guess I didn't do it correctly. Can someone tell me how to fix it?

**Comment by MatthewScholefield** [comment]
There's probably an easier way but this should work. It will just reset everything and copy back in the file. Note that this does away with any commit history and thus will forcefully update the hash so anyone who pulled from your fork will have to re-clone. This will also move any commits you have on `master` to a new `backup` branch.
```sh
cp build_host_setup_solus.sh ../ # copy script out of git folder
git checkout master # Make sure we are still on master branch (the one this PR is looking at)
git checkout -b backup # Makes a branch called "backup" with the exact same commits
git branch -D master # Permanently deleted all changes to master (but don't worry, any other small changes are saved in the "backup" branch)
git checkout upstream/master # Get a fresh copy
git checkout -b master # label this locally as "master"
mv ../build_host_setup_solus.sh . # Bring back script
git add build_host_setup_solus.sh
git commit -m "Added build script for Solus" # Commit with whatever message you want
git push --force -u origin master # Forcibly replace all the commits on your fork with the new one (rewrites history). In addition, the -u sets the locally labelled "master" to track origin/master

# Now, if desired, to get back to the old commits/changed files
git checkout backup
```

**Comment by MatthewScholefield** [comment]
@jasonehines Can you try the commands above and let us know what happens? Thanks! I'm excited to get some Solus build scripts into Mycroft :smile:.

**Comment by ethanaward** [comment]
@jasonehines Any update on fixing the git errors?

**Comment by penrods** [comment]
Hey @jasonehines, I'd love to get this pulled in.  If Github is just causing you issue we can come up with a couple different approaches.  I'm thinking:
1) You could start a new PR that only has the  build_host_setup_solus.sh in it
2) We could start a PR, pulling the  build_host_setup_solus.sh out of this one and just @jasonehines to include you in the history.

The second choice isn't quite a clean, but would be easiest for you.  Your call.

**Comment by jasonehines** [comment]
I’ve been busy on a rush job. I might be able to get back to it towards the
end of the month.

**Comment by penrods** [comment]
Thanks, no pressure.  Just trying to figure out if we can help.

Also, when you have a chance please fill out a CLA via https://mycroft.ai/cla so I can accept this.  I'm making CLAs a requirement for accepting PRs now.

**Comment by penrods** [comment]
I'm going to go ahead and close this as we have merged all build commands into the main dev_setup.sh.  If you would still like to include this, please resubmit in a new PR.

**Pull request closed without merging**
