### PR TITLE
Check if GUI is connected rather than maintain list of platforms

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
There are already many Mycroft platforms that have GUIs and this will only grow. We want to know if the device has a GUI connected rather than if it is in a pre-defined list of platforms.

## How to test
With the new latest Wikipedia installed - ask common query a question and ensure it is still displayed.

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-3025))

**Review by forslund — CHANGES_REQUESTED** [review]
Nice improvement, the test case  needs to be removed / updated otherwise it should be good to go!

**Comment by krisgesling** [comment]
In order to be able to run a scenario that exhibits different behaviour when a GUI is connected, I mocked the GUI class to provide a settable connected attribute. Interested in any opinions on this approach.

This also removes the concept of a "Mark II" from the test as it should be any device with a connected display.

**Review by forslund — APPROVED** [review]
Super nice! Approved

**Review by JarbasAl — APPROVED** [review]

**Pull request merged**
