### PR TITLE
Hot Word detection

### PR DESCRIPTION
**Pull request by JarbasAI**
Listening for common words could be useful

proposal:
- add any number of hot words to config
- hot word can be any engine (snowboy/pocketsphinx)
- hot word can trigger listening or not
- hot word can play a sound or not
- hot word can be treated as full utterance or not

a WakeWordFactory should eventually be made

youtube video demo: https://www.youtube.com/watch?v=GIkBh0VFmbc&feature=youtu.be

Also added more logs and made "STT could not transcribe audio" failure send a speak message instead of failing silently

### CODE REVIEW

**Comment by penrods** [comment]
Does your other PR (the Hotword factory) make this obsolete?

**Comment by JarbasAI** [comment]
no, this PR allows many hot words and actually works much better with the other PR

this adds optional hotwords, which can do any of the following:
- play sound
- emit an utterance
- trigger listening

needs refactoring, i actually had this one depending on the other and downgraded it (because  i wasnt sure about snowboy support in the other one)

**Comment by UW-SG** [comment]
I am trying to run this pull request but the mycroft.sh script doesn't seem to work. Please suggest. No detached screens.

sg@sg-VirtualBox:~/mycroft-core$ ./mycroft.sh start
Started mycroft-service
Started mycroft-audio
Started mycroft-skills
Started mycroft-voice
Started mycroft-cli
sg@sg-VirtualBox:~/mycroft-core$ screen -list
No Sockets found in /var/run/screen/S-sg.

**Comment by JarbasAI** [comment]
this PR is not functional, needs update, do not try to use it

**Comment by renekliment** [comment]
@JarbasAI Looking forward to seeing this fixed and merged :smiley:

**Comment by JarbasAI** [comment]
https://github.com/MycroftAI/mycroft-core/pull/1233 redone

**Pull request closed without merging**
