### PR TITLE
Clear registered vocab when skill is unloaded

### PR DESCRIPTION
**Pull request by forslund**
## Description
This adds a search and destroy method moving through the Adapt Trie removing any keywords belonging to the skill when skill is shutdown.

This should fix 50% of the issues described in #2866.

## How to test
- Start Mycroft
- Enter the word `jokes` in the CLI and assert you get a suitably bad joke
- Take the joke skill's `Joke.voc` vocab and remove the word `jokes` then save the file
- Skill will reload
- Enter the word `jokes` again and assert that Mycroft don't know what your talking about
- Enter `joke` and make sure that works as expected

## Contributor license agreement signed?
CLA [ yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2867)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2867/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2867/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2867/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2867/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2867/logs/enclosure.log)

**Comment by JarbasAl** [comment]
shouldn't this be made against adapt repo instead? feels like the `find_type` method belongs somewhere in there

if its faster it can be merged as a workaround, but maybe leave a TODO + Issue in adapt repo

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2867)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2867/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2867/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2867/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2867/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2867/logs/enclosure.log)

**Comment by forslund** [comment]
I'm still pondering on how to do it best in adapt. Possibly a search/remove using regex / globbing matches.

Adapt has by tradition no remove code so we'll see how well those patches are received :)

**Comment by forslund** [comment]
Opened adapt PR https://github.com/MycroftAI/adapt/pull/122

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2867))

**Comment by forslund** [comment]
Going to close this, got some excellent feedback over at the Adapt PR telling me why this is not a good idea and will iterate on it there.

**Pull request closed without merging**
