### PR TITLE
Auto update optional

### PR DESCRIPTION
**Pull request by JarbasAI**
this allows users to disable the msm auto update feature, msm can still be used, but will not be invoked by skills main

for users looking for more security this is a desired option, as illustrated by the evil skill :)

### CODE REVIEW

**Comment by forslund** [comment]
Good idea!

I'd like a couple of small modifications:
- instead of returning directly in the download_skills method I think it would be clearer if it wasn't called at all so update l330 to

```python
            if time.time() >= self.next_download and AUTO_UPDATE:
                self.download_skills()
```

- Instead of loading the autoupdate config value only at startup, load it before the check so we perhaps can add a voice command to start/stop updating during runtime.

**Comment by JarbasAI** [comment]
should i do             

       # Update skills once an hour
        if time.time() >= self.next_download:
            # check if auto update is enabled 
            AUTO_UPDATE = Configuration.get().get("skills", {}).get(
                "auto_update", True)
            if AUTO_UPDATE:
                self.download_skills()
or

       # check if auto update is enabled
        AUTO_UPDATE = Configuration.get().get("skills", {}).get(
            "auto_update", True)
        
        # Update skills once an hour
        if time.time() >= self.next_download and AUTO_UPDATE:
            self.download_skills()

i like it best only checking the flag before download but after the time out, otherwise the logs get a little polluted with config loading messages


so it checks the flag once an hour instead of once every 2 seconds

**Comment by forslund** [comment]
Rebased and merged in #1344. Thanks @JarbasAI !

**Comment by tlc** [comment]
I just ran into a problem that might be related to this.  Then again I'm new to Mycroft.

On a new install of mycroft (on Ubuntu 16.04), I ran _msm/msm default_, but mycroft wouldn't load any skills except _pairing_.  I looked at the skills loading and saw it wasn't getting past this:

>  if (exists(SKILLS_DIR) and
>         (self.next_download or not update)):

After I changed my config to _auto_update: false_, they loaded.

**Pull request closed without merging**
