### PR TITLE
Fix extractnumber_en failure on "%" (#2110)

### PR DESCRIPTION
**Pull request by ChanceNCounter**
Closes MycroftAI/mycroft-core#2110

---

CLA [ yes ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

(wait for Coveralls - test suite wouldn't run locally)

### CODE REVIEW

**Comment by JarbasAl** [comment]
i think it makes more sense for that to be handled in [_tokenize](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/util/lang/parse_en.py#L145)

that will make it more useful down the line for other languages, quick note here, this is lagging behind lingua franca since https://github.com/MycroftAI/lingua-franca/pull/28

**Comment by ChanceNCounter** [comment]
Yeah. We should discuss the implications for Lingua Franca, as well as the other points we mentioned in the issue. I'll close this for now.

**Comment by ChanceNCounter** [comment]
Discussed in chat: Jarbas suggests (and I agree) merging the hotfix, and implementing a proper fix in Lingua Franca, which will end up in Core soon enough.

**Comment by JarbasAl** [comment]
chat conversation here for reference https://chat.mycroft.ai/community/pl/yj486ji5gpyxtpgwsupb1rdcna

**Comment by forslund** [comment]
Sounds good, in @JarbasAI and @ChanceNCounter I trust.

Could you cherry-pick 4016efa into this PR as well to get @ChristopherRogers1991 testcase?

**Comment by forslund** [comment]
Excellent, thank you. Merging!

**Pull request merged**
