### PR TITLE
Dev add nl nl

### PR DESCRIPTION
**Pull request by g3rb3n**
## Description
Added voc and dialog files for nl-nl
Added date-time parser and config for nl-nl
Modified format.py to make sure thousands also get parsed correctly in nl-nl as \3en\4 \1en\2, e.g. 2191 year should be parsed to 'een en twintig een en negentig'

## How to test
./start-mycroft.sh unittest
./start-mycroft.sh singleunittest test/unittests/util/test_format.py would be a nice feature
I added in my local repo in start-mycroft.sh:
```
    "singleunittest")
        source-venv
        pytest "$@"
        ;;
```
No tests for voc and dialog files.

## Contributor license agreement signed?
Requested the agreement, still waiting for a mail from Joshua.
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
Hi @g3rb3n can you fix the codacy issue. it seems to just be an unused variable.

**Comment by forslund** [comment]
Hi @g3rb3n should I go ahead and fix the pep8 issues and codacy problem or do you want to handle it?

**Comment by forslund** [comment]
Hi @g3rb3n You can use the *pep8* tool from the command line `pep8 FILENAME` (installed in the mycroft venv). I also like to use [pep8-git-hook](https://github.com/cbrueffer/pep8-git-hook) to automatically check for issues when trying to commit.

For the Codacy I can't quite say which checks are done. You can use `pylint` but that will likely show a lot of other issues. I'll try to see if I can find a list somewhere.

According to pep8-speaks comment above there are a couple of issues still:

```
    In the file mycroft/util/lang/format_nl.py, following are the PEP8 issues :

    Line 161:9: E265 block comment should start with '# '
    Line 352:1: E302 expected 2 blank lines, found 1

    In the file test/unittests/util/test_format_nl.py, following are the PEP8 issues :

    Line 105:13: E128 continuation line under-indented for visual indent
    Line 107:13: E128 continuation line under-indented for visual indent
    Line 109:13: E128 continuation line under-indented for visual indent
    Line 111:13: E128 continuation line under-indented for visual indent
    Line 113:13: E128 continuation line under-indented for visual indent
    Line 115:13: E128 continuation line under-indented for visual indent
```

**Comment by g3rb3n** [comment]
Thank you for the suggestions! 

Really weird that PEP8 speaks send this email at 01:05 UTC on 2018-12-07 and no updates thereafter.
>>>
There are no PEP8 issues in the file mycroft/util/format.py !
There are no PEP8 issues in the file mycroft/util/lang/format_nl.py !
<<<
It seems that PEP8 first send a message that all was okay and at 02:00 updated the comment without sending an email.

**Comment by forslund** [comment]
Yeah, that is weird. I believe it did an edit to the original message and edits don't generate emails or something.

Thanks for taking care of those issues. Will do final review tests shortly.

**Comment by forslund** [comment]
Tested and works nicely. Many thanks for this contribution!

**Pull request merged**
