### PR TITLE
Upgrade gTTS to fix Google voice

### LINKED ISSUE #2825: gTTS needs to be upgraded to 2.2.2 on dev branch
**Describe the bug**
When using Google TTS, the audio service returns an error and never returns audio.
```
2021-02-06 02:39:24.895 | ERROR    |     1 | mycroft.audio.speech:mute_and_speak:134 | TTS execution failed (gTTSError('200 (OK) from TTS API. Probable cause: Unknown'))
```

I had to upgrade `gTTS` from `2.2.0` to `2.2.2` to fix the issue.

```
pip install gTTS -U
Collecting gTTS
  Downloading https://files.pythonhosted.org/packages/5f/b9/94e59337107be134b21ce395a29fc0715b707b560108d6797de2d93e1178/gTTS-2.2.2-py3-none-any.whl
Requirement already satisfied, skipping upgrade: click in /opt/mycroft-venv/lib/python3.7/site-packages (from gTTS) (7.1.2)
Requirement already satisfied, skipping upgrade: six in /opt/mycroft-venv/lib/python3.7/site-packages (from gTTS) (1.15.0)
Requirement already satisfied, skipping upgrade: requests in /opt/mycroft-venv/lib/python3.7/site-packages (from gTTS) (2.20.0)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /opt/mycroft-venv/lib/python3.7/site-packages (from requests->gTTS) (1.24.3)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /opt/mycroft-venv/lib/python3.7/site-packages (from requests->gTTS) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /opt/mycroft-venv/lib/python3.7/site-packages (from requests->gTTS) (2020.12.5)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /opt/mycroft-venv/lib/python3.7/site-packages (from requests->gTTS) (2.7)
Installing collected packages: gTTS
  Found existing installation: gTTS 2.2.0
    Uninstalling gTTS-2.2.0:
      Successfully uninstalled gTTS-2.2.0
Successfully installed gTTS-2.2.2
```

**Environment:**
 - Device type: Raspberry Pi 4
 - OS: Raspberry OS 64-bit
 - Mycroft-core version: dev

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
Restore Google voice functionality with updated Python package.

Fixes #2825

Thanks to @goldyfruit for diagnosing and testing the updated package.

## How to test
Switch voice to Google and see if it works against gTTS 2.2.0 vs 2.2.2

## Contributor license agreement signed?
- [x] CLA

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2831))

**Review by forslund — DISMISSED** [review]
Note that this will not automatically update 2.2.2 to 2.2.3 if a new release is pushed upstream.

**Comment by forslund** [comment]
Looks like the gtts language list has been updated so `en-us` is just `en` and the test case needs to be updated at[test_google_tts.py:L17](https://github.com/MycroftAI/mycroft-core/blob/dev/test/unittests/tts/test_google_tts.py#L17)

**Comment by krisgesling** [comment]
Thanks for pointing out the deprecated lang codes. I've also removed these from the cached list of supported languages, and switched all references to the two-character "en".

And yeah, the relaxed requirement definition won't automatically update the package but figured it would at least work for new installs. Still need to setup the automated testing on all these so we can proactively and confidently update rather than wait for things to break.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2831)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2831/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2831/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2831/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2831/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2831/logs/enclosure.log)

**Review by forslund — APPROVED** [review]
Looks good,

`gtts.tts_langs()` returns zh-CN and zh-TW (captal letters) in addition to the updated set, reading the code they look active but I might be wrong.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2831))

**Pull request merged**
