### PR TITLE
Fix remote settings overwrite at startup

### PR DESCRIPTION
**Pull request by forslund**
## Description
This is a suggestion to improve the usability of the local settings, an implementation of an idea mentioned in #2698

Currently Mycroft always mangels any local settings changes at startup. This PR adds a cache of the last settings from home on disk and only updates skills if there is an actual change.

This means that as if a member is changed locally (manually edited or changed by the skill itself) it will be kept until another  change is made to the skill on Home.

In my opinion this is a more intuitive way of handling the changes, but it's definitely up for discussion / rejection.

## How to test
Ensure that skill updates from home works as normally. Edit a settings.json while Mycroft is turned off and make sure that the change doesn't get overwritten when mycroft starts again.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2707))

**Comment by JarbasAl** [comment]
this looks good, its a partial solution but ensures the settings updated event means exactly that

2 way sync is still needed however

issue clarification:
- update setting X locally
- update setting Y in web interface
- settings update replaces X

Out of scope for this PR either way, we could separate local settings from remote settings somehow, but any approach like that is just hacky, the proper fix is selene side

**Comment by forslund** [comment]
I definitely agree that the two-way sync is what's needed. But in addition to that I think this is needed as well as core shouldn't send settings updated messages to all skills at startup even if they've been synced.

**Comment by ChanceNCounter** [comment]
I've confirmed that it works as described:

1. Dismiss Mycroft, get feedback
2. Disable Dismissal feedback in Home
3. Ensure that the change synced, dismiss Mycroft, no feedback
4. Shut Mycroft down
5. Enable Dismissal feedback in Home
6. Start Mycroft, still no feedback from Dismissal ✅ 
7. Go back to Home, don't even touch the setting, just push "save" again
8. Ensure that the change synced, dismiss Mycroft, get feedback

The code looks straightforward, I can't see what could possibly be wrong with it, and it runs as described. Only thing I can't say is whether it'll break what's underneath that allows it to work. Where's the main change itself? I don't see anything to do with the overwriting loop.

**Comment by forslund** [comment]
The main change is [L353](https://github.com/MycroftAI/mycroft-core/pull/2707/commits/8c8a210b8dc98bb7282b013dd993b05e9f0896b0#diff-3e08b7eb36a753ba228c9661639c672c4012acd93c18492f2ec48ff461fe2927R353), the settings already only request skills to reload settings if there is a difference. At above mentioned line the copy of the settings used for comparison when identifying changes is restored so the initial download after startup also has a reference.

The behavior you describe doesn't sound quite correct, gonna see if I can replicate that. A change on home while the device is turned off should trigger an update, the idea is that if there is no change on home since last fetch but a local change has been made, the local change should not be overwritten as soon as Mycroft is restarted.

**Comment by forslund** [comment]
I haven't been able to replicate your behavior using my test skill, going to try the dismissal skill as well.

I did find and remove an unused member variable assignment.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2707))

**Comment by ChanceNCounter** [comment]
To be honest, I thought the behavior I saw was what you intended. It made sense to me.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2707)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2707/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2707/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2707/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2707/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2707/logs/enclosure.log)

**Comment by krisgesling** [comment]
Hey Chance, thanks for checking it out.

I wasn't clear from your first message of whether you tried changing the setting locally on the device?

I was thinking along the lines of

1. Dismiss Mycroft, get feedback
2. Disable Dismissal feedback in Home
3. Ensure that the change synced, dismiss Mycroft, no feedback
4. Modify Dismissal Skill settings locally to enable feedback
5. Shut Mycroft down
6. Start Mycroft - should get feedback from Dismissal showing remote settings haven't synced
7. Go back to Home, enable feedback, and save
8. On Home, disable feedback, and save
8. Ensure that the change synced, dismiss Mycroft, get no feedback

Might be even easier to see with something like the News Skill where you can switch between many default stations. Or something with a text input.

**Comment by ChanceNCounter** [comment]
Thanks, Gez! I was able to confirm the behavior as described, this works and I'm not sure what happened the first time around. It may simply be that I didn't wait long enough before reporting back, and didn't notice it overwriting on sync.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2707))

**Comment by krisgesling** [comment]
Excellent, thanks Chance - if you are happy to submit an approving code review I'll merge it in :)

**Review by ChanceNCounter — APPROVED** [review]
Working as described on Debian/dev branch.

**Review by krisgesling — APPROVED** [review]
Reviewed by Chance

**Pull request merged**
