### PR TITLE
468 - Fix tests

### PR DESCRIPTION
**Pull request by ethanaward**
This fixes some of the tests that are currently broken. Most only required minor changes. Some of the tests seem to require pairing to work properly, and a few of the audio consumer tests are still not working.

### CODE REVIEW

**Comment by jdorleans** [comment]
Ok, here is a first suggestion... let's break this into small chuncks. Don't take all tests to be fixed into one task. Let's concentrate on fixing a group of them properly then we can already ship them into the next release. So we tackle the other ones. How that sounds? I'll check on what you've done so far. Thx for that again!

**Comment by jdorleans** [comment]
Let's ship this now, then we create specific tasks for further fixes.

**Comment by aatchison** [comment]
Hmm, we seem to have a few conflicts here now.

**Comment by forslund** [comment]
This one can be closed right?

**Comment by ethanaward** [comment]
This has been closed, the bugfixes have already been addressed.

**Pull request closed without merging**
