### PR TITLE
feat/ cli GUI client

### PR DESCRIPTION
**Pull request by JarbasAl**
## Description
Adds a very simple CLI GUI, useful for debugging and skill developers. 

Original a quick and dirty script, but @AIIX suggested i made a PR

simply_gui

## How to test
```./start-mycroft.sh gui```

## Contributor license agreement signed?
CLA [yes] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by AIIX** [comment]
The dev branch seems to have an issue with establishing multiple gui client connections and gui debug client doesn't work when gui is already running a similar issue to: https://github.com/MycroftAI/mycroft-core/issues/2525

It works nicely on the bugfix workaround-multi-displays branch, so this branch should be merged in dev for this to work correctly: https://github.com/MycroftAI/mycroft-core/tree/bugfix/workaround-multi-displays

**Comment by JarbasAl** [comment]
im making a cli GUI, this is now included as a debugger

https://github.com/JarbasAl/Mycroft_cli_GUI

**Comment by krisgesling** [comment]
Hey sorry I haven't looked at this properly before. I really like it as a developer focused GUI debugging tool.

I've been leaning toward core being as lightweight and agnostic as possible, so that it can be as "composable" as possible through build recipes. I'm wondering if it makes the most sense to have it as a separate package, rather than included in core? 

Same with tools like MSK. As we move to more end-user installations, I don't see a need to have it on every end-user device. I think it makes sense on Picroft as it's a hackers/makers release. But on the Mark II - not necessarily.

I'm really just thinking out loud here, so interested in others thoughts on this.

**Comment by JarbasAl** [comment]
this is part of my TUI  https://github.com/JarbasAl/Mycroft-TUI  it can be used as a standalone script, its still WIP and im still figuring out how i want to package it, but its available for anyone to use

Makes no difference to me if its part of core or not, if you feel its just bloat feel free to close this PR

**Comment by krisgesling** [comment]
Would it be possible to load it as a plugin using the [methods Ake's proposed](https://github.com/MycroftAI/mycroft-core/pull/2594/commits/74cb9c48f0c9f5c31faf1ab729d3fa9a59504194)?

**Comment by JarbasAl** [comment]
> Would it be possible to load it as a plugin using the [methods Ake's proposed](https://github.com/MycroftAI/mycroft-core/pull/2594/commits/74cb9c48f0c9f5c31faf1ab729d3fa9a59504194)?

i dont think that makes sense, this is not a plugin, it just connects to the bus

i can just put it up on pip, then people can do something like
```
pip install mycroft-gui-debugger
(.venv) mycroft-gui-debugger
```

**Comment by krisgesling** [comment]
Yeah fair call. If it is on PyPI then we can easily add something to provide a simple installation for it. 
> "If you're a dev, do you want these tools installed - [x, y, z]"

Although maybe that should really be in MSK. 

Either way, I'll close this for now. If anyone disagrees, they can re-open.

**Pull request closed without merging**
