### PR TITLE
Networking fix: resolves #363

### LINKED ISSUE #363: Internet connection check fails when tls is blocked by network
Just as the title says. I am behind a weird firewall on a university network. Every command fails with the response "This device is not connected to the internet"  This is an issue with the connection check. When I edit "client/speech/listener.py", and just remove the check, Mycroft, can process voice commands just fine. I'm not sure if there is a better way to check network connections, but if there is, let me know, and I would be happy to implement it.

### PR DESCRIPTION
**Pull request by clccmh**
This may be a better solution for reporting network connectivity problems. With this implementation, the request for speech recognition is always made, without checking for connection before starting the thread.

This closes #363

### CODE REVIEW

**Comment by aatchison** [comment]
Thanks!
It looks like you have a few pep8 errors going on. You can run pep8 locally if you like as well.
`workon mycroft`
`pep8 $path` or `pep8 $file`

https://travis-ci.org/MycroftAI/mycroft-core/builds/161974776

**Comment by aatchison** [comment]
We have made a major update to master and plan on getting to this, thanks!

**Comment by aatchison** [comment]
Is this still an issue? If you would like to re base off of master and make another PR into the dev branch, that's how we plan to do this from now on. We will update the Contributing.md here soon as well. Thanks!

**Comment by aatchison** [comment]
Let's rebase and PR against the dev branch if you are still having this issue. We will try to get it reviewed and addressed, sorry.

**Comment by kfezer** [comment]
I'm going to re-write this PR once we get the newest release out.

**Comment by kfezer** [comment]
Sorry it took us so long to get to this. 

I'm going to close this PR and replicate it for the next build. A lot of the original code has changed and instead of resolving conflicts it will be easier to write in your changes on top of the newest version. I'll do that after this release. I'll make sure to tag you in the new PR.

**Pull request closed without merging**
