### PR TITLE
set active lang to configured if missing from STT and normalize

### PR DESCRIPTION
**Pull request by forslund**
## Description
I ran across this when checking some questions I had surrounding [mycroft-timer PR #77](https://github.com/MycroftAI/mycroft-timer/pull/77)

If the STT doesn't send a lang code fallback to configured language instead of hardcoded en-us. This should at least be more correct than the previous behaviour.

## How to test
Check that Mycroft operates as usual and that the new unittest passes

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2650))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2650))

**Comment by krisgesling** [comment]
Nice!

Is there going to be a benefit in re-using this elsewhere? ie should this be an imported util?


In terms of testing, is it worth us adding a test for a globally configured lang code?
Something like:
```
    def test_config_lang(self):
        msg = Message('test msg', data={})
        config = {'lang': 'it-it'}
        Configuration.patch(Message('patch', data={'config': config}))
        self.assertEqual(_get_message_lang(msg), 'it-it')
        Configuration.patch_clear(msg)
```

Sidenote - It seems like `patch_clear` doesn't really need any arguments, the Message arg looks like it's just been copy-pasted from the `patch` method. Will do a PR to propose removing that.

**Comment by krisgesling** [comment]
disregard the `patch_clear` sidenote, just saw that it's got a messagebus handler so the Message arg makes total sense.

**Comment by forslund** [comment]
I've added an explicit testcase for the case when the config doesn't contain a language code and changed it so the configured language code in the test is 'it-it' which should indeed be better than using the 'en-us' one which would be invisible.

I don't _think_ it's of much use outside of the intentservice, the function could technically be placed in `mycroft.util.lang`, but since this is marked as "private" with the underscore, placing it here for now should be fine. If another use is found it can be added there and this can be removed.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2650))

**Pull request merged**
