### PR TITLE
custom skills #161

### LINKED ISSUE #161: custom skills
Currently there is no architecture to create a 3rd party skill

- User dir `~/.mycroft/third_party_skills`
- `mycroft/third_party_skills`

### PR DESCRIPTION
**Pull request by the7erm**
Fixes #161

### CODE REVIEW

**Comment by aatchison** [comment]
It looks like You have just one pep 8 failure :)
`mycroft/skills/core.py:40:80: E501 line too long (80 > 79 characters)`

**Comment by ethanaward** [comment]
This looks potentially very useful, have you tested it to see if it works with a sample third-party skill?

**Comment by the7erm** [comment]
@ethanaward Yes I have.  I put a skill in `~/.mycroft/third_party_skills` and it worked.  `mycroft/third_party_skills` should also work.

**Comment by the7erm** [comment]
@aatchison I fixed the pep8 issue.  What's messed up is I have a line in my text editor that shows me when I hit the limit, but I guess I wasn't paying attention.

**Comment by ethanaward** [comment]
@the7erm You can also `pip install pep8` and run `pep8 mycroft test` to check that your code is passing what the Travis build is doing.

**Comment by aatchison** [comment]
Thanks, looks good. let me quickly review.

**Comment by aatchison** [comment]
lgtm

**Comment by the7erm** [comment]
@aatchison I'm going to venture to guess it wasn't up to mycroft standards since you reverted it.

**Comment by aatchison** [comment]
I thought it would be I'm my revert PR. Basically, the external skills location needs to be outside of the codebase location. When we ship these as debs (as we do on the unit,) directories get created. If you put your own files in and then update, apt will complain that those paths were modified. Maybe we can point it to inside a user's home folder?

**Comment by clusterfudge** [comment]
Sorry, I got to this post-facto and asked for the revert. What @aatchison said is correct; like most of our configuration, I'd like to see a sane default in defaults.ini (maybe ~/.mycroft/third_party_skills). It should also be configurable, so that we (or other developers) can decide where to place 3p skills. I imagine on installed devices we'll probably put it in /opt/mycroft/third_party or something like that.

thanks!

**Pull request merged**
