### PR TITLE
[Debian] Replace Python 2 packages by their Python 3 counterparts and remove doubled "automake"

### PR DESCRIPTION
**Pull request by MichaIng**
## Description
The aim is simply to skip installing Python 2 on Debian where only Python 3 is required. (Removal of the doubled `automake` package from dependency list is trivial. 😉)
+ python3-setuptools: https://packages.debian.org/stretch/python3-setuptools
+ python3-gi: https://packages.debian.org/stretch/python3-gi

The second one is not the -dev package. There is non available for Python 3 only, instead for both: https://packages.debian.org/stretch/python-gi-dev
However I tested with the above two on x86 and didn't notice any compilation (including Mimic) or related run error with Mycroft. However clearly needs additional testing on e.g. ARM devices in case, or knowledge of the devs who know where/how the GObject libs/headers are actually used.

So take this PR for now as an idea to think about skipping the install of Python 2 on Debian.

## How to test
Install on Debian on different CPU architectures, where compilation might have different needs compared to x86.

## Contributor license agreement signed?
- [x] CLA (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @MichaIng, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Thanks for this, will merge as soon as the CLA gets in.

I don't think python3-gi is actually needed for core either and we should be able to remove that requirement all together.

**Comment by MichaIng** [comment]
@forslund 
> Thanks for this, will merge as soon as the CLA gets in.

I filled the form already but didn't receive a confirmation email yet. This takes a while?

> I don't think python3-gi is actually needed for core either and we should be able to remove that requirement all together.

Would be even better. Shall I remove it completely (on all distros) with this PR? Even as is, the PR should be tested on other architectures before merging, so then dependency on GObject could be tested all together.

**Comment by forslund** [comment]
There's some amount of manual labor involved in getting the CLA mails sent out so you should have the mail soon-ish. If it doesn't arrive in a day or two, check spam then yell at me and I'll look into it.

Just change it for debian/ubuntu and then we can create help-wanted issues for the other OS'es so it can be tested properly. (I currently only run Debian derivatives)

**Comment by MichaIng** [comment]
@forslund 
Makes sense, same here with Debian-only distros running.

**Comment by MichaIng** [comment]
Resolved conflict with new info print when pre-reqs are installed.

**Comment by forslund** [comment]
CLA has arrived. Going to spin up a new Ubuntu VM and try this fresh! Thanks for contributing!

**Comment by forslund** [comment]
Tested and looks good! Merging!

**Pull request merged**
