### PR TITLE
Remove mplayer audioservice

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
`py_mplayer` is no longer maintained, and will not be adopted.

If a suitable alternative is found in the future, an audioservice plugin should be created.

## How to test
No functional change - automated tests should pass.

## Contributor license agreement signed?
- [x] CLA

### CODE REVIEW

**Comment by krisgesling** [comment]
This also gets flagged by plenty of users that see the error of it failing to load and assume it must be a real issue eg #3074

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-3078))

**Review by forslund — APPROVED** [review]

**Comment by JarbasAl** [comment]
small clarification, py_mplayer is not up for adoption, if you found a bug open an issue and i will look into it

I haven't used it for a long while but last i checked it was functional and a viable alternative to vlc

**Comment by goldyfruit** [comment]
Change has been reflected within the Docker images.
https://github.com/smartgic/docker-mycroft/commit/3808a36001d2ba4cfa90473e8c11c7af60a1086c

**Comment by krisgesling** [comment]
Sorry Jarbas, it's been a while since we talked about it. Thanks for the clarification.

**Pull request merged**
