### PR TITLE
Add flag "--skip" 

### PR DESCRIPTION
**Pull request by kleo**
## Description
Flag `--skip` for skipping interactive prompt. I added this flag neccessary for building [Picroft](https://github.com/kleo/picroft) image on Github Actions.

## How to test
Run `dev_setup.sh --skip`

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @kleo, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
I think this is a good addition since I usually don't want the interactive one when setting up locally so it's really useful to have. However I think this should be combined with the existing `CI` environment variable (intended for use with things like github actions / jenkins) to skip the interactive parts.

Maybe initialize `opt_skip` based on if the `CI` environment variable is set and remove the `-z $CI` in the if statements where `$opt_skip` is used?

Also note that setting the `CI` environment variable should disable the tput colors so they shouldn't need to be removed.

**Comment by kleo** [comment]
Thanks for teaching me the CI environment variable @forslund. I've been using that [here](https://github.com/kleo/picroft/blob/main/.github/workflows/build-transfer-stable.yml#L60) and I haven't had problems so far.

**Comment by forslund** [comment]
@kleo, do you think this PR should be closed or are you interested in continuing the work?

**Comment by kleo** [comment]
> @kleo, do you think this PR should be closed or are you interested in continuing the work?

No @forslund. Thanks! Closing

**Pull request closed without merging**
