### PR TITLE
Add send_email method to skills

### PR DESCRIPTION
**Pull request by MatthewScholefield**
Update: It now works for me.
### Usage
```Python
self.send_email('Title', '<b>content</b><br>here')
```

### Example Skill
**\_\_init__.py**
```Python
from mycroft import MycroftSkill, intent_file_handler


class EmailSkill(MycroftSkill):
    def __init__(self):
        MycroftSkill.__init__(self)

    @intent_file_handler('send.email.intent')
    def handle_send_email(self, message):
        self.send_email('Your email', message.data.get('content', '...'))
        self.speak_dialog('sent.email')


def create_skill():
    return EmailSkill()
```

**send.email.intent**
```
send an email saying {content}.
send the email {content}.
```

sent.email.dialog**
```
I've sent the email.
The email has been sent.
```

### CODE REVIEW

**Comment by forslund** [comment]
I've tested it and the call to the backend returns a 200 status but so far I've not received any e-mail.

Two things:
- Test case (at least for the api)
- Docstrings

**Comment by MatthewScholefield** [comment]
@forslund I've added docstrings, and it should be fixed now. Also, how should we do a test case without actually sending an email?

**Comment by forslund** [comment]
In this case the tests would be pretty easy. Mock out the `Api.request()` method and verify that it's called and the expected parameter is passed in the correct format. This would be mainly for protection against sloppy coders like me in the future :)

Looking at the possibilities here, you could do that for a mocked "valid" `IdentityManager.uuid` and an uninstantiated (which would be a `DeviceIdentity().uuid`)

**Comment by MatthewScholefield** [comment]
@forslund I've added a unit test for the `send_email` part of `DeviceApi`, similar to `STT`.

**Pull request merged**
