### PR TITLE
Added a new feature to... nevermind

### PR DESCRIPTION
**Pull request by penrods**
The utterance processing now looks at the tail end of the transcribed phrase, ignoring the utterance if it ends with "nevermind" or "cancel" or "ignore that".  This is for use case like:
   Hey Mycroft, can you tell me the...ummm...oh, nevermind

I have some concerns about a few corner cases that a skill might want to use.
For example:
 * Hey Mycroft, play Nirvana's Nevermind
 * Hey Mycroft, I want that last request to cancel
But I think this is something that can normally be designed around easily.

====  Tech Notes ====
Added mycroft.dialog.get_all(phrase, lang, context).  This lets you load all of the rendered versions, not just a single randomly selected one.

This class has the experiment of returning a value when a matching .dialog file isn't found.  Instead it returns ['phrase'], replacing the . with spaces.  So if I add:
    mycroft.dialog.get_all("thank.you") and there is no resource file found named 'thank.you.dialog', it will still return successfully:  ['thank you']

==== Localization Notes ====
This adds the new "nevermind" core resource string.

### CODE REVIEW

**Comment by JarbasAl** [comment]
maybe having a convention for always ending with "that", it sounds natural and should reduce collisions. the examples you gave would work

i think cancel and nevermind are too generic, "cancel that", "nevermind that", "ignore that" and maybe also "X that order" or "X this order"

these sound natural, until we get a more robust approach it would be better to "train the user" to interact in a certain way than mysteriously failing here and there.

**Comment by penrods** [comment]
Can you provide some good collision examples?  Remember that this only matches the very end of the transcription, so you can say "Hey Mycroft, cancel my appointment with Jimbo" without any issue.  I am stuck coming up with real-world phrases that people might attempt to use that this would prevent.  It feels like "cancel" might cause conflicts, but I can't come up with realistic phrases that might end in 'nevermind'.  If you can give me some potential phrases, I could be swayed.

I agree that this is a "train the user" solution for now.

**Comment by JarbasAI** [comment]
@penrods 

What is another word for nevermind?
What is the opposite of nevermind?
What is the meaning of the word nevermind?
How do you pronounce the word nevermind?

i would train the user to always end with X "that" "this" or "that order"

**Comment by JarbasAI** [comment]
what if you checked for neverminds after determining intent but before message broadcast and allow individual intents to disable this setting?

**Comment by penrods** [comment]
I think this one is of limited utility, so closing for now.

**Pull request closed without merging**
