### PR TITLE
Added comments to document race condition

### PR DESCRIPTION
**Pull request by chrisveilleux**
## Description
[PR2937](https://github.com/MycroftAI/mycroft-core/pull/2937) addressed an issue with a race condition but no comments were added to describe the problem and the work around to address it.  This PR adds those comments.

## How to test
No testing necessary.  Only comments touched.

## Contributor license agreement signed?
CLA [Y]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2945))

**Review by forslund — APPROVED** [review]
Nice, maybe we should open an issue as well?

**Comment by chrisveilleux** [comment]
> Nice, maybe we should open an issue as well?

There is an issue in the internal ticketing system for this.  I am not sure if we have a clear delineation for what goes into GitHub issues vs. Mycroft's internal issue tracker.

**Comment by krisgesling** [comment]
Until we can setup a syncing system between them, I think we should ideally have a public issue for anything that is of interest to the broader community. This would be particularly useful if downstream projects might have a vested interested in fixing it and contributing that fix back.

I've tried to do this a bit with internal tickets and include a link to the public issue, but it is a pain trying to maintain two listings.

**Pull request merged**
