### PR TITLE
Inform user about skill installation at first start

### PR DESCRIPTION
**Pull request by forslund**
I haven't had time to test this thoroughly, seems to be ok from the 5 tests I've run but should be tested further before merge.

If no skills are present don't immediately try to start pairing, instead inform user that the skills will be installed and launch pairing after that.

### CODE REVIEW

**Comment by forslund** [comment]
I realized just now that it should be limited to speak only once and not on subsequent retries. Will update...

**Comment by penrods** [comment]
I want to build on this to provide clean feedback points (booting, looking for wifi, connected, paired, initial download / updating skills, all skills loaded, etc), along with appropriate feedback in the user interface.  E.g. changing the eye spin and/or colors.

**Comment by penrods** [comment]
I think the feedback in #1308 takes care of this issue.  Can we close this one out unmerged?

**Comment by forslund** [comment]
Yes!

**Pull request closed without merging**
