### PR TITLE
Remove all references to /opt/mycroft/skills

### PR DESCRIPTION
**Pull request by MatthewScholefield**
## Description
This get's rid of references to `/opt/mycroft/skills` so that it can properly be configured. The only thing that should reference it is the config. This fixes #1354 and closes #1255.

## How to test
 - Pull branch
 - Make sure skills load properly

### CODE REVIEW

**Comment by forslund** [comment]
Hmm wouldn't it be better in the long run to remove all references to `/opt/mycroft` (so cached websettings and the event-save file also are included in this.

Having the skills directory be `join(mycroft_dir, 'skills')`

**Comment by forslund** [comment]
@MatthewScholefield seems like recent changes has created some conflicts, do you mind rebasing this?

**Comment by MatthewScholefield** [comment]
@forslund Just rebased.

**Comment by MatthewScholefield** [comment]
@forslund Any idea why these tests are failing? They are working on my end

**Comment by forslund** [comment]
Found an issue with the configuration test, had probably been there a while but the ordering of the tests masked it. I did a quick fix and rebased this branch so now it's passing again.

**Comment by MatthewScholefield** [comment]
@forslund I've routed all references of `data_dir` through `expanduser`. As for `prepare-msm`, I'm not sure the best thing for that since it is a bash script run on startup that needs to access all configurations (since it would likely be overridden user level). The best solution I could think of is making it perform the same actions in a startup python script, but it'd have to load all of the configuration manager which I'm not sure if it would be too long to put at startup. I think for now it's reasonable to reference the two so that to change your data_dir you need to also change `prepare-msm`.

**Comment by forslund** [comment]
You're right. That sounds like a good solution for now.

**Comment by forslund** [comment]
Looks good, Merging

**Pull request merged**
