### PR TITLE
CI: Use the docker -f flag instead of copying the Dockerfile

### PR DESCRIPTION
**Pull request by forslund**
## Description
Replace the Dockerfile copy step with building the Docker container with -f test/Dockerfile

## How to test
Check that the VK test passes.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2541))

**Comment by forslund** [comment]
Dockerfile has been renamed as requested

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2541))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2541))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2541))

**Comment by forslund** [comment]
@chrisveilleux I rebased this resolving the conflict. Anything else you'd like to change?

**Comment by krisgesling** [comment]
LGTM - @chrisveilleux I'll merge it on Monday unless there's anything else that needs addressing

**Pull request merged**
