### PR TITLE
Noticed that FAQ/Common Errors section of README.md said that mycroft.…

### PR DESCRIPTION
**Pull request by jasonehines**
…sh would start the cli, so I added it.

### CODE REVIEW

**Comment by ethanaward** [comment]
My intention there was to say that you should run ./start.sh service, ./start.sh skills, and either ./start.sh voice __or__ ./start.sh cli. Running both at the same time will have unintended side effects. Making an option in mycroft.sh for running either `service, skills, and voice` or `service, skills and cli` would be useful though, for those who want to test using cli rather than voice.

**Comment by jasonehines** [comment]
@ethanaward are their other unintended side effects besides Mycroft saying everything twice?

**Comment by ethanaward** [comment]
@jasonehines That's the main one afaik.

**Comment by jasonehines** [comment]
@ethanaward okay. I added the quite option and it seems to work as expected.

**Comment by jasonehines** [comment]
I like having the cli --quiet and the voice running at the same time; unless it's going to cause some other issue. That way I have the option to type/paste something in the cli or just talk to Mycroft.

Please give me some feedback on which way to go with this.

**Comment by ethanaward** [comment]
@jasonehines I think your method of doing it should be fine as long as cli is in quiet mode. The only other suggestion I would have would be to make another mode that doesn't run cli in case people don't want to run both.

**Comment by jasonehines** [comment]
Unless I missed a bug or you want to change something, this should be ready.

**Comment by ethanaward** [comment]
LGTM, merged.

**Pull request merged**
