### PR TITLE
make message parameter on intent handler optional

### PR DESCRIPTION
**Pull request by azie-ginanjar**
- import getargspec on mycroft/skills/core.py
- add conditional on wrapper function(under add_event function) based on number of parameter of handler

### CODE REVIEW

**Comment by penrods** [comment]
Hello, @azie-ginanjar. Thank you for helping with the Mycroft project! We welcome everyone into the community and greatly appreciate your help as we work to build an AI for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any code contribution. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by azie-ginanjar** [comment]
Hello @penrods, I have requested the CLA. Thank you

**Comment by forslund** [comment]
This looks good. The back-end is down so my tests are a bit limited. I'll finish testing as soon as the servers starts behaving.

**Comment by forslund** [comment]
Ok, more tests today and everything works beautifully many thanks for implementing this. Merging

**Pull request merged**
