### PR TITLE
Minor improvements to the msm tool

### PR DESCRIPTION
**Pull request by theCalcaholic**
This pull requests adds two improvements to the msm command line tool.

1) `msm list` will now show which skills are already installed (issue #1202)

2) A new `msm info <skill>` command has been added, with <skill> either being a distinct substring of a skill's name or the skill's github repository's url. It will display the readme.md from the repository in the terminal (if found). (issue #1203)

### CODE REVIEW

**Comment by theCalcaholic** [comment]
Sorry for not referencing the issues in the commit messages. Next time I'll read the contribution guidelines _before_ making the PR.

**Comment by forslund** [comment]
Thank you, this sounds like very useful features. I'll give it a go in a bit.

In the meantime I'd like you to sign the contributors licensing agreement (https://mycroft.ai/cla/), this is needed to make sure everything is Ok on the licensing side and you are aware what rights you're granting us.

**Comment by theCalcaholic** [comment]
Thanks for the information. I signed the agreement.

**Comment by Mn0491** [comment]
This works really nicely. Tested and works for me. @forslund let me know if you have any concerns with this. otherwise it looks good to me. thanks @theCalcaholic!

**Comment by forslund** [comment]
I tested it earlier and it works really well. Merging. Big thanks @theCalcaholic!

**Comment by theCalcaholic** [comment]
I'm glad that it works.

I think I should point out a short coming off the `msm info` command. It gets the information from the latest version's Readme instead of the version which is included in https://github.com/MycroftAI/mycroft-skills because I have no idea how to get the exact submodule version information without cloning the parent repository.

**Comment by forslund** [comment]
I think we still pull the head version so that's quite accurate. I'll make a note to check it over when we start to use the version the submodule is pointing to

**Comment by theCalcaholic** [comment]
@forslund Oh, perfect. Thanks!

**Pull request merged**
