### PR TITLE
Speak sayto bash pipes

### PR DESCRIPTION
**Pull request by FruityWelsh**
## Description
Feature: Allow mycroft-speak and mycroft-say-to take bash pipes #2105

## How to test
with mycroft instance running
run cmd: mycroft-speak test
confirm mycroft speaks
run cmd: echo test | mycroft-speak
confirm mycroft speaks

run cmd: mycroft-say-to "hey mycroft"
confirm mycroft acknowledges
run cmd: echo "hey mycroft" | mycroft-speak
confirm mycroft acknowledges

## Contributor license agreement signed?
CLA [YES]

This is the corrected version of :https://github.com/MycroftAI/mycroft-core/pull/2108

### CODE REVIEW

**Comment by forslund** [comment]
Thanks, this seems to work great, will merge when your CLA arrives.

One of the features of the scripts to automatically join all arguments into a single utterance seem to be broken. If you like you're welcome to tackle the joining of arguments as well otherwise I'll do it when this is merged.

Something like

```bash
data=$(echo "{\"utterance\": \"$@\"}")
output=$(python -m mycroft.messagebus.send "speak"  "${data}")
```

should work.

**Comment by penrods** [comment]
@FruityWelsh, here is the blurb and connection to the CLA system again...

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by FruityWelsh** [comment]
I have entered my info into the web page, and selected "request agreement". It takes me to next page, and that's it. Is there anything else I need to do?

**Comment by penrods** [comment]
Ahh... I think I know what is going on.  It looks like a Wordpress change has exposed a "honeypot" field which is used to stop bots from spamming us.  It also hosed the look of the form in general -- sorry about that.

For now, please revisit https://mycroft.ai/cla and enter data in the three top fields for Name First / Last and Email, then check the Individual and/or Thru Employeer box as appropriate. 

But if you see another field above the Request Agreement button DO NOT PUT ANYTHING IN IT.  The label above the field changes between things like Name, Website, Phone, Email, etc.  This is normally hidden to humans but visible to bots, so they fill in this honeypot and we can ignore them.

Sorry about the confusion!

**Comment by forslund** [comment]
@FruityWelsh did you retry to request to sign the CLA? I believe the incorrectly exposed field has been removed now.

If you've received the email and signed already let me know and I'll make sure we check if it's lost on our end.

**Comment by forslund** [comment]
Hi, just checking in. Any luck with the CLA?

**Comment by FruityWelsh** [comment]
No luck so far.
Screenshot_2019-05-09 Contributor License Agreement - Mycroft(1)
Screenshot_2019-05-09 Contributor License Agreement - Mycroft

These were the pages before and after filling out and selecting "Request Agreement"

**Comment by FruityWelsh** [comment]
Found a bug after further testing (using: echo "hello world" | mycroft-speak) in which everything after the first bug was ignored. Fixed by changing it to: set -- "${1:-$(</dev/stdin)}" "${@:2}"

**Comment by FruityWelsh** [comment]
I didn't have any luck with:
data=$(echo "{\"utterance\": \"$@\"}")
but have no idea why, that looks like it should work to me

Joining them in for loop works if you would want me to commit this change too I can.
for utter in "$@";do
    data+=" ${utter}"
done

**Comment by FruityWelsh** [comment]
Separate note, with the current setup the test cat testfile | mycroft-speak or echo "`cat testfile`" | mycroft-speak does not work. I am stumped as to why currently.

**Comment by forslund** [comment]
Might be the old "shellscripts are weird" reason :)

feel free to append the all arguments fix to this PR. I'll test the cat thing and see if I can see anything...

**Comment by forslund** [comment]
Btw I've started a test of the CLA requester to see if it's broken somehow.

**Comment by forslund** [comment]
Send an email directly to steveDOTpenrodATmycroftDOTai asking to get a CLA, include info if you're an individual contributor or working through an employer.

**Comment by forslund** [comment]
This is working really nicely for me now. Big thanks for providing this feature and fix!

Merging

**Comment by FruityWelsh** [comment]
Good to hear!

**Pull request merged**
