### PR TITLE
scripts: Support busybox chown

### PR DESCRIPTION
**Pull request by rzr**
Those extra options are not enabled in busybox
(at least not the configured version in poky yocto distribution)

This will also help to support systems without coreutils,

Relate-to: https://github.com/MycroftAI/mycroft-core/pull/2686
Signed-off-by: Philippe Coval <philippe.coval@astrolabe.coop>

## Description
(Description of what the PR does, such as fixes # {issue number})

## How to test
(Description of how to validate or test this PR)

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @rzr, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2966)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2966/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2966/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2966/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2966/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2966/logs/enclosure.log)

**Comment by krisgesling** [comment]
Hi @rzr - thanks for signing the CLA - you've been added to our [list of excellent humans](https://github.com/mycroftAI/contributors)

If I don't hear any objections I can't see any reason to keep these flags if they're blocking support for a system.

For reference they are:
```
       -f, --silent, --quiet
              suppress most error messages

       -v, --verbose
              output a diagnostic for every file processed
```

**Comment by forslund** [comment]
The v and f seems quite redundant...verbose and quiet...

The default (without -v) is quiet and will only report errors so I too think this is a good change

**Review by forslund — APPROVED** [review]

**Pull request merged**
