### PR TITLE
This implements CLI enhancements per issue #547

### PR DESCRIPTION
**Pull request by penrods**
Main CLI enhancements:
* Microphone meter
* Long log line left/right scrolling
* Eliminated flicker
* VT100 ESC key code support (used by some terms)

In addition, to achieve the meter it was necessary to implement a mechanism for local Inter Process Communication (IPC).  This is achieved using the file-system.  By default a folder structure is created under /tmp/mycroft/ipc, but it can be directed to somewhere else by setting the config value in mycroft.conf:
    "ipc_path" : "/path/to/somewhere"
In the future, Mark 1 and Picroft will get RAM disks to avoid burning out the SD card.  This is also a very fast communication mechanism.  This is all hidden under util.get_ipc_directory()

Further, the named signal mechanism was changed to use the IPC folder.  The signal can have a lifetime now (not just one shot).

### CODE REVIEW

**Comment by aatchison** [comment]
With the default config file, just running this branch in dev setup:

`./start.sh skills
Starting skills
2017-03-10 11:13:04,115 - mycroft.configuration - DEBUG - Configuration '/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/configuration/mycroft.conf' loaded
2017-03-10 11:13:04,115 - mycroft.configuration - DEBUG - Configuration '/etc/mycroft/mycroft.conf' loaded
2017-03-10 11:13:04,115 - mycroft.configuration - DEBUG - Configuration '/home/aatchison/.mycroft/mycroft.conf' not found
2017-03-10 11:13:04,285 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-03-10 11:13:04,536 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/23599501-df03-419c-b4f9-895a1e14057e/setting HTTP/1.1" 200 2894
2017-03-10 11:13:04,539 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
2017-03-10 11:13:04,765 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/23599501-df03-419c-b4f9-895a1e14057e/location HTTP/1.1" 200 885
Traceback (most recent call last):
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/skills/main.py", line 29, in <module>
    from mycroft.skills.core import load_skills, THIRD_PARTY_SKILLS_DIR, \
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/skills/core.py", line 28, in <module>
    from mycroft.client.enclosure.api import EnclosureAPI
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/enclosure/__init__.py", line 35, in <module>
    from mycroft.util.audio_test import record
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/util/audio_test.py", line 20, in <module>
    from mycroft.client.speech.mic import MutableMicrophone
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/mic.py", line 33, in <module>
    from mycroft.util.log import getLogger, get_ipc_directory
ImportError: cannot import name get_ipc_directory`

**Comment by aatchison** [comment]
I added the configuration option manually. This did not help.
I moved the get_ipc_directory class to log.py from util/__init__.py , now the import is found.

**Comment by aatchison** [comment]
Now I get this error in the speech client:
`
Traceback (most recent call last):
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/main.py", line 170, in <module>
    main()
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/main.py", line 142, in main
    loop = RecognizerLoop()
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/listener.py", line 187, in __init__
    self.remote_recognizer = ResponsiveRecognizer(self.mycroft_recognizer)
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/mic.py", line 151, in __init__
    self.mic_level_file = os.path.join(get_ipc_directory(), "mic_level")
NameError: global name 'os' is not defined
`

**Comment by aatchison** [comment]
I added `import os` to mic.py, and I get this:
`
Traceback (most recent call last):
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/main.py", line 170, in <module>
    main()
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/main.py", line 142, in main
    loop = RecognizerLoop()
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/listener.py", line 187, in __init__
    self.remote_recognizer = ResponsiveRecognizer(self.mycroft_recognizer)
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/client/speech/mic.py", line 152, in __init__
    self.mic_level_file = os.path.join(get_ipc_directory(), "mic_level")
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/util/log.py", line 52, in get_ipc_directory
    dir = mycroft.configuration.ConfigurationManager.get().get("ipc_path")
NameError: global name 'mycroft' is not defined
`

**Comment by penrods** [comment]
I probably need a find a better workflow to prevent these from happening.  I often am developing on a Pi with an apt install, then copy/pasting for checkin.

**Comment by augustnmonteiro** [comment]
LGTM

**Pull request merged**
