### PR TITLE
Fixed typo "Devloper" to "Developer"

### PR DESCRIPTION
**Pull request by tycrek**
## Description
Fixed typo in dev_setup.sh

## How to test
Run the script with this update

## Contributor license agreement signed?
Yes

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @tycrek, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Hi @tycrek, just checking in to see if the CLA process has gone well or if you have any questions.

**Comment by forslund** [comment]
Hi @tycrek, just checking in again to see if there's been any hitch with the CLA process?

**Comment by tycrek** [comment]
I recieved an email for it but my Internet got screwed up during the process so it didn't appear to complete properly. I also no longer have the original email, not sure if it can be resent? 

I'm new to CLA's but it looks promising! 
Mar. 15, 2020, 2:58 p.m. by notifications@github.com:

**Comment by forslund** [comment]
You should be able to request a new CLA e-mail from https://mycroft.ai/cla

**Comment by krisgesling** [comment]
Hey @tycrek I just triggered a reminder email but hit me up if it doesn't show or you run into any trouble.

**Comment by tycrek** [comment]
@forslund @krisgesling Just signed the CLA and received a confirmation email.

**Comment by krisgesling** [comment]
Received, thanks @tycrek :)

**Pull request merged**
