### PR TITLE
Enable/Disable speak

### PR DESCRIPTION
**Pull request by JarbasAI**
sometimes it is useful to have mycroft do everything except speak, for example if you want it to play music while using the cli without getting interrupted by speech

we mustn't assume the user will always start things in quiet mode and it is good to be able to control this trough intents

a generic mute skill will give user control to disable speech

other use-cases can send a bus message to control this

issue#https://github.com/MycroftAI/mycroft-core/issues/361

### CODE REVIEW

**Comment by augustnmonteiro** [comment]
Please fix conflicts and rebase : D

**Comment by ethanaward** [comment]
This seems good, although we don't have skills in the core anymore. Could you remove the skill and rebase?

**Comment by augustnmonteiro** [comment]
@JarbasAI can you rebase this?, thank you

**Comment by JarbasAI** [comment]
rebased and updated this

**Comment by AIIX** [comment]
+1 vote for this feature another use case: office working environments or public places where one would like to use mycroft using text instead of speech on enclosures that support text

**Comment by JarbasAI** [comment]
we now can not execute TTS with #1408 , but i would still like this feature as a global switch

i like telling mycroft to mute and to start playing music, then i can still trigger skills because i always have a ssh terminal open to my mark1, i can still type in questions without having the speech

if this is desired i will rebase again

**Pull request closed without merging**
