### PR TITLE
Utilize the mycroft-messagebus-client module

### PR DESCRIPTION
**Pull request by forslund**
## Description
Thanks to @NEONdaniel the mycroft-messagebus-client is (almost) back in sync with core. Discussions in chat suggested that there might be a good idea to switch to using the common module. It was proposed back in #2431, but perhaps the world is ready for this abstraction now :)

Currently still in WIP due to a pending PR, VK fails due to the git+ urls aren't parsed in setup.py without jumping through some hoops. But can be tested locally using the dev_setup.sh script.

The pros are
- the client and core won't get out of sync
- less code in core

The cons:
- one more dependency

## How to test
Make sure mycroft runs as expected

## Contributor license agreement signed?
CLA [ yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2863)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2863/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2863/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2863/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2863/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2863/logs/enclosure.log)

**Comment by NeonDaniel** [comment]
I definitely support more modular code. I see this as a big benefit for plugins, etc. to be able to utilize the exact same messagebus package as core.

FWIW, I'm testing similar changes as these against the NeonAI fork of mycroft-core without issue.

**Comment by forslund** [comment]
The requirements.txt has been updated with the released package.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2863)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2863/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2863/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2863/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2863/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2863/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2863))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2863))

**Comment by NeonDaniel** [comment]
Anything holding up this PR? The event-based waiting alone was a notable speed up to skill responses in my testing.

**Comment by krisgesling** [comment]
Nope this all looks good. 

I didn't expect such a noticeable speed improvement but the VK tests are a good indicator for this - they are running almost 20% quicker!

**Review by krisgesling — APPROVED** [review]

**Pull request merged**
