### PR TITLE
centos support

### LINKED ISSUE #1836: Centos 7 support
*I am trying to install Mycroft from the repo (what ever that newest version is)
*I am trying to install this on Centos 7 (which I know is not supported yet)

My basic process for understanding is listed as follows on a fresh minimal install.

1. sudo yum install epel-release
2. sudo yum update -y
3. sudo yum upgrade -y
4. sudo yum install nano wget git python-pip python-devel (This is not all of them)
5. sudo yum groupinstall 'development tools'

The main issue here is that dev_setup.sh will not work because it cannot use apt and it needs yum. However I was able to get pip to install the entire requirement.txt (with some work). I can go through the process again and correct every issue I ran into originally so we can get this working. However I am not very good with scripts so I would just need help fixing that so that it can easily be install on centos.

### PR DESCRIPTION
**Pull request by JarbasAl**
## Description
fixes #1836 

## How to test
run dev setup in centOs, or other distro that uses yum

## Contributor license agreement signed?
CLA [ yes] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by JarbasAl** [comment]
hunting down some packages... seems python3 is not available in yum

**Comment by JarbasAl** [comment]
thats not the correct package, it seems theres no equivalent according to https://repology.org/metapackage/libfann/versions

i am now compiling from source, doing final test in a fresh vm but everything seems to be working

**Comment by forslund** [comment]
Hmm, the manifest matches the debian package pretty well...

What issue do you have with it?

In any case you should probably use the fixed release  instead of HEAD, the tag releases/tag/2.2.0 or just use the tar.gz https://github.com/libfann/fann/archive/2.2.0.tar.gz

**Comment by JarbasAl** [comment]
pip simply fails to install fann if using the provided package, from source it works

**Comment by forslund** [comment]
It could be the multiarch issue with the fann pip package that's acting up again.

I still think the release tag or release tar.gz should be used

**Comment by JarbasAl** [comment]
i have no way to test this, if someone wants to test and propose changes i can add them, but until some real user gives the working changes i don't want to touch this since it is currently working (and just using the other package is confirmed not to work)

**Comment by forslund** [comment]
If you don't want to use the tag, at least fix the SHA to the current head commit.

**Comment by forslund** [comment]
Thanks @JarbasAI and @assasen11. Merging now

**Pull request merged**
