### PR TITLE
Update CommonPlaySkill and CommonQuerySkill to pass messages

### LINKED ISSUE #2875: Pass Messages to CommonSkill handlers
**Is your feature request related to a problem? Please describe.**
Similar to #2812, Messages are easier to write generic methods around so a CommonSkill match method could be easily adapted from an intent handler, more data is available, supporting methods can always expect Messages, etc.

**Describe the solution you'd like**
Like #2813 resolved #2812, I propose passing messages instead of just text. I think passing the callback data in the action methods does provide some convenience, though that is also included in the message so it would be possible to use messages alone.

**Describe alternatives you've considered**
There is currently no other means for passing extra data into `match_query_phrase`. `action` can receive extra data via the `callback_data` param, though inserting a message into the `callback_data` seems like more of a workaround than a solution.

**Additional context**
None

### PR DESCRIPTION
**Pull request by NeonDaniel**
## Description
Fixes #2875 
Similar to #2813, this updates the CPS and CQS abstract methods to expect Messages instead of Strings. Inspecting the method signatures provides backwards compatibitliy.

## How to test
This should work with all existing skills as-is. New functionality can be tested by modifying `match_query_phrase` and `action` overriding methods to match the new signature

## Contributor license agreement signed?
CLA [x ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @NeonDaniel, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2876)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2876/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2876/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2876/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2876/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2876/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2876)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2876/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2876/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2876/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2876/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2876/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2876)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2876/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2876/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2876/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2876/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2876/logs/enclosure.log)

**Comment by devs-mycroft** [comment]
Hello, @NeonDaniel, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Closing PR since we're archiving the repo

**Pull request closed without merging**
