### PR TITLE
Change git clone command in getting started to reduce clone size

### PR DESCRIPTION
**Pull request by Seenivasanseeni**
Changed git clone to git clone to git clone --depth=1 to reduce the cloning size as this is only for deployment of mycroft and not for development and  added additional instructions for developers to use the whole repo instead of single depth repo.

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
I think this makes sense, especially since it reduces the code from 152 MB to 25 MB. In addition, developers can still code just like normal with this, they just won't have code history. @forslund Any thoughts on this?

**Comment by MatthewScholefield** [comment]
I just noticed you heven't signed the CLA. Here's some info on it:

-----
  Hello @Seenivasanseeni, thank you for helping with the Mycroft project! We welcome
  everyone into the community and greatly appreciate your help as we work to
  build an AI for Everyone.
  
  To protect yourself, the project, and users of Mycroft technologies we require
  a Contributor Licensing Agreement (CLA) before accepting any code contribution.
  This agreement makes it crystal clear that along with your code you are
  offering a license to use it within the confines of this project. You retain
  ownership of the code, this is just a license.
  
  Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by forslund** [comment]
I think it's a good change! If for some reason the history is desired that can be fetched later. Let's merge after the CLA is handled!

**Comment by Seenivasanseeni** [comment]
@MatthewScholefield I singed the CLA.

**Comment by MatthewScholefield** [comment]
Awesome, thanks for this!

**Pull request merged**
