### PR TITLE
Adapt intent matches not returned to core in confidence order.

### PR DESCRIPTION
**Pull request by chrisveilleux**
## Description
The AdaptService in core assumes that the highest confidence intent match will be the first result returned from Adapt.  This is not always the case.  It is possible that Adapt should be ordering the return value instead.  But that would be a bigger change to Adapt.

## How to test
- Remove the future time Padatious intent from the date/time skill
- Ask "what time will it be in ten minutes"; current time will be returned.
- Apply the change in this PR
- Make same request as before, future time will be returned. 

## Contributor license agreement signed?
CLA [Y]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2915)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2915/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2915/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2915/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2915/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2915/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2915)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2915/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2915/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2915/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2915/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2915/logs/enclosure.log)

**Comment by ChanceNCounter** [comment]
It looks to me, having spent about 3 minutes on it and being unfamiliar with Adapt, like something similar could be done to (or wrap) the culprit generator in Adapt, less of a change than it seemed:

https://github.com/MycroftAI/adapt/blob/4a8fe8ab7def813dc4f6f881ce646b92863d4bfc/adapt/engine.py#L132-L135

**Comment by ChanceNCounter** [comment]
I should clarify, I mean switch to something like `adapt.get_highest_confidence(generator_in_question)` so as neither to disrupt Adapt, nor to handle it in Core when it's Adapt's fault 👅 my 2¢

**Review by forslund — DISMISSED** [review]
The change looks good. Love the update to the docstring.

I think it's good to have the sorting here for the moment. But @ChanceNCounter makes a good point that maybe we should in the future add it as a convenience function to adapt as suggested.

I'm not sure about the variable name "utt_best" as it's the best intent match and not an utterance really. maybe could be renamed to "best_match" or something.

However since it's only a name thing I'll leave that up to you, for me you can merge this as soon as Voight Kampff passes. :)

Once more, really great detective work figuring this out!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2915)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2915/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2915/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2915/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2915/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2915/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2915)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2915/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2915/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2915/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2915/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2915/logs/enclosure.log)

**Comment by chrisveilleux** [comment]
Oops.  made a big fat mistake and merged the `feature/mark-2` branch into this.  Closing and re-opening a new PR.

**Pull request closed without merging**
