### PR TITLE
Fix #2604 Add missing commands to help

### LINKED ISSUE #2604: Suggestion to add 'mycroft-config edit _' to the 'mycroft-start --help' menu.
Nevermind, found the problem for 'How to exit `mycroft-config edit Default` without leaving stopped job'

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
- Adds some missing commands to the `mycroft-help` list
- minor restructure for clarity. 
- change more info link to point to documentation

Fixes #2604 

Consideration should also be given to adding a `mycroft --help` option.

## How to test
Run `mycroft-help` and ensure the output and descriptions are clear.

## Contributor license agreement signed?
- [x] CLA (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2613))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2613))

**Comment by forslund** [comment]
Looks good and works as intended.

A couple of small things that is probably outside the scope here:
- The first character is not always capitalized (seemingly randomly). Might be something that can be addressed as well (but may be outside the scope of this PR).
- The venv-activate.sh is mentioned here, it is runnable like a shell script but will only print the instruction to source it.

Maybe a couple of newbie friendly issues could be created for these changes?

**Comment by krisgesling** [comment]
Good call regarding capitalization.

> * The venv-activate.sh is mentioned here, it is runnable like a shell script but will only print the instruction to source it.

I can't see a direct reference to that shell script. However the `mycroft-venv-activate` is a weird one as it's only handled through aliases. If you run `deactivate` instead of `mycroft-venv-deactivate` then the aliasing gets out of sync and you only have `mycroft-venv-deactivate` available...

I think we need to reconsider how we handle that. But outside the scope of this PR and I've left it in for now.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2613))

**Pull request merged**
