### PR TITLE
Change instance of ConfigurationManager().get to ConfigurationManager…

### PR DESCRIPTION
**Pull request by esoleyman**
Issue #847

### CODE REVIEW

**Comment by Mn0491** [comment]
LGTM! @esoleyman if you haven't can you sign the CLA. The CLA makes it crystal clear that you are giving the project and users of the project license to use your code, but that you still own your contributed code.

After that we can merge

**Comment by esoleyman** [comment]
I've put in the request to sign the CLA but as of yet no email to do so.

**Comment by penrods** [comment]
@esoleyman Can you please try again, I don't see any record of your request in the system.  Be sure to check either "Individual Contributor" or "Working through and Employeer".

**Comment by esoleyman** [comment]
I did about an hour ago. I just did again but from a different browser.

**Comment by penrods** [comment]
I'm puzzled as to why it isn't coming through normally.  Can you please just send me an email directly to steve.penrod@mycroft.ai with the email you would like used for the CLA and I'll push it through manually for you.

**Pull request merged**
