### PR TITLE
use long options and add --upgrade to arch linux pacman

### PR DESCRIPTION
**Pull request by doczkal**
## Description
Arch Linux setup might fail on circumstances where --sync reveals newer versions of packages to be installed but setup does not allow updates of these packages.

## Contributor license agreement signed?
CLA [yes]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2582))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2582))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2582))

**Comment by forslund** [comment]
This looks good as far as I can read. Many thanks for this update. Merging

**Comment by doczkal** [comment]
Please revert. The change is **not** working as expected and I have to think about this.
Unfortunately it's not possible to add --sync and --upgrade which would cover all edge cases.
It needs another solution.

**Pull request merged**
