### PR TITLE
Pulseaudio update

### PR DESCRIPTION
**Pull request by forslund**
## Description
Replaces the current approach of modifying streams on the go with an approach using pulse audio's built in support for audio ducking. This will mute or lower the volume of streams with certain media roles (music and video by default).

To trigger the ducking/corking when mycroft is listening the audioservice launches `paplay` with a dummy input.

## How to test
Load the module-role-ducking:
`pactl load-module module-role-ducking`
Enter the following into your mycroft.conf:
```json
  "Audio": {
    "pulseaudio": true
  }
```

Start up Mycroft and start the npr-news. Why playing say "Hey Mycroft", the news volume should be reduced while mycroft listens. The volume should also be lowered when Mycroft starts speaking.

## Contributor license agreement signed?
CLA [Yes]

### CODE REVIEW

**Comment by j1nx** [comment]
Ok, then I leave the rebase to you so I can just easily download the PR as patch and apply for some testing on my own.

Thx.

PS. I think this PR also makes it easier to start playing with other PulseAudio plugins right?

**Comment by forslund** [comment]
I think so. It basically names the mycroft streams consistently so pulse plugins can handle them separately.

**Comment by forslund** [comment]
@j1nx sorry for the delay. It's now rebased and tested.

**Comment by j1nx** [comment]
@forslund OK, great! Atm not able to test this out, bu should be anytime now. Will report back as soon as I have some feedback.

**Pull request closed without merging**
