### PR TITLE
Remove "stop_threshold"

### PR DESCRIPTION
**Pull request by penrods**
The setting "stop_threshold" is not used (and doesn't look like it ever was).  Removing
from mycroft.conf.

## How to test
Search for usage of "stop_threshold".  Not found in mycroft-core or any skills on a unit.

### CODE REVIEW

**Comment by penrods** [comment]
Nice catch!  Your removal from the unit-test looks good to me.

**Comment by JarbasAl** [comment]
was this some planned feature that was never implemented? what was this threshold meant for in the first place?

**Comment by KathyReid** [comment]
> was this some planned feature that was never implemented? what was this threshold meant for in the first place?

@JarbasAI not sure, before my time I'm afraid.

**Comment by penrods** [comment]
This is from WAY back, I don't think it had any specific meaning.  There were just "threshold" values for everything.

**Comment by forslund** [comment]
I rebased the additions by @KathyReid into a single commit to keep the commit history clean. Merging now.

**Pull request merged**
