### PR TITLE
some vocab/dialog was added

### PR DESCRIPTION
**Pull request by domcross**
## Description
some additional files were added to the 'en-us' folders which are not reflected in the 'de-de' folders yet.

## How to test
change language to 'de-de', reboot Mycroft, it should speak "Ich muss neu starten um die Uhr zu synchronisieren. Bin gleich wieder zurück." when syncing...

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
Danke @domcross, the changes looks good. The CLA hasn't been received on our end yet but when it does we'll merge this.

Let me know if there seem to be some issue with the CLA process and I'll try to help.

**Comment by domcross** [comment]
Hello Åke,

I have filed the CLA already some weeks ago (with my real-name Dominik Kreutz-Kösler, e-mail dkreutz@t-online.de) but got no feedback so far - should I file it again?

Best regards,
Dominik

**Comment by forslund** [comment]
Hi again,

it should be no more than a couple of days to get a response. Please retry at https://mycroft.ai/cla/ and also you might want to check your spam folder just in case.

**Comment by domcross** [comment]
Hi Åke,

I just wanted to let you know that CLA is now signed.

Best regards,
Dominik

**Pull request merged**
