### PR TITLE
Bugfix/gtts version update speech impl fix

### LINKED ISSUE #377: gtts speech backend needs a version of gtts greater than 1.0.6
The _gtts_ version [enforced in requirements.txt ](https://github.com/MycroftAI/mycroft-core/blob/f0386264a363c82078510a11ca680e64247466e3/requirements.txt)(1.0.6) is broken.

However, using the latest and functional version of _gtts_ raises a problem as it now saves an mp3 file, instead of a wave file as it previously did.

This is due to the current speech implementation [that is using play_wav](https://github.com/MycroftAI/mycroft-core/blob/f0386264a363c82078510a11ca680e64247466e3/mycroft/tts/google_tts.py#L22) to play the TTS file retrieved from the 3rd party service -- to fix this _play_wav_ should be substituted for _play_mp3_.

Here's the current state of **gtts 1.0.6**:

```
$ mkvirtualenv gtts-test

[...]

(gtts-test) $ pip install gtts==1.0.6
Collecting gtts==1.0.6
  Downloading gTTS-1.0.6.tar.gz
Collecting requests (from gtts==1.0.6)
  Using cached requests-2.11.1-py2.py3-none-any.whl
Building wheels for collected packages: gtts
  Running setup.py bdist_wheel for gtts ... done
  Stored in directory: /home/<redacted>/.cache/pip/wheels/78/fa/32/75896791efd0f0de28ded4db03f9be223659c08467eb2b50db
Successfully built gtts
Installing collected packages: requests, gtts
Successfully installed gtts-1.0.6 requests-2.11.1
(gtts-test) $ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtts
>>> tts = gtts.gTTS(text='Hello', lang='en')
>>> tts.save('hello.wav')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<redacted>/.virtualenvs/gtts-test/local/lib/python2.7/site-packages/gtts/tts.py", line 90, in save
    self.write_to_fp(f)
  File "/home/<redacted>/.virtualenvs/gtts-test/local/lib/python2.7/site-packages/gtts/tts.py", line 108, in write_to_fp
    r.raise_for_status()
  File "/home/<redacted>/.virtualenvs/gtts-test/local/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://translate.google.com/translate_tts?textlen=5&idx=0&q=Hello&tl=en&client=t&total=1&ie=UTF-8
>>>
(gtts-test) $ file hello.wav
hello.wav: empty
```

Here's a shell session showing **gtts 1.1.6** works, and outputs mp3:

```
(gtts-test) $ pip install -U gtts
Collecting gtts
Collecting gtts-token (from gtts)
Requirement already up-to-date: requests in ./.virtualenvs/gtts-test/lib/python2.7/site-packages (from gtts)
Installing collected packages: gtts-token, gtts
  Found existing installation: gTTS 1.0.6
    Uninstalling gTTS-1.0.6:
      Successfully uninstalled gTTS-1.0.6
Successfully installed gtts-1.1.6 gtts-token-1.1.1
(gtts-test) $ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gtts
>>> tts = gtts.gTTS(text='Hello', lang='en')
>>> tts.save('hello.mp3')
>>>
(gtts-test) $ file hello.mp3
hello.mp3: MPEG ADTS, layer III, v2,  32 kbps, 24 kHz, Monaural
```

### PR DESCRIPTION
**Pull request by ncouture**
Adds newer versions of dependencies in requirements.txt and modifies Google TTS implementation to address issues listed in #377.

This should close #377.

### CODE REVIEW

**Comment by jdorleans** [comment]
@ncouture thank you very much for this PR. Do you mind to create a unit test so we can validate your changes? You may consider following some of the existing unit tests we already have. Here an example:
https://github.com/MycroftAI/mycroft-core/blob/master/test/configuration/__init__.py

**Comment by ncouture** [comment]
@jdorleans AFAIK there is currently no unit test for the gTTS speech backend. 

Can we merge this fix and open a different issue for creating unit tests?

**Comment by forslund** [comment]
This works fine for me, however I don't think the version bump of `SpeechRecognition` is relevant to this fix. I'm still on 3.1.3 and have no issues.

@jdorleans, what sort of unit test do you suggest? This code is quite dependent of an internet connection and mocking the calls to gTTS will make little sense.

**Comment by forslund** [comment]
@ncouture, I've noticed a slight problem with this PR. When handling multiple sentences only the last is played correctly. This occurs for example when using the wikipedia skill: `wikipedia donald duck`

I think this is happens because `play_mp3` is non-blocking and the `handle_speech` callback splits the utterance into sentences. The issue can be fixed by replacing `play_mp3(self.filename)` with

```python
        p = play_mp3('/tmp/gtts.mp3')
        p.communicate()
```

**Comment by aatchison** [comment]
We have made a major update to master and plan on getting to this, thanks!

**Comment by aatchison** [comment]
Ok, if you are still experiencing this issue, and this is still the fix, please re base on master and PR to the dev branch. Thanks!

**Comment by forslund** [comment]
I think this has been updated and included in #454 and can be closed

**Comment by ethanaward** [comment]
This has been addressed in #454, closing

**Pull request closed without merging**
