### PR TITLE
handling tonight in date & time extraction

### PR DESCRIPTION
**Pull request by Ruthvicp**
## Description
``` 
set an alarm for 9 o'clock tonight 
```
Creates an alarm for 9 am (If current time is before 9 am)

## How to test
Added unit tests for special cases. You can try the below examples on Mark1
(Note: Try these before the current time is 9 AM)

- set an alarm for tonight at 9:30
- set an alarm at 9 for tonight
- set an alarm at 10:30 tonight
- set an alarm at 10 o'clock tonight

## Contributor license agreement signed?
CLA [ yes] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by Ruthvicp** [comment]
Original branch & commit : [here](https://github.com/MycroftAI/mycroft-core/pull/2065)
I closed it because of commits made by mistake.

**Comment by JarbasAl** [comment]
i still think the "tonight" should be removed from the remainder, this is the only case where a used word is not being removed, this breaks expected behavior

**Comment by JarbasAl** [comment]
here is a fixed version https://github.com/MycroftAI/mycroft-core/compare/bugfix/handling_tonight...JarbasAl:bugfix/handling_tonight

**Comment by Ruthvicp** [comment]
Thank you for the better approach @JarbasAl

**Pull request merged**
