### PR TITLE
feature insert italian get_gender() test

### PR DESCRIPTION
**Pull request by aleale99**
insert normalization test for italian language

### CODE REVIEW

**Comment by forslund** [comment]
Hi @aleale99 Thanks for this! before we can merge your PR's you will need to sign the CLA to make sure everything is up and up. To start the process please visit https://mycroft.ai/cla/

**Comment by penrods** [comment]
One more thing -- to simplify maintaining and merging translations we just split the singlar "parse.py" and "format.py" files into per-language files.  See:  https://github.com/MycroftAI/mycroft-core/tree/dev/mycroft/util/lang

Can you modify to follow this pattern for your PR?  Thank you!

**Comment by penrods** [comment]
While you are at it, feel free to join all of your Italian translations (#1332, #1334, #1336, #1337, #1339) into a single PR.  Seems like it would be easier to me.

**Comment by aleale99** [comment]
ok no problem 
I'm going to close the 5 PR and during the weekend I'll write the new files in the new format in a single PR

unittests file will be separate or will it remain a single file?
ciaoAle
 

    Il Martedì 9 Gennaio 2018 0:18, Steve Penrod <notifications@github.com> ha scritto:
 

 While you are at it, feel free to join all of your Italian translations (#1332, #1334, #1336, #1337, #1339) into a single PR. Seems like it would be easier to me.—

**Comment by forslund** [comment]
They haven't been split up yet, but there might be a point to do that as well. I'll make sure it's done before the weekend.

**Comment by aleale99** [comment]
necessary to rewrite

**Pull request closed without merging**
