### PR TITLE
fix extract date

### LINKED ISSUE #1650: extract_date_en is buggy
# bugs

**missing space throw exception** 

fixed by #1651 

`extract_date("5pm")`  -> no spaces fails

> line 693, in extract_datetime_en
>     words[idx + i] = ""
> IndexError: list assignment index out of range
> 

  **system clock date format skews result**

` extract_date("afternoon") `-> 12 extra hours in result (day should be 21 not 22, hour should be 19 not 15), my system clock is in 12hour format so the +12h addition causes a skew, if providing a date to the function it works
`
[datetime.datetime(2018, 6, 22, 15, 0), 'test']` 

**some singulars do not work**

fixed by #1651 

`extract_date("1 minute") `-> fails, "minutes" works, same for "second" / "seconds"

**some plurals do not work**

fixed by #1651 

`extract("2 hours") `-> fails, "hour" works

# test cases

```
       testExtract("lets meet in 5 minutes",
                    "2017-06-27 00:05:00", "lets meet")
        testExtract("lets meet in 5 seconds",
                    "2017-06-27 00:00:05", "lets meet")
        testExtract("lets meet in 1 hour",
                    "2017-06-27 01:00:00", "lets meet")
        testExtract("lets meet in 2 hours",
                    "2017-06-27 02:00:00", "lets meet")
        testExtract("lets meet in 1 minute",
                    "2017-06-27 00:01:00", "lets meet")
        testExtract("lets meet in 1 second",
                    "2017-06-27 00:00:01", "lets meet")
```

### PR DESCRIPTION
**Pull request by JarbasAl**
## Description
partially fixes #1650 

## How to test
check the unittests

## Contributor license agreement signed?
CLA [ yes] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
I'm not sure this works correctly still:

```
>>> from mycroft.util.parse import extract_datetime
>>> from datetime import datetime as dt
>>> dt.now()
datetime.datetime(2018, 6, 25, 7, 55, 10, 667063)
>>> extract_datetime("lets meet in 2 hours", dt.now())
[datetime.datetime(2018, 6, 25, 2, 0), 'lets meet']
```

Seems like it's always starts from midnight maybe?

The parsedatetime module works pretty well with the "in X minutes/hours/seconds" so maybe this can be simplified slightly using that?

**Comment by JarbasAl** [comment]
thats the missing bug from the issue i opened, im not sure it starts from midnight, i got a 12hour skew and assumed it was something to do with the system time not being in 24h format, looking at your example it does seem to start at midnight however

either way that bug was not in the scope of this PR (because i didnt diagnose it yet), i can update the PR if you want this change included here or make a new one

**Comment by forslund** [comment]
What is the scope of this PR?

**Comment by JarbasAl** [comment]
missing space throw exception - extract_date("5pm") -> no spaces fails
some singulars do not work - extract_date("1 minute") -> fails, "minutes" works, same for "second" / "seconds"
some plurals do not work - extract("2 hours")-> fails, "hour" works

these are the fixed this PR addresses, missing to fully fix #1650 is the issue you ran into

**Comment by JarbasAl** [comment]
should be fixed, can you check it? i did not add any test case for it, i can do that but need to edit all previous tests to correct the start time (test start at midnight by default, so the bug is stealthy)

also found another bug, added test case for it with a TODO

**Comment by forslund** [comment]
Thanks! Looks good now.

**Pull request merged**
