### PR TITLE
#99 added pdoc to requirements.txt

### PR DESCRIPTION
**Pull request by the7erm**

### CODE REVIEW

**Comment by aatchison** [comment]
Lgtm

**Comment by clusterfudge** [comment]
pdoc isn't a runtime requirement of mycroft (it's a build tool) and does not belong in requirements.txt

**Comment by the7erm** [comment]
I wasn't sure if the omission was accidental or intentional because of that
very reason.

I asked about it in the slack:
> the7erm 9:24 AM pdoc isn't in requirements.txt should it be?
[doc/generate_sdk_docs.py](
https://github.com/MycroftAI/mycroft-core/blob/master/doc/generate_sdk_docs.py#L2)

> ryanleesipes 9:52 AM @the7erm: yeah. pdoc would be good. Care to send a
PR?

Sorry for creating extra work for you.

**Comment by clusterfudge** [comment]
no worries, just a miscommunication. There's value in folks being able to generate the docs locally; it's currently done by our jenkins instance (which installs pdoc outside source control :\). If you have thoughts on managing these build-time dependencies, I'm open to them.

**Comment by ryanleesipes** [comment]
Sounds like that should go in the README.

**Pull request merged**
