### PR TITLE
Use mimic as default TTS, updated mycroft/configuration/default.ini

### PR DESCRIPTION
**Pull request by aatchison**
https://github.com/MycroftAI/mycroft-core/issues/29

Would this be enough?

### CODE REVIEW

**Comment by ryanleesipes** [comment]
Need to make sure Mimic is installed as part of the process.

**Comment by jdorleans** [comment]
If we ensure mimic is always been installed, then yes! :+1:

**Comment by aatchison** [comment]
I believe we fixed that with a previous PR

**Comment by aatchison** [comment]
lgtm

**Pull request merged**
