### PR TITLE
Issues-4 - Fix pep8 errors.

### LINKED ISSUE #4: Codebase is not PEP8 compliant
To better suit collaboration (and clean code) the codebase should be entirely PEP8 compliant.

`autopep8` might be the saving grace for the initial step here. A test should also be added, perhaps
as part of Travis CI. Might want to add pipe exit code checking here.

`find . -name "*.py"` | xargs pep8

This is a subtask of issue #2

### PR DESCRIPTION
**Pull request by elopio**
Fixes #4.

### CODE REVIEW

**Comment by elopio** [comment]
I'm sorry for the huge PR, but the less traumatic way to adopt a code style is to do it early. And as it will conflict with any future branches, lets get it out of the way at once.

**Comment by aatchison** [comment]
What do you think @clusterfudge ?

**Comment by clusterfudge** [comment]
Hey @elopio thanks for looking into this! It looks like our travis-ci config didn't make the move over from the legacy repo; I'm going to see that gets in here, and then ask you to rebase with that change. That will allow me to see inline whether or not there are any accidental breakages. 

Thanks for your patience!

**Comment by elopio** [comment]
I rebased and pushed. I think you didn't enable the thing in travis-ci.org.

**Comment by aatchison** [comment]
Yeah, needs to be  enabled again. @clusterfudge

**Comment by aatchison** [comment]
I realized that I have travis-ci access, so I've enabled it in the dahboard for this repo. No, how to trigger it?

**Comment by clusterfudge** [comment]
@elopio I've confirmed travis-ci integration is working [here](https://travis-ci.org/MycroftAI/mycroft-core/pull_requests), though we might have to push a new commit to this PR to trigger it.

**Comment by aatchison** [comment]
@elopio 
Would you mind trying one more time? I would touch the repo to trigger travis-ci, but I don't want to steal your thunder.

**Comment by elopio** [comment]
Github is acting funny on me. Maybe related to https://twitter.com/githubstatus/status/734768813279875072 ?
Feel free to steal my thunder if it works for you. Or I can retry once github's status is green again.

**Comment by aatchison** [comment]
They are definitely having issues

**Comment by aatchison** [comment]
I think github is back to full functionality, if you want to try to the nth time:)

**Comment by elopio** [comment]
no luck.

**Comment by aatchison** [comment]
Ok, I'm looking into it. Not sure what is going on, thanks for you patience

**Comment by elopio** [comment]
it's all github's fault, failing on all our projects too. Don't worry, maybe just give it some air :D

**Comment by aatchison** [comment]
Sounds like a plan. Really want to get this merged so people can re-base on the pep8 compliant code.

**Comment by aatchison** [comment]
Hmm, it seems like the build went through, but we are having problems with the test publishing. Looking into it.

**Comment by elopio** [comment]
Woohoo, it's running. I added to the .travis the pep8 execution, in case you want to take a look at that file in the diff.

**Comment by aatchison** [comment]
Cool! All checks passed. It seems our pypi host was being flaky.

**Pull request merged**
