### PR TITLE
issue-2760 Integrate new Azure Cognitive Services (TTS)

### PR DESCRIPTION
**Pull request by dalgwen**
## Description

#2760 Implement Azure Cognitive Services (TTS) API

## How to test
This TTS service requires a subscription to Microsoft Azure and the creation of a Speech resource (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/overview#create-the-azure-resource)
The free plan is more than capable to handle domestic usage (5 million character per month, or 0.5 million with neural tts)
You can choose your voice here in the column "voice name" (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support#text-to-speech)

New configuration (only the api_key is mandatory, if you are in westus) :
"tts": {
  "module": "azure",
  "azure": {
    "api_key": "insert_your_key_here",
    "voice": "en-US-JennyNeural",
    "region": "westus"
  }
}

## Contributor license agreement signed?
CLA [X] Yes

### CODE REVIEW

**Comment by JarbasAl** [comment]
hey, we are moving away from integration this directly in core, the new approach is plugin based

See https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/plugins

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2761))

**Comment by dalgwen** [comment]
> 
> 
> hey, we are moving away from integration this directly in core, the new approach is plugin based
> 
> See https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/plugins

Oh, OK, thanks.
So, I pushed this Azure TTS as a new plugin (https://github.com/dalgwen/mycroft-tts-plugin-azure)
Do you know if I have to declare it somewhere ? Or is it too soon, should I wait for a marketplace or something like this ?

**Comment by forslund** [comment]
You can publish it on pypi so it's an easy pip install. But we should create a list of available plugins somewhere. @krisgesling do you have any suggestions? The Mycroft documentation? or should we create a small wiki where authors can add their new plugins?

**Comment by krisgesling** [comment]
Hey, thanks for this @dalgwen!!

The intention is to incorporate this into the Marketplace, but at present I think in the [Customize > TTS documentation](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/customizations/tts-engine) is the best place. Currently you basically need to go there to get instructions on how to configure the services anyway, so it seems like the best fit.

This is all hosted in this repo if you have time to add it there:
https://github.com/MycroftAI/documentation

**Comment by krisgesling** [comment]
Closing this PR in favor of the plugin.

**Pull request closed without merging**
