### PR TITLE
Allow requests for STT from wave_file

### PR DESCRIPTION
**Pull request by JarbasAI**
Handler for STT requests for a wave audio file

Triggered by: "recognizer_loop:external_audio"
 Expected data fields:
         'wave_file' : ' path/to/file.wav'

Responds with:
          message.type: "recognizer_loop:external_audio.reply"
          message.data: "stt": transcription

### CODE REVIEW

**Comment by btotharye** [comment]
seems like there are some issues on this travis build that need to be check out @JarbasAI

**Comment by penrods** [comment]
Pep8 strikes again!  

Also, can you include a little more documention on how this would be used.  I know this isn't all on you, but I want to start documenting the messagebus protocols.  So when you add a new message we have a definition of what data is expected.  E.g.  recognizer_loop:external_audio looks like it expects a data packet with the path to a WAV file.  For now, just include the doc in the PR since there isn't a definitive repository of these protocols (other than a spreadsheet I started a few weeks ago).

**Comment by forslund** [comment]
Personally I'd prefer if this was implemented as a separate client. So that speech did speech, text did text and file (or what we might want to call it) did files.

The implementation as a stand alone client should be simple enough and frankly the speech client doesn't need any more complexity.

**Comment by JarbasAI** [comment]
@forslund so a standalone .py that would create another STT factory just to handle this? as in a new running process?

im not sure i follow you on this one

**Comment by forslund** [comment]
Exactly like that. A stand alone process recieving wav's sending it of to the configured STT, and then feeding the result forward to the intent service over the message bus.

The sst-factory is quite small and just returns a class sending of the file to a SST processor (local or online)

**Comment by penrods** [comment]
Jarbas, are you looking to support input from two different audio sources at once (WAVs and mic stream both)?  Or would you only need to send WAVs in all the time?

**Comment by JarbasAI** [comment]
fuu, checked out wrong branch working on the pt translation..sorry guys fixing this...

**Comment by JarbasAI** [comment]
i like forslunds aproach for wave file reader with own stt better

the idea is that at any time a skill or anything else connected to the bus could request STT for any file, for example @btotharye mycroft-api project could use this

**Comment by forslund** [comment]
@JarbasAI I've got an example of this pretty much ready. Gonna push to a repo later today

**Comment by JarbasAI** [comment]
I have seen your wave file repo, i like it

My idea was to enable to get the transcription from anywhere, not necessarily emit it to the intent service after, for example a "transcribe this file" skill that would monitor a folder or something

**Comment by forslund** [comment]
I haven't pushed the latest changes that would do something along those
lines. Matbe we can talk about it on mattermost in the next couple of days
and come up with something together. (At a wedding tonight)

Den 9 sep. 2017 9:06 em skrev "Jarbas" <notifications@github.com>:

**Comment by JarbasAI** [comment]
closing, https://github.com/JarbasAI/mycroft-wave-client/blob/master/main.py

**Pull request closed without merging**
