### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by jony0008**
Swedish translation of dialog messages

### CODE REVIEW

**Comment by forslund** [comment]
I've been about to do this for a long time myself, nice that you've gone and done it! Tack så mycket!

Before we can merge you need to sign the CLA https://mycroft.ai/cla

Another thing, we're using the four letter language codes so the folder name should be `sv-se`

**Comment by jony0008** [comment]
I have now signed the CLA. 
Please rename the folder to sv_FI and make a copy of the folder and rename it sv_SE because Swedish is one of the national languages in Finland. Tack!

**Comment by forslund** [comment]
Sure thing! Once I've gotten the confirmation of the CLA I'll handle it!

**Comment by forslund** [comment]
Merged in #1399. Closing

Stort tack @jony0008, det uppskattas verkligen!

**Pull request closed without merging**
