### PR TITLE
Cleanup of documentation

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
Improve documentation including standardizing docstrings and address warnings raised by the Sphinx readthedocs builder, as well as fixing up issues in CLI client.

- We currently go by the Google Python Docstrings Style Guide which uses `Args:` rather than `Arguments:`. This has been inconsistently used throughout the code base so this modifies them all to be the standard.
- Fixed heading underlines to silence warnings
- Added missing lines to silence warnings and aid readability
- Improved formatting of particular items eg `mycroft.MycroftSkill.get_response` had missing content, and now provides highlighted examples.
- Fixed capitalization of "Skills" in the CLI help info
- Fixed incorrect colors on Log Output Legend
- Fixed incorrect keyboard shortcuts for next and previous utterances in CLI
- ran autopep8 on touched files to address auto-format.

## How to test
```
source .venv/bin/activate
cd doc
make html
```
Also check the CLI client

## Contributor license agreement signed?
- [x] CLA (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2898))

**Comment by forslund** [comment]
Looks nice, I do however still get a bunch of warnings:
`/home/ake/projects/python/mycroft-core/mycroft/util/parse.py:docstring of mycroft.util.parse.normalize:10: WARNING: Block quote ends without a blank line; unexpected unindent.`

Are these intended to be left in?

IMO the auto-pep8 should be run in a separate commit but not a big deal here.

**Comment by krisgesling** [comment]
Indeed - need to PEP8 the whole repo so it doesn't catch you when you're updating something completely separate...
I might at least remove `text_client.py` and do that separately given the auto-format changes are quite extensive.

The remaining warnings for parse and format docstrings should no longer exist in this repo with the inclusion of LF v0.4.1.

Nice find on the underscore issue!

**Comment by forslund** [comment]
Then they were left intentionally. Feel free to add the common_iot_skill fix. And merge away when the PEP-8 line length issues have been fixed :)

**Review by forslund — DISMISSED** [review]

**Comment by krisgesling** [comment]
hmm soz... I probably should have done the PEP8 in a separate commit while I was at it, but I'm a terrible person :smiling_imp:

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2898)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2898/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2898/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2898/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2898/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2898/logs/enclosure.log)

**Comment by krisgesling** [comment]
Timer Skill you are drunk! :P

**Comment by forslund** [comment]
Timer skill is definitely the black sheep among the skills. Always the drunk one and always the loudest :P

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2898))

**Review by chrisveilleux — APPROVED** [review]
Hard to _argue_ with this change... oh I crack myself up.  Nice work Gez.

**Pull request merged**
