### PR TITLE
Fix PEP8 and unittest errors from PR 1049

### PR DESCRIPTION
**Pull request by penrods**
PR 1049 introduced several cosmetic PEP8 errors that were easily fixed.
Additionally there are unittests that include non-ASCII characters which are
failing.  As Pt-PT support is a work-in-progress, I just commented them out
with TODOs next to them.

### CODE REVIEW

**Comment by penrods** [comment]
@JarbasAI check out the unittest failures, please.

**Comment by forslund** [comment]
Looks good!

**Comment by JarbasAI** [comment]
will investigate tests failing, i'm pretty sure they weren't before so perhaps i messed up the PR itself with old code...

**Comment by forslund** [comment]
@jarbasai from my brief checks it's a file encoding issue. All non-ascii characters shows as <?> when the file is in utf-8. Do you know if you're using one of the Latin-* encodings or something?

**Comment by JarbasAI** [comment]
if i am it is not on purpose, doesn't # -*- coding: iso-8859-15 -*- at the top of the file solve this?

**Comment by JarbasAI** [comment]
i am not sure how to fix these, it seems to be encoding related, i just replaced the ? in a couple tests to the correct char and those no longer fail

how can i help solving this?

**Pull request merged**
