### PR TITLE
italian translation minor update

### PR DESCRIPTION
**Pull request by aleale99**
## Description
create mycroft/res/text/it-it/date_time.json
insert SHORT:_SCALe & LONG_SCALE in mycroft/util/lang/format_it.py

## How to test
no test  required: only translation

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
Thanks for the addition @aleale99, should any more test cases be added to cover these additions?

**Comment by aleale99** [comment]
hi @forslund the work to complete the tests is long, or better not so long, but it needs some steps:

- [ ] A : align the format_it.py functions to format_en.py
- [ ] B : align the parse_it.py functions to parse_en.py:
- [ ] C: : put in unittest_xx_it the **same** tests present in unittest_xx_en (both format and parse)

Now I am at 50% of point A and 35% of point C, but I  doesn't have much leisure time, I will also work during the holidays, so when I will have some commits... I will send.
sorry for my slowness :)

With best wishes for a prosperous new year.
AleAle

**Comment by forslund** [comment]
Thanks @aleale99 for looking into this and helping to expand mycroft's language support, there's absolutely no need to apologize. Happy Christmas and a Merry New Year (and/or any other celebrations you might partake in)!

**Comment by aleale99** [comment]
Hi @forslund you can help me ?

how can i manage the error  detected by  Codacy on SHORT_SCALE ?    we use only the long version
I learned here that there were two scales !!! :)

without this error for me the pull is completed and tested
the work on parse_it.py is going to require a lot of time

best wishes and happy new year!
Ale

**Comment by forslund** [comment]
Happy new year!

From what I can see I think it's reacting to the fact that those imports are unused in the file.

in parse_it.py You should be able to just replace the lines

```python
from mycroft.util.lang.format_it import NUM_STRING_IT, LONG_SCALE_IT, \
    SHORT_SCALE_IT, pronounce_number_it
```

with

```python
from mycroft.util.lang.format_it import pronounce_number_it
```

**Comment by aleale99** [comment]
hi @forslund 
do you think it's possible the merge of this part?

**Comment by forslund** [comment]
Hi, sorry I've fallen a bit behind on reviewing PRs. It looks pretty good, I'll try to get it tested tomorrow morning.

**Comment by forslund** [comment]
Tested and seems to work (as far as I can tell, Italian isn't exactly a language I know)

**Pull request merged**
