### PR TITLE
Initial spanish format functions 

### PR DESCRIPTION
**Pull request by adocampo**
## Description
This commit add the translations for nice_number_es, pronounce_number_es and nice_time_es

## How to test
`./start-mycroft.sh unittest`

## Contributor license agreement signed?
CLA [X] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by penrods** [comment]
This is looking much better!  I'm still not certain why it it is showing that the PR includes 10,000 commits.  But I think we can deal with that using a Squash and Merge.

I went ahead and modified this branch to remove the symbolic link to /opt/mycroft/skills -- that shouldn't be checked in, either.

**Comment by forslund** [comment]
The PR branch may have been based on master and not dev, but as @penrods says we can handle that when merging/reviewing. Thank you for this submission @adocampo!

**Comment by adocampo** [comment]
Thank you all guys to help me to accomplish it. 

I created the branch just after the clone of the main core repo, I expected it would be the dev branch, but probably was the master. Next time I'll check twice!

**Comment by adocampo** [comment]
Just for the record. It switched from dev to master when I ran ./dev_setup.sh, and answered 'Y' to everything... :man_facepalming:

**Comment by penrods** [comment]
Mystery solved!

**Pull request merged**
