### PR TITLE
Changes for Basque language

### PR DESCRIPTION
**Pull request by e-gor**
Changes for Basque language
===========================

#### Description

These changes, along with those sent to other repos, make Mycroft work in Basque language.

Made by Elhuyar, Talaios and Skura

#### Type of PR

Feature implementation

#### Dependencies
This PR relies on https://github.com/MycroftAI/lingua-franca/pull/206

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @e-gor, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2961))

**Comment by krisgesling** [comment]
Hey Igor, this is awesome, thanks!

For the new TTS and STT modules, we've created a plugin system so that these don't need to be merged and maintained in Mycroft-core. This means we aren't continually expanding core, and makes it easier to get fixes into individual packages. It also means you don't need to wait for merge requests like this to get in. We'll be extracting the existing modules out and making them their own plugin packages as well, just haven't gotten to that yet. 

Information on the plugin system is available here:
https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/plugins

and there's a complete TTS example here:
https://github.com/forslund/mycroft-tts-plugin-gtts

So it will be easiest if this PR only contained translation additions. The `nice_relative_time` addition will need to be done with an update to Lingua Franca.

Cheers

**Comment by e-gor** [comment]
So you mean I should take out the STT and TTS as modules? All right, but due to holidays, I do not think I will be able before September...

Regarding `nice_relative_time`, it is in the lingua-franca PR.

**Comment by krisgesling** [comment]
Yeah that's right, it's not sustainable for us to push everything into mycroft-core. The plugins help keep mycroft-core lighter and make it quicker for maintainers to distribute fixes. 

Just for clarity I've added the PR to Lingua Franca as a dependency in this PR description.

**Comment by e-gor** [comment]
> Information on the plugin system is available here:
> https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/plugins
> and there's a complete TTS example here:
> https://github.com/forslund/mycroft-tts-plugin-gtts

Is there a STT plugin example available?

**Comment by krisgesling** [comment]
Yeah, that looks right. There's also more available on PyPI if you want some other examples:
https://pypi.org/search/?q=mycroft+plugin+stt&o=

**Comment by e-gor** [comment]
Necessary changes in lingua-franca PRs done, @krisgesling. Once they are merged, this PR should have no conflict and could therefore be merged too.

**Comment by e-gor** [comment]
lingua-franca now has the nice_relative_time function (PR has been merged), but integration test still fails saying it does not exist, I do not know why...

**Review by ASTRA053 — DISMISSED** [review]

**Comment by krisgesling** [comment]
Hey Igor, we need to bump the Lingua Franca version to 0.4.3 in `requirements/requirements.txt`

I tried to push this to your branch but understandably don't have write access.

That should make the new function available, along with the rest of the Basque support.

**Comment by e-gor** [comment]
Sorry, my mistake (again), was not aware of that...

Did the required change, but there are still errors in the integration tests (though I do not think they are due to our changes, they are in Wikipedia skill, apparently).

**Comment by forslund** [comment]
Closing PR since we're archiving the repo

**Pull request closed without merging**
