### PR TITLE
#527 - skill to skill installation

### PR DESCRIPTION
**Pull request by augustnmonteiro**
For this skill work well the [auto reload skill](https://github.com/MycroftAI/mycroft-core/pull/524) should be merged.

### how it works:
say `hey mycroft install bitcoin` and [msm](https://github.com/MycroftAI/msm) will install the skill

### CODE REVIEW

**Comment by aatchison** [comment]
So, here is what I'm thinking.
I have an old version of msm hanging around on my computer.
Let's add a script like scripts/install-msm.sh.
This script can then clone the current version of msm that is working with the core (similar to mimic)
Add a configuration option to define the msm script location, with default in the mycroft-core/msm directory.
Then, when packaging we can define another location for installation by package (like mimic.)
Does this sound okay?

**Comment by augustnmonteiro** [comment]
yeah, it sounds good.
what you think about we install in /usr/bin ?

**Comment by aatchison** [comment]
This is where I install mimic.
mimic: /usr/local/bin/mimic
I can take care of the path in packaging as long as you have a line like this in config:

```
{
  "tts": {
    "module": "mimic",
    "mimic": {
      "voice": "ap",
      "path":"/usr/local/bin/mimic"
    }
  }
}
```

**Comment by aatchison** [comment]
Sort of like this:
https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/tts/mimic_tts.py#L32
The mimic path defaults to `./mimic/bin/mimic` in a git checkout environment, you could do the same for msm.
Checkout `./scripts/install-mimic.sh`

**Pull request merged**
