### PR TITLE
Parallel skill test

### PR DESCRIPTION
**Pull request by forslund**
## Description
Experiment splitting skilltest into 2 set run in parallel. Hopefully this will reduce the total test time. 

Still todo:
- Make the docker building more effective
- Reporting results

## How to test
Assert that Voight Kampff still tests all skills in a sensible manner

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/null)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/null/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/null/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/null/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/null/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/null/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/null)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/null/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/null/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/null/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/null/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/null/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2811))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2811/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2811)). 
Mycroft logs are also available:
Set 1:
[skills.log](https://reports.mycroft.ai/core/PR-2811/logs/set1/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/set1/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/set1/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/set1/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/set1/enclosure.log)

Set 2:
[skills.log](https://reports.mycroft.ai/core/PR-2811/logs/set2/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2811/logs/set2/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2811/logs/set2/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2811/logs/set2/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2811/logs/set2/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2811))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2811))

**Comment by forslund** [comment]
Closing PR since we're archiving the repo

**Pull request closed without merging**
