### PR TITLE
Issue-2550 - Update contributor guidelines

### LINKED ISSUE #2550: Contributing guidelines out of date and inconsistent
## Overview
The contributing guidelines for mycroft-core need minor updates to correct a broken links, provide a bit more clarity for new contributors, and ensure consistency between the use of 'issue' and 'issues'.

## Proposed Resolution
- Fix broken links, so creating an issue links to the actual mycroft-core issues / testing pages, not 404 or redirects
- Add code block showing how to add an upstream remote after forking
- Update recommendations to use singular 'issue' in all locations, rather than a mix of 'issue' and 'issues'
- Various copy changes for clarity

I am happy to take care of these items and will be submitting a PR shortly that reflects the changes. I think this will provide increased clarity moving forward to those who wish to contribute.

Additionally, I think we could improve the clarity of the pre-PR rebase codeblock, but this is more personal preference--I know everyone has their own individual style on how they reset / rebase from upstream and merge changes.

### PR DESCRIPTION
**Pull request by codyreinold**
## Description
This PR updates contributor guidelines to improve clarity, fix some broken links, and hopefully make it easier for new developers to contribute to the project! No code changes included--only updates to the GitHub md file. Resolves #2550.

## How to test
Review contributor guidelines located at the top of the Issues Tracker, or via any other link on GitHub. Confirm language aligns with project goals and new / update links lead to the appropriate resources (not 404 or redirects).

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @codyreinold, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2551))

**Comment by forslund** [comment]
Thanks for updating this. I'll assign it to @krisgesling for doing a review of the update.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2551))

**Comment by krisgesling** [comment]
Great update, thanks!

I have been slowly consolidating all end-user facing documentation into the documentation repo which is hooked up to Gitbook but I think this contributing guide will continue serving a useful purpose for a while yet :)

**Pull request merged**
