### PR TITLE
Adding a stop() function to audioservice.py

### LINKED ISSUE #1194: Calling the pause() function does not pause the playback
This [pause() function](https://github.com/MycroftAI/mycroft-core/blob/a9d627c979b98053719200c6084f3b31a9a97c62/mycroft/skills/audioservice.py#L83) does not have the desired effect of pausing the playback. 
`self.emitter.emit(Message('mycroft.sudio.service.stop'))`
This stops the playback, but the Audioservice does not expose a stop function. I could make the commit to add the stop() function if agreed upon.

### PR DESCRIPTION
**Pull request by akailash**
Fix #1194

### CODE REVIEW

**Comment by forslund** [comment]
Thank you, it looks good!

Before I can merge this you need to sign the Contributor License Agreement (https://mycroft.ai/cla/) to basically you allow us to use the code with the license we're using. It's mainly details but it ensures that everything is Ok.

Is soon as I get confirmation I'll merge this.

**Comment by akailash** [comment]
I filled in the Contributor License Agreement (https://mycroft.ai/cla/) yesterday but I am yet to get a email with the HelloSign link.

**Comment by forslund** [comment]
Hi did you get a link yet or has it gotten lost somehow?

(Please check your spam folder as well)

**Comment by akailash** [comment]
Hi, I got the link last night. I have signed it.

**Comment by forslund** [comment]
Many thanks for this. Merging now.

**Pull request merged**
