### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by apachelogger**
installation is spelled with two l

### CODE REVIEW

**Comment by forslund** [comment]
Thanks @apachelogger, every bit helps!
This feels a bit silly but we need you to sign a CLA  before we merge this fix. Sign the CLA here: https://mycroft.ai/cla/

Should be a quick process and is basically to make sure everything is up-and-up legally.

Once more thanks for your contribution.

**Comment by penrods** [comment]
Even if it is a little silly, beyond the keeping things spotlessly clean from a legal standpoint I want to acknowledge EVERYONE who has helped in any way!  Including correcting my typo.  :)

**Comment by apachelogger** [comment]
CLA should be signed now.

**Comment by forslund** [comment]
Nice, @penrods will get a notification and can merge whenever he get's a chance.

**Comment by penrods** [comment]
Thanks!

**Pull request merged**
