### PR TITLE
Issues 76 - Fix changes to wikipedia skill so that tests pass

### PR DESCRIPTION
**Pull request by ethanaward**
I changed the wikipedia skill so that it triggers on 'what does wikipedia say about'. I also removed 'who is' and 'who was' in the vocab, as those will be handled by Wolfram.

### CODE REVIEW

**Comment by ryanleesipes** [comment]
@ethanaward please coordinate with @jdorleans to see why the tests aren't working on this PR.

**Comment by jdorleans** [comment]
I thought I had commented on this PR a few days ago. Have you guys created another PR for this task?

**Comment by ryanleesipes** [comment]
Yeah, this is a different (clean) PR.

**Comment by jdorleans** [comment]
Ok, the changes seems reasonable, but before merging I'd like to know if anyone has tested it.

**Comment by ethanaward** [comment]
I tested it using ./start.sh unittest on my own, and the tests passed.  @ryanleesipes was wondering why the tests weren't showing here, though.

**Comment by jdorleans** [comment]
ok, this seems to be a forked branch which means it does not exist into our repo. As a result, Travis won't be able to find it and run the tests

**Pull request merged**
