### PR TITLE
Add a given an Italian speaking user

### PR DESCRIPTION
**Pull request by damorosodaragona**
## Description
(Description of what the PR does, such as fixes # {issue number})

## How to test
(Description of how to validate or test this PR)

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @damorosodaragona, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2710))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2710))

**Comment by krisgesling** [comment]
Hey Dario, got your CLA and you've been added to our [list of excellent humans](https://github.com/mycroftAI/contributors) :tada:

For this I wonder if we can generalize the existing "Given an english speaking user" Step rather than create a new one for each language?

My first thought is that we create a dictionary to map the full language names to their respective code, eg:
```
{
  'english': 'en-us',
  'australian english': 'en-au',
  'italian': 'it-it'
}
```
There's probably a better way to do this though...

I'm also not confident that setting the language in the context like this actually has the intended effect but I could be wrong. Have you tested this with Italian dialog? 

We might need to use the new [`patch_config`](https://github.com/MycroftAI/mycroft-core/blob/06e958cf737a1f5e6e31f44b99ece13d57b6444d/test/integrationtests/voight_kampff/features/steps/configuration.py#L24) instead. See [this Step for an example](https://github.com/MycroftAI/mycroft-core/blob/06e958cf737a1f5e6e31f44b99ece13d57b6444d/test/integrationtests/voight_kampff/features/steps/configuration.py#L98)

**Comment by krisgesling** [comment]
Closing as we haven't had any engagement beyond the original PR but this is on the longer term roadmap for full multilingual support.

**Pull request closed without merging**
