### PR TITLE
Address Python 3 changes

### PR DESCRIPTION
**Pull request by penrods**
Touch on several Python3 issues

## Contributor license agreement signed?
CLA [ X ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by cclauss** [comment]
__pep8__ was renamed to __pycodestyle__.  I would recommend that the latter is pip installed and run instead of the latter.  flake8 is a superset of pycodestyle + PyFlakes + McCabe Complexity + a few other special tests.  It is the most recommended of all.

**Comment by penrods** [comment]
FYI:  The CI failure is due to PEP8 stuff that got addressed in #1766 and will disappear when this merges.

**Comment by penrods** [comment]
Thanks, @cclauss.  We'll look at migrating tools later.

**Comment by forslund** [comment]
Looks good. merging.

**Pull request merged**
