### PR TITLE
Bugfix/issue 175

### LINKED ISSUE #175: ubuntu 14.04 missing screen
It looks as if `screen` isn't installed by default in ubuntu 14.04.  It's required by [`mycroft.sh`](https://github.com/MycroftAI/mycroft-core/blob/master/mycroft.sh).
http://releases.ubuntu.com/14.04/ubuntu-14.04.4-desktop-amd64.manifest
It needs to be added to [`build_host_setup.sh`](https://github.com/MycroftAI/mycroft-core/blob/master/build_host_setup.sh)

### PR DESCRIPTION
**Pull request by forslund**
Fixes #175.

Adds screen to required packages, also sets `mycroft.sh` to exit on first error.

### CODE REVIEW

**Comment by aatchison** [comment]
Ehh, let's just do it. We can separate build and development prerequisites later.

**Comment by aatchison** [comment]
lgtm, lgtU?

**Comment by forslund** [comment]
If you're happy I'm happy.

**Comment by aatchison** [comment]
;)

**Pull request merged**
