### PR TITLE
New config file for GitHub Actions

### PR DESCRIPTION
**Pull request by chrisveilleux**
## Description
WIP for testing GitHub Actions as a replacement for Travis CI

## How to test
All unit tests should pass for all supported versions of Python

## Contributor license agreement signed?
CLA [Y]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by forslund** [comment]
You can also look at #2764 which does the same thing

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2817)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2817/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2817/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2817/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2817/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2817/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2817)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2817/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2817/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2817/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2817/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2817/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2817)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2817/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2817/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2817/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2817/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2817/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by j1nx** [comment]
> You can also look at #2764 which does the same thing

Perhaps you should have been more direct or use the /endsarcasm tag.

Very disrespectfull to ignore a PR of a community member and then even commit with the message that you even pull in code from it without even one little message in either PR.

If he only used that same commitment when working on the backend stuf... /END SARCASM

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2817)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2817/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2817/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2817/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2817/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2817/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2817)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2817/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2817/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2817/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2817/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2817/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2817))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2817)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2817/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2817/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2817/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2817/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2817/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2817)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2817/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2817/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2817/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2817/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2817/logs/enclosure.log)

**Comment by chrisveilleux** [comment]
Closing this PR as it was just being used to test the process.  See [PR 2819](https://github.com/MycroftAI/mycroft-core/pull/2819) for the final implementation.

**Pull request closed without merging**
