### PR TITLE
fix syntax error for Python 3

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by stardiviner** [comment]
@augustnmonteiro I updated `dev_setup.sh` to use Python 3 now. check out. Is there other places to modify?

**Comment by stardiviner** [comment]
@augustnmonteiro I updated `dev_setup.sh` which is from your email attachment. Thanks. Please check it out the updated branch.

**Comment by ethanaward** [comment]
This seems like it changes the whole git install to use python 3 rather than just fixing syntax errors in preparation for a change, which is a very substantial change. Do we know that all of our dependencies and the codebase work with python 3?

**Comment by kfezer** [comment]
This is similar to the newer PR https://github.com/MycroftAI/mycroft-core/pull/446#issuecomment-311780314

**Pull request closed without merging**
