### PR TITLE
Merge pull request #1 from MycroftAI/dev

### PR DESCRIPTION
**Pull request by FruityWelsh**
Feature: Allow mycroft-speak and mycroft-say-to to accept bash pipes

## Description
Feature: Allow mycroft-speak and mycroft-say-to take bash pipes #2105

## How to test
with mycroft instance running
run cmd: mycroft-speak test
confirm mycroft speaks
run cmd: echo test | mycroft-speak
confirm mycroft speaks

run cmd: mycroft-say-to "hey mycroft"
confirm mycroft acknowledges
run cmd: echo "hey mycroft" | mycroft-speak
confirm mycroft acknowledges

## Contributor license agreement signed?
CLA [X]

### CODE REVIEW

**Comment by penrods** [comment]
There are no file changes in this PR.  I'm guessing this isn't what you intended.  ;-)

**Comment by penrods** [comment]
@FruityWelsh, Additionally, if you do get you code in this PR (or any other)...

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by FruityWelsh** [comment]
Sorry I am pretty new to actually using git. 
This is the corrected pull-request
https://github.com/MycroftAI/mycroft-core/pull/2111

**Comment by penrods** [comment]
I'm going to close this PR as it appear to be replaced by #2111

**Pull request closed without merging**
