### PR TITLE
Handle multiple intents with the same name

### PR DESCRIPTION
**Pull request by forslund**
## Description
This implements Alternative 1 from #2920 

- It will raise a `ValueError` if two named `IntentBuilder`s with the same name is registered
- If anonymous `IntentBuilder`s are used they will be automatically given an unique name

The handling for enable-disable intent was updated to make sure that the intent was removed from the list of `registered_intents`, for re-enabling it's moved to a list of `detached_intents`

## How to test
Add a second `@intent_handler()` decorator to a method ensure both can be used to trigger the handler and that the handler is triggered exactly once.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2921))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2921)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2921/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2921/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2921/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2921/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2921/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2921))

**Comment by forslund** [comment]
It's now more than a year since the last concern raised here was pushed (I think), is this something the core team is interested in or should I close the PR?

**Comment by krisgesling** [comment]
Hey Ake, I think it's a good change - seems like everything is accounted for and it passed all the tests. So if there's no opposition I think we can merge it in. 

I'll do this on Monday/Tuesday unless I hear otherwise.

**Pull request merged**
