### PR TITLE
Improve help message and logging of dev_setup.sh

### LINKED ISSUE #1714: Incidental findings from review of `dev_setup.sh`
_Background_ Did a review of `dev_setup.sh` for #1712 and raised these questions during review, moving to new Issue to separate them out. 

### `dev_setup.sh`

1. In the `show_help()` function, recommend pointing the user to Chat or Forums if they have questions - this isn't a _technical_ thing per se, but it helps to grow the Dev Community

2. just a minor nit-pick, but I'd set the `opt_skipmimic` and `opt_allowroot` flags above `show_help()` and add comments around what they do. 

3. there is an `--allow-root` option, but the code does not allow for the similar `--skip-mimic` - for usability and predictable usage, recommend added `--skip-mimic` as an allowable option. 

4. In the code block that checks whether `--allow-root` is set, and exits if it is not, then I would add a log entry using `syslog` or similar to `mycroft-update.log`, as it makes sense to log this for troubleshooting. 

5. In the function `install_deps()` I'd be inclined to add commentary around which platform each package manager is usually associated with - this would likely help with troubleshooting in the future, particular for non-Debian flavours of Linux. 

6. I might be missing something, but why are we installing `python2` packages with some of the installers, for instance `pacman` for Manjaro? 

7. I think there is a typo in line 119 (of your commit, line 116 of previous commit) - reads `${blue} git python 2 python-setuptools ...`. I _think_ `python 2` should be `python2`. 

8. In the function `install_venv()`, how likely is it that the URL for `get-pip.py` will change in the future? Should it be abstracted into a var at the top of the bash script? 

9. On line 156 I think we should warn the user that building `mimic` can take upwards of an hour. 

10. Do we need to check that the `venv` installs successfully in `install_venv()` and log and exit if it doesn't? It doesn't seem like a common source of failures, but being thorough. 

11. Why do we force the version of `pip`? `pip` is up to about version 18, and I wonder if this causes any confusion? 

12. On line 234 do we need to set the execute bit for `start-venv.sh`? I'm not sure, so asking the question. 

13. why is `/var/log/mycroft` 777? Should it be 775 with `mycroft:mycroft` - again I'm not sure so more "kicking the tyres" / questioning. 

### main.py

* In function `check-dependencies()` we pipe `notify-send` to `/dev/null` - again should we syslog this to one of the logs for troubleshooting? 

END comments

### PR DESCRIPTION
**Pull request by mikejgray**
## Description
Corrects incidental findings from review of dev_setup.sh (fixes https://github.com/MycroftAI/mycroft-core/issues/1714). Most of the findings have been corrected already. This PR should close what little remains, aside from a security concern with log file permissions that probably belongs in a separate issue.

## How to test
Execute dev_setup.sh in various operating systems
Execute `shellcheck dev_setup.sh` for linting and best practices

## Contributor license agreement signed?
CLA [x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-3105))

**Comment by forslund** [comment]
Looks like a nice improvement. I think the github action is running into an issue when the log folder hasn't been created and given the correct permissions. Maybe move that stage to the start of the setup?

**Comment by mikejgray** [comment]
Checked locally, should be ok this time.

**Review by forslund — DISMISSED** [review]
I think these changes looks good now and the CI is happy. Do you think it would be a good idea to add a "setup complete" line at the end to explicitly show that the dev-setup completed successfully?

**Comment by mikejgray** [comment]
Probably not a bad idea. We can also explicitly call out that the new logfile exists and may have further information. Should I include that in this PR?

**Comment by forslund** [comment]
I think it's a good idea @krisgesling do you have any opinion?

**Comment by mikejgray** [comment]
I went ahead and added it in.

**Comment by krisgesling** [comment]
Hey sorry, I was away last week but this looks great. 

Agree on the final success message too :+1: 

My only question is whether we need to use the `-a, --append` flag for all the `tee` calls? Currently it seems to overwrite the log file with each new line.

**Comment by mikejgray** [comment]
Thanks @krisgesling , good call-out. I'll be sure to have a better test setup next time. I've submitted that fix.

**Comment by mikejgray** [comment]
@forslund Anything else you'd like me to do on this PR?

**Review by krisgesling — APPROVED** [review]
Thanks Mike this is all working great now!

**Pull request merged**
