### PR TITLE
Feature: enable simultaneous CI jobs and keep logs

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
- When multiple jobs run Voight Kampff tests simultaneously they are currently writing the allure data to the same directory on the host. This can create clear conflicts.  These are now stored under unique directories `$HOME/core/PR-####/(allure|mycroft-logs)` that are cleaned up on each run.
- This PR also retains mycroft-logs and provides them on test failure as is now done for mycroft-skills.
- Adds a lockable resource with the repo and PR number to ensure that the directory won't be used by another job from the same PR. I don't think this can happen anyway, but it seemed like an easy fail safe.
- Finally we improved the cleanup of docker containers by explicitly removing containers generated by this job if the build was successful. Based on: MycroftAI/selene-backend#230

## How to test
Replay all the jobs!

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2762)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2762/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2762/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2762/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2762/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2762/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2762)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2762/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2762/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2762/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2762/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2762/logs/enclosure.log)

**Comment by forslund** [comment]
The big issue here is sharing of the Mycroft identity. If multiple mycroft instances shares it it may be saved in an invalid state if the identity is updated.

**Comment by krisgesling** [comment]
In this instance I think it was just a directory permissions issue. 
As I hadn't created the directories in the script, when binding them with Docker it created them automatically but with incorrect permissions. 
So I've added a `mkdir -p` to explicitly create them and removed the directories that were previously created on the host.

I haven't yet seen the identity issue surface. It is something we should address but doesn't seem to be a blocker just yet.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2762))

**Comment by forslund** [comment]
I didn't mean that it was the cause of the failure. I just pointed out a potential hurdle here. (it has historically been an issue)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2762))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2762))

**Review by chrisveilleux — APPROVED** [review]

**Pull request merged**
