### PR TITLE
typo

### PR DESCRIPTION
**Pull request by doczkal**
Aprill ... April

## Description
(Description of what the PR does, such as fixes # {issue number})

## How to test
(Description of how to validate or test this PR)

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
Thanks for this typo-fix. it looks very correct :)

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by forslund** [comment]
Hi, I've yet not seen a confirmation of you signing the CLA, has there been any issue?

-Åke

**Comment by doczkal** [comment]
Sorry for the late reply... Where can I snail mail the signed document to?

**Comment by penrods** [comment]
Did you receive the electronic signature request?  That is honestly easier
for both you and us.

If you really prefer snail mail, you can send a paper copy of the document
to:
    Mycroft AI
    Attn: Steve Penrod
    300 E. 39th Street
    Kansas City, MO   64111

**Comment by doczkal** [comment]
The signed letter is on it's way. Thanks for your patience and understanding.

**Comment by doczkal** [comment]
Have you received something yet?

**Comment by penrods** [comment]
It showed up today!

**Pull request merged**
