### PR TITLE
Feature/issue 2593

### PR DESCRIPTION
**Pull request by INsiteLabDev**
## Description
(Description of what the PR does, such as fixes # {issue number})

Fixes issue #2593 by enabling modification of rate SSML tag. We have a RateSkill being developed so that the user can modify the rate. Once this change on issue 2593 is approved, the RateSkill will be functional.

## How to test
(Description of how to validate or test this PR)

Since this feature depends on the integration of the RateSkill, testing would involve manually modifying the rate value in audio_config.txt file. Once the RateSkill has been incorporated the user will be able to use voice commands to modify the rate at which Mycroft responds. Sample values to manually test with range between 0.5-1.7 as a string to adjust the output rate. 

## Contributor license agreement signed?
CLA [X] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @INsiteLabDev, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by INsiteLabDev** [comment]
Hello, 
We have actually signed a CLA already and have been added to [Mycroft Contributer List](https://github.com/MycroftAI/contributors?fbclid=IwAR3FdP0_FkQSp76bybMkmmNAhzBLMYuXkGlqo7Cyc9v2vVAcR82MovY3k_g)

Additionally, we have attached the CLA file to this comment as well for your reference. Thank you!
[Corporate_Mycroft_Contributor_Agreement.pdf](https://github.com/MycroftAI/mycroft-core/files/4684659/Corporate_Mycroft_Contributor_Agreement.pdf)

**Comment by JarbasAl** [comment]
i kinda dislike this, SSML support is there already https://github.com/MycroftAI/mycroft-core/pull/1545

skill using SSML might run into conflicts with this. 

If the objective is having a "global ssml" that always applies, then it should be TTS engine agnostic. Engines that dont support it will just ignore the tags

**Comment by forslund** [comment]
I agree with @JarbasAI here, I suggest you look into the comment I gave in #2593 about using the duration_stretch config value. It will be static for the entire sentence but ssml tags can override.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2596))

**Comment by JarbasAl** [comment]
i also do not like the use of ```eval```, and a new .txt file makes no sense, if anything add a param to mycroft.conf

**Comment by devs-mycroft** [comment]
Hello, @INsiteLabDev, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devs-mycroft** [comment]
Hello, @INsiteLabDev, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by krisgesling** [comment]
Hey INsite team, we are shifting to a plugin system that might be of interest to you. It will allow the creation of TTS service plugins along with STT and Audioservice backends. 

The [first draft of the documentation](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/plugins) is up and the TTS example might provide some useful guidance around how to structure the configuration parameters in the overall `mycroft.conf` rather than creating a new config file.

The plugin system also means that whatever you want to do, you can have a custom TTS that easily loads into Mycroft, without having to maintain a fork of mycroft-core.

**Comment by krisgesling** [comment]
Hey there, as we're moving to the plugin system, I'm closing this PR. 

Hope things are still progressing well for your team.

**Pull request closed without merging**
