### PR TITLE
Pull request to Galician language translation

### PR DESCRIPTION
**Pull request by Davidrebolomaga**
## Description
(Description of what the PR does, such as fixes # {issue number})

## How to test
(Description of how to validate or test this PR)

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @Davidrebolomaga, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-3053))

**Comment by krisgesling** [comment]
Hi David, 

Thanks for all this translation work! It's always exciting to see Mycroft coming to new languages. 

Have you had a chance to look at the CLA? If you have any questions about it please let me know.

**Comment by forslund** [comment]
Closing PR since we're archiving the repo

**Pull request closed without merging**
