### PR TITLE
German formatting for Wolfram alpha skill responses in format_de.py

### PR DESCRIPTION
**Pull request by f-e-l-i-x**
Response formatting for German language ordinals depending on cases/prepositions for dates
"am 1. März" -> "am ersten März" (on the first of March)
"der 1. März" -> "der erste März" (the first of March)
"1. März" -> "erster März" (first of March)

Response formatting for mathematical results
"10 ^ 2" -> "10 hoch 2" (ten to the power of two)

Can be tested via the corresponding test_format_de or by using wolfram alpha skill:
"Was ist die Fläche von Canada"
"Wann ist George Washington geboren"

### CODE REVIEW

**Comment by f-e-l-i-x** [comment]
I don't quite understand why the Travis CI build failed

**Comment by penrods** [comment]
I can simply tell you, but let me "teach you to fish".  :)

Click on the Details button next to "The Travis CI build failed" to jump to Travis-CI.  Once there, you should see the failure message and a Build Jobs section in the lower right area.  Click on an entry to see detailed output from the job.  You can scroll through there to find the errors, usually highlighted in red.

In this case, the failure is from PEP8 testing.   PEP8 is horribly picky, but it also keeps the codebase from getting messy.  In this case it is complaining about a few simple issues regarding blank lines in some of your code:
```
mycroft/util/lang/format_de.py:350:1: E302 expected 2 blank lines, found 1
mycroft/util/lang/format_de.py:366:1: E302 expected 2 blank lines, found 1
mycroft/util/lang/format_de.py:390:1: W391 blank line at end of file
```

This output shows you which files, and then which line:column within that file has the issue.  If you can't tell the exact reason, you can Google "pep8 E302" or whatever error code for more info.


Thanks for your contributions!

**Comment by f-e-l-i-x** [comment]
@penrods Thanks a lot!

**Comment by penrods** [comment]
LGTM!  Danke!

**Pull request merged**
