### PR TITLE
Add more Italian variations for yes.voc

### PR DESCRIPTION
**Pull request by amaciotta**
Improvement italian translation.

## Description
Enhanced recognition of affermative responses in italian.

## How to test
When Mycroft is asking for "yes" or "no" answer with new phrases.

## Contributor license agreement signed?
CLA [X]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Hello, @amaciotta, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-3126)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-3126/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-3126/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-3126/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-3126/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-3126/logs/enclosure.log)

**Comment by forslund** [comment]
The CI failure seems to be the regression in the Wikipedia-skill so there is no issue with this PR.

**Comment by krisgesling** [comment]
Hi there,

Thanks for this.

CLA received and agree with Forslund about the CI failure.

Merging :)

**Pull request merged**
