### PR TITLE
Display Service

### PR DESCRIPTION
**Pull request by JarbasAI**
initial proposal for a display service based on forslund's audio service

I know the enclosure now handles display, this should not interfere in any way and could be used by a "desktop enclosure" 

Early work but functional, don't expect it to get merged soon, just want to generate discussion for improvements!

Display Control Skill (own repo coming soon):
https://github.com/JarbasAI/JarbasAI/tree/patch-15/jarbas_skills/skill_display_control

Demo:
https://www.youtube.com/watch?v=cKc_RxRbJ3U&feature=youtu.be

TODO:

- video support
- many backends

### CODE REVIEW

**Comment by btotharye** [comment]
looks like the build failed with:

cp: cannot stat ‘/usr/lib/python2.7/dist-packages/cv*’: No such file or directory

Might want to make sure there aren't any issues here.

**Comment by JarbasAI** [comment]
perhaps someone can help me with that, open-cv doesn't like being installed in virtual envs

https://medium.com/@manuganji/installation-of-opencv-numpy-scipy-inside-a-virtualenv-bf4d82220313

the way i handled it is installing open-cv system-wide and then copy the files to virtual env folder, seems to work in my fork (not extensively tested, one time i had to run the cp command again for some reason)

**Comment by forslund** [comment]
Seems like it requires a newer version of pip to install. (Tried with 9.0.1)

**Comment by JarbasAI** [comment]
doesnt work, the pip package doesn't support displaying images (the author says so and i tried it)

**Comment by forslund** [comment]
@JarbasAI Ok, I see. I only read about the problem with video.

**Pull request closed without merging**
