### PR TITLE
Bugfix/audioservice issues

### PR DESCRIPTION
**Pull request by forslund**
## Description
This is an attempt to make the audioservice behave better in the VK test. In particular it tries to handle exceptions seen in the audio.log after a failing VK run such as:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/opt/mycroft/mycroft-core/.venv/lib/python3.6/site-packages/pyee/_executor.py", line 56, in _callback
    self.emit('error', exc)
  File "/opt/mycroft/mycroft-core/.venv/lib/python3.6/site-packages/pyee/_base.py", line 116, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/opt/mycroft/mycroft-core/.venv/lib/python3.6/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
    raise error
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/mycroft/mycroft-core/mycroft/audio/services/simple/__init__.py", line 90, in _play
    if isinstance(self.tracks[self.index], list):
IndexError: list index out of range
```

This PR adds a lock and a check that the track in question still exists before starting playback.

It also handles an issue where the playback isn't restored as it should after speaking when using the dummy tts module 

## How to test
(Description of how to validate or test this PR)

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2804)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2804/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2804/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2804/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2804/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2804/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2804)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2804/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2804/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2804/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2804/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2804/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by forslund** [comment]
This commit contains fixes to the singing skill test steps to verify that with those in place. It after the singing skill has been updated that commit can be dropped along with the speed testing commit.

**Comment by krisgesling** [comment]
You're awesome, thanks Ake!!!

I've done PR's to add this VK method to the Singing Skill and mycroft-core - though renamed the method. I know you just grabbed this from News - name not your fault. Just thought `wait_for_audio_service` was more descriptive.

**Comment by forslund** [comment]
Still seem to find ways to fail :( Will continue investigation...

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2804)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2804/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2804/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2804/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2804/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2804/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2804)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2804/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2804/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2804/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2804/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2804/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2804)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2804/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2804/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2804/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2804/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2804/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2804)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2804/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2804/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2804/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2804/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2804/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2804)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2804/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2804/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2804/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2804/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2804/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2804))

**Comment by forslund** [comment]
I've removed the Work in progress tag, The last 10 tests have completed without singing or news skills failures.

**Review by krisgesling — APPROVED** [review]
All looks good and working locally too. 

Here's hoping it really has put these tests to bed :crossed_fingers:

**Pull request merged**
