### PR TITLE
feat/ read mark1 eye color

### PR DESCRIPTION
**Pull request by JarbasAl**
## Description
Adds a mechanism to query the current eye color for the mark1

There is no way to get this info from the arduino directly, instead this keeps track of every change in the Enclosure class

## How to test
```python
pixels = self.enclosure.get_eyes_color()
individual_pixel = self.enclosure.get_eyes_pixel_color(idx)
```

## Contributor license agreement signed?
CLA [y] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
Works very well :+1: 

Just a tiny nitpick can you look at the docstrings and make them in the same style as the rest?

The summary line at the same line as """ and a `Returns:` section

```python
        """Get the eye RGB color for all pixels
        Returns:
           (list) list of (r,g,b) tuples for each eye pixel
        """

**Comment by forslund** [comment]
Seems like this needs a rebase as well to fix the conflicts.

**Comment by forslund** [comment]
I would still like to see the docstrings updated to conform with the Mycroft standard.

**Comment by JarbasAl** [comment]
done, i had changed in the mark1 folder but missed it under the enclosure folder

**Comment by forslund** [comment]
Very nice, I fixed up the commit history a bit, merging now.

**Pull request merged**
