### PR TITLE
PocketSphinx STT

### PR DESCRIPTION
**Pull request by JarbasAI**
add pocketsphinx as an offline solution for STT

### CODE REVIEW

**Comment by JarbasAI** [comment]
should i add .lm a .dict files for english by default?

**Comment by penrods** [comment]
Those dicts are pretty big, right?  I don't really want to bloat the repo if we can avoid it and instead pull down models from elsewhere on demand.

**Comment by JarbasAI** [comment]
32.4MB for the english .lm.bin and .dict

updating PR for .bin support

**Comment by zenogantner** [comment]
If you are worried about bloating the repo, you could look at git-lfs as a solution.
Mozilla's DeepSpeech uses it, too.

**Comment by JarbasAl** [comment]
closing this one, will make a plugin once #2594 is in

**Comment by JarbasAl** [comment]
@renekliment and anyone else interested, a plugin for this is now available https://github.com/OpenJarbas/mycroft-stt-plugin-pocketsphinx

**Pull request closed without merging**
