### PR TITLE
Feature/improved skill tester

### PR DESCRIPTION
**Pull request by forslund**
## Description
This is an updated version of #1431. Many thanks to @CarstenAgerskov for doing the main work here.

Changes are:
- Adding support for Padatious and fallbacks.
- Using pytest to do test discovery via parametrized tests
- Possibility to set up test environment
- `expected_dialog` and `expected_data` structures in the intent.json files

### Steps to test
 - `git checkout feature/improved-skill-tester`
 - `./dev_setup.sh -sm` (`pytest` is a new requirement)
 - `./start-mycroft.sh unittest`
 - Make sure the tests all succeed
 - `workon mycroft`
 - `pytest test/integrationtests/skills/discover_tests.py`
 - Now, many of these should fail, but make sure at least a few succeed (`.` means success and `F` means fail). Example correct output:
```
================================================================================================ test session starts ================================================================================================
platform linux2 -- Python 2.7.14, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
rootdir: /path/to/mycroft-core, inifile:
collected 99 items                                                                                                                                                                                                  

test/integrationtests/skills/discover_tests.py F....F......F.........FFFFFFFF..FF.......F.F...FFFFFFFF.FF..........FFFFF......FFFF.F.FFFFFFFFFFF..

# Then a bunch of junk
```

## Contributor license agreement signed?
CLA [Yes]

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
What's the status of this? Do we think it's ready to be reviewed?

**Comment by forslund** [comment]
I think so, it works well enough so...

**Comment by KathyReid** [comment]
Not sure if I'm helping or hindering here, I went to test this to try to help using the "Steps to test". Pulled the feature branch in, ran `dev_setup.sh` OK, but it did _not_ install `pytest`. 

```
kathyreid@kathyreid-N76VZ:~/Dropbox/PHPworkspace/mycroft-core$ ./start-mycroft.sh unittest
./start-mycroft.sh: line 166: pytest: command not found
```

**Comment by forslund** [comment]
The testing requirements are separated from the normal requirements so they are not installed by default. (since they shouldn't be installed when doing packaging and when just running it as a user)

You need to activate the virtual env and then install test-requirements.txt:

```
source .venv/bin/activate
pip install -r test-requirements.txt
```

**Comment by KathyReid** [comment]
OK that was super helpful @forslund - I've att'd my `unittest` results in the file below. 

[kathy-unittest.txt](https://github.com/MycroftAI/mycroft-core/files/2013944/kathy-unittest.txt)

**Comment by MatthewScholefield** [comment]
Should we install the `test-requirements.txt` by default in `dev_setup.sh`? The reason would be that `dev_setup.sh` isn't run when packaging, and `pytest` is light enough that it shouldn't matter that it's installed on a few people using a `git` clone who aren't developers.

**Comment by forslund** [comment]
Can't argue with that reasoning. Especially since now we want developers to test their skills so...

**Pull request merged**
