### PR TITLE
just more cancel words for cs-cz

### PR DESCRIPTION
**Pull request by Manasovo**

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2565))

**Comment by devs-mycroft** [comment]
Hello, @Manasovo, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Hi, the commit history of this PR seems a bit weird. Did you create the branch from master and not from dev?

**Comment by Manasovo** [comment]
yes sorry ... i will make a new pull request from dev

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2565))

**Comment by forslund** [comment]
The history is still a bit weird but I can fix that before merging. The problem I see is that the change in the mycroft/util/parse.py requires a newer version of lingua-franca, and I don't think that's released yet. If you remove the change to that file I can merge the translation files.

**Comment by Manasovo** [comment]
new lingua-franca with cs-cz support is already released 8 days ago. See at: https://github.com/MycroftAI/lingua-franca/commit/7ff4bcecdaff44815e013f6e8339693ed34c83d1

**Comment by forslund** [comment]
The last release of lingua-franca was [v0.2.1](https://github.com/MycroftAI/lingua-franca/releases/tag/0.2.1) on March 23. That change was merged on April 28 and there has been no release since then I'm afraid.

**Comment by Manasovo** [comment]
Yes you're right. It's not released yet, only in repo.

**Pull request closed without merging**
