### PR TITLE
Alan Pope voice runs by default, no idea what will happen when I pack…

### PR DESCRIPTION
**Pull request by aatchison**
…age it

### CODE REVIEW

**Comment by ryanleesipes** [comment]
This does work as intended. And the voice does sound clearer, but also seems quiet. Need to test on unit. If the voice can be understood at a reasonable volume, I will be alright with merging this.

**Comment by aatchison** [comment]
I'm pretty sure that it's not going to get any louder, it's a problem inherent in Mimic, and perhaps the voice  as well (remember to popping)

**Comment by ryanleesipes** [comment]
I also tested on my laptop speaker, which is not the best. I would like to see someone load this PR on a Holmes IV unit to hear what it sounds like there.

**Comment by aatchison** [comment]
As soon as I can I will. You could always do a checkout on the unit. It's going to be considerably less loud than the other sounds mycroft makes though. ...So they will turn the volume all the way up.....

**Comment by ethanaward** [comment]
LGTM, testing on a laptop.

**Comment by aatchison** [comment]
lgt...ethan!

**Pull request merged**
