### PR TITLE
Fix UnboundLocalError in AudioProducer

### PR DESCRIPTION
**Pull request by dalgwen**
==== Fixed Issues ====
#2779 

====  Tech Notes ====
The variable should be declared outside the loop.

## Description
fixes an UnboundLocalError exception

## How to test
Basic use of mycroft. Nothing broken, then good to go.

## Contributor license agreement signed?
CLA [X]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2780))

**Review by forslund — APPROVED** [review]
Nice catch, Looks good!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2780))

**Comment by krisgesling** [comment]
Awesome thanks @dalgwen!

**Pull request merged**
