### PR TITLE
Upgrade from pycodestyle to flake8

### PR DESCRIPTION
**Pull request by cclauss**
~Blocked by https://github.com/MycroftAI/mycroft-core/pull/2104#issuecomment-520016425~

## Description
(Description of what the PR does, such as fixes # {issue number})

## How to test
(Description of how to validate or test this PR)

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by cclauss** [comment]
Blocked by https://github.com/MycroftAI/mycroft-core/pull/2104#issuecomment-520016425

**Comment by forslund** [comment]
Thanks, looks like a very useful tool. We have an optional [pre-commit hook](https://github.com/MycroftAI/mycroft-core/blob/dev/scripts/pre-commit) which is based on pycodestyle should this also be upgraded to use flake8 or should the pycodestyle module be kept side by side of flake8?

**Comment by cclauss** [comment]
I usually run psf/black in my precommit which effectively makes pycodestyle unnecessary.

Flake8 is a superset of pyflakes + pycodestyle + McCabe complexity analysis + it adds its own issue codes.  Running flake8 unrestricted will execute all of the pycodestyle tests and will add many others besides.  Here we have focused flake8 on a handful of errors codes that effect runtime safety or correctness.

**Comment by devs-mycroft** [comment]
Hello, @cclauss, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by cclauss** [comment]
WTF w the CLA checker?

**Comment by forslund** [comment]
It's job was blocked and just ran now. You've not been added to the CLA list, I've sent an email to @krisgesling since he manually flipped you to "CLA: Yes" to check the status and why you weren't added.

**Comment by cclauss** [comment]
Bump on this one...

**Comment by forslund** [comment]
Thanks, can you look at the python 3.8 failure as well? (or maybe split that out into a separate PR if it's tricky)

We need to either restore pycodestyle to the test-requirements.txt or remove/update the precommit-hook util that's using it.

**Comment by cclauss** [comment]
flake8 is a superset of pycodestyle so installing flake8 will also install pycodestyle.

**Comment by forslund** [comment]
Ok NOW I get it, sorry for being dense. This looks very nice. Merging

**Comment by forslund** [comment]
Thanks for this.

**Pull request merged**
