### PR TITLE
 Issues 64 - Removing undesirable thread from speak function

### PR DESCRIPTION
**Pull request by jdorleans**
This PR fix the #64

### CODE REVIEW

**Comment by aatchison** [comment]
Testing in progress.

**Comment by aatchison** [comment]
It's really hard to gauge performance, but things seem to be working ok. Overall the response time seems much better recently.
I can't really review the code itself though.

**Comment by jdorleans** [comment]
@clusterfudge Please, check this PR. I need it to fix issues related to enclosure pairing code displaying

**Comment by ryanleesipes** [comment]
Works well, looks good to me, and unit tests are passing. Let's merge this @jdorleans

**Pull request merged**
