### PR TITLE
Added "found_wakeword" event to message bus

### PR DESCRIPTION
**Pull request by speedfox-uk**
## Description
Added an event to the message bus that will be sent when the wakeword
is found and before the notification sound is played

## How to test
Connect to the message bus and output all of the messages. Say the wakeword. You should see the "found_wakeword" message, 

## Contributor license agreement signed?
Yes

### CODE REVIEW

**Comment by devs-mycroft** [comment]
Hello, @speedfox-uk, thank you for helping with the Mycroft project! We welcome everyone
into the community and greatly appreciate your help as we work to build an AI
for Everyone.

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code
contribution. This agreement makes it crystal clear that along with your
code you are offering a license to use it within the confines of this project.
You retain ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank
you!

**Comment by forslund** [comment]
Hi This is working as expected...however it seems like the recognizer_loop:wakeword should mean the same thing. But that seem to be broken in some way. We should try to determine why the original message is late...

**Comment by speedfox-uk** [comment]
It's broken because the message tone is played in the same method that does the wakeword detection (_wait_until_wake_word in mic.py). The other way to fix this would be to take playing the wakeword detected tone out of _wait_until_wake_word and put it somewhere after the wakeword message has been sent. Either that or remove the current "wakeword" message and just rename my new message to that. I don't mind either way.

**Comment by forslund** [comment]
It's a bit more than that, (at least to me) it seems like it's not sent until after the recording of the STT phrase is complete...

**Comment by forslund** [comment]
I do think it'd be best if your message was renamed but that would also require the session id to be included

```python
SessionManager.touch()                                                  
        payload = {                                                             
            'utterance': self.wakeword_recognizer.key_phrase,                   
            'session': SessionManager.get().session_id,                         
        }                                                                       
        self.emitter.emit("recognizer_loop:wakeword", payload)
```

And the corresponding section in [listener.py](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/client/speech/listener.py#L188) should be removed.

**Comment by speedfox-uk** [comment]
OK, I'll make the change after I get home and update the PR.

**Comment by speedfox-uk** [comment]
I've renamed it to "wakeword" and removed the old one. I'm just grabbing the utterance from "self.wake_word_name" rather than keeping a reference to the wakeword recogniser because it seemed like a simpler solution.

**Comment by forslund** [comment]
Thanks, will look it over and hopefully merge tomorrow.

**Comment by forslund** [comment]
@davidwagnerkc had done some similar work so I've assigned him to do the review of these changes.

**Comment by speedfox-uk** [comment]
No problem. Just happy that this is making its way into master.

**Comment by forslund** [comment]
Did a rebase to clean it up but merging now. Many thanks for fixing this!

**Pull request merged**
