### PR TITLE
improve runtime

### PR DESCRIPTION
**Pull request by maxbachmann**
## Description
This PR improved the runtime of the pronounce_number_en function.
Depending on the arguments provided it is 2-5 times as fast, mainly by reducing the need to copy the dicts from common_data_en.py and type conversions.

## How to test
The behavior stays the same and is already covered by tests

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by forslund** [comment]
This looks great,

not related to your work in this PR but I do think the docstring for the `num` is incorrect. It states

>num(float or int): the number to pronounce (under 100)

Would you mind handling this while you're touching this code. If you don't have the time I can do it later.

**Comment by maxbachmann** [comment]
@forslund so this should probably be changed to
```
num(float or int): the number to pronounce
```
since it can be anything between -inf and +inf

**Comment by forslund** [comment]
That sounds good :+1:

**Comment by maxbachmann** [comment]
ok applied

**Comment by forslund** [comment]
Many thanks, Merging now.

**Pull request merged**
