### PR TITLE
Standardize

### PR DESCRIPTION
**Pull request by juliengk**
CLA [x]

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
Thanks for this; it looks a lot more consistent now. Two style changes that I think are more common in bash:
 - `echo $(echo hi)` rather than `echo $( echo hi )`
 - `if [ "$val" == "hi" ]; then` rather than `if ["$val" == "hi" ] ; then`

Any opinion on them? (@juliengk, @forslund, @penrods)

**Comment by forslund** [comment]
I'm ok with those rules @MatthewScholefield. At some point I think it may have been @el-tocino that suggested we'd use the google shell style guide https://google.github.io/styleguide/shell.xml

Is that something we should try to follow?

**Comment by juliengk** [comment]
* No space after $(: if we look at that [page](https://www.gnu.org/software/bash/manual/html_node/Command-Substitution.html#Command-Substitution), there are no spaces at all.
* No space after if [] : https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html#Conditional-Constructs

I could remove spaces for those 2 cases

**Comment by penrods** [comment]
Are these all manual edits, or do you have some sort of bash lint tool you used?  It is nice to clean this up, as there is a ton of variance in sh script styles and oddball rules if you were attempting to follow Posix vs bash, etc.  I see tools like https://www.shellcheck.net/, but that doesn't enforce spacing, consistent use of newline/then vs " ; then" etc.

I looked through all of these changes and am going to go ahead an merge this as-is.  We can do another PR with more cleanup later if we pick a specific style.  Ideally, I want one that has tools that reinforce it -- many of the changes that are in this code are from where different devs added to the scripts.

**Pull request merged**
