### PR TITLE
Refactor - common bus connection method

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
Following on from #2758 this switches the remaining Services to use the new common method for connecting to the message bus. This should only simplify the current code bringing together 4 different ways of doing the same thing.

## How to test
Run Mycroft and ensure all Services start and connect to the message bus as expected.

Given the significance of changes to the startup flow of Services, each should be checked carefully.

## Contributor license agreement signed?
- [x] CLA (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Review by forslund — CHANGES_REQUESTED** [review]
One tiny nitpick (missing argument in docstring) otherwise it looks good.
I wonder if we should consider moving the `mycroft.services.util` to `mycroft.util.process_utils` or move the contents of that file into `mycroft.service` since they seem heavily related.

**Comment by krisgesling** [comment]
Yeah I started the new module as I originally thought of abstracting more of the duplicated code to ensure all the services operate consistently and explicitly continue to do so (maybe a Service base class?). 

But `process_utils` looks like the perfect place for this right now.

Good spot on the docstring too :)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Review by forslund — APPROVED** [review]

**Comment by forslund** [comment]
Very nice, tested and working. :+1:

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Comment by JarbasAl** [comment]
to avoid code duplication, i would argue this should go into https://github.com/MycroftAI/mycroft-messagebus-client/

and the whole client folder in mycroft deprecated, mycroft-core only needs to contain the server, the Message object and the MessagebusClient can / should be imported from package above

**Comment by krisgesling** [comment]
I don't disagree with this in principle, means that everyone is using a common client rather than the client in core diverging from the client for 3rd parties. This PR still seems like it's going in the right direction toward that end goal.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Review by forslund — CHANGES_REQUESTED** [review]
Finally realized the issue here... The audioservices aren't registered...

The bus handlers was set to be registered when the bus started in an event handler, see [audioservice.pyL211](https://github.com/MycroftAI/mycroft-core/blob/feature/common-bus-connection/mycroft/audio/audioservice.py#L211). Can't quite recall why this was I believe it was a performance thing.

I think you should be able to fix it by replacing the line with 

`self.load_services()`

and renaming the `load_services_callback` method to `self.load_services`


Tested locally before (failing) and after (succeeding) [this commit](https://github.com/forslund/mycroft-core/commit/ddfaf68788f94ce3fe5a91934dbc6f80a758eb9f)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2792))

**Review by forslund — APPROVED** [review]

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2792)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2792/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2792/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2792/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2792/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2792/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2792))

**Pull request merged**
