### PR TITLE
Bugfix/issue 2563

### PR DESCRIPTION
**Pull request by katridi**
## Description
#2563 If there is no path e.g. `~/mycroft/mycroft-core/mycroft/client/speech/recognizer/model/WRONG-PATH/hmm`
then created `en-us` config

## How to test
run `PocketSphinxRecognizerTest.testRecognitionFallback`

## Contributor license agreement signed?
CLA [ ] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2692))

**Review by forslund — APPROVED** [review]
This works just as expected :+1:. I wonder if the LOG statement should be extended to say somehing like "Falling back to en-us" in addition to the model not found just for clarity.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2692))

**Comment by katridi** [comment]
Yeah, sure i can add it, it would definitely clarify this behaviour

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2692))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2692))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2692))

**Review by forslund — APPROVED** [review]

**Comment by krisgesling** [comment]
Awesome, thanks for another great PR, and to Ake for the review :slightly_smiling_face:

**Pull request merged**
