### PR TITLE
Normalize text before intent parsing #530

### PR DESCRIPTION
**Pull request by penrods**
Fixes issues #530 

Utterance text is now normalized before being processed by Adapt for intent parsing.  This means:
  * Numbers become digits (e.g. "Tell me two things" becomes "Tell me 2 things"
  * Articles are removed (e.g. "What is the weather like" becomes "What is weather like")
  * Contractions are expanded (e.g. "What's the time" becomes "What is time")

Adjusted default Skill .voc files as necessary.  Generally this allowed them to become smaller.  But be aware that this can break a skill that contains words "a", "an", "the" in the .voc.

REPEAT:  This is a potentially breaking change!  Check your .voc files!

P.S.  I fat-fingered the branch -- it is 539 instead of 530.  :(

### CODE REVIEW

**Comment by aatchison** [comment]
This is very nice.
`2017-02-23 10:23:33,788 - mycroft.client.speech.listener - DEBUG - STT: i'd like to find 14 cherries
2017-02-23 10:23:33,789 - SpeechClient - INFO - Utterance: [u"i'd like to find 14 cherries"]
2017-02-23 10:23:39,678 - SpeechClient - INFO - Speak: Sorry, I couldn't find an answer for i'd like to find 14 cherries.
`
The looks great when pulling vars for intents...
Doing basic math is a little strange though:
`2017-02-23 10:22:58,543 - mycroft.client.speech.listener - DEBUG - STT: whats 2 x 7
2017-02-23 10:22:58,543 - SpeechClient - INFO - Utterance: [u'whats 2 x 7']
2017-02-23 10:23:01,007 - SpeechClient - INFO - Speak: s×2×7 s 14 s
`
Finally, "what time is it" has an intent failure and falls back to wolfram alpha, negating my configuration settings. 
`2017-02-23 10:25:29,206 - Skills - DEBUG - {"type": "recognizer_loop:utterance", "data": {"session": "a04fffd9-f74d-4618-bd69-bb1507136e29", "utterances": ["what time is it"]}, "context": null}
2017-02-23 10:25:29,207 - intent__init__ - ERROR - 
Traceback (most recent call last):
  File "/mnt/500gb-volume/Sync/do-volume/work/PycharmProjects/mycroft-core/mycroft/skills/intent/__init__.py", line 48, in handle_utterance
    utterance, 100))
StopIteration
2017-02-23 10:25:29,208 - Skills - DEBUG - {"type": "intent_failure", "data": {"utterance": "what time is it"}, "context": null}
2017-02-23 10:25:29,208 - wolfram_alpha__init__ - DEBUG - Could not determine intent, falling back to WolframAlpha Skill!
`

**Comment by penrods** [comment]
Please try it again @aatchison .  I fixed a typo and it worked for me under KDE.

**Comment by aatchison** [comment]
The time is now working, basic math is still wonky.
2017-02-24 11:02:55,246 - SpeechClient - INFO - Utterance: [u'whats 12 + 6']
2017-02-24 11:02:58,068 - SpeechClient - INFO - Speak: s×12 + 6 s 12 s + 6

**Comment by aatchison** [comment]
In the current dev branch this is working well:
```
2017-02-24 11:04:54,166 - SpeechClient - INFO - Utterance: [u'what is 7 + 6']
2017-02-24 11:04:55,688 - SpeechClient - INFO - Speak: 7 + 6 is 13
```

**Comment by penrods** [comment]
That is very interesting.  The transcription you have is "whats 8 + 4", but "whats" is not really word!  I'm adding "whats" -> "what is" in the normalization.

**Comment by penrods** [comment]
You know what -- that fails in the current branch too, I bet.  Look at the transcriptions you pasted.  The first was "whats 12 + 6"  the second is "what is 7 + 6"

**Comment by aatchison** [comment]
That makes sense.

**Comment by aatchison** [comment]
Let me know when you push that.

**Comment by aatchison** [comment]
After testing this branch again, it seems that Wolfram Alpha doesn't return an answer. I verified WA is working in the dev branch.

**Comment by kfezer** [comment]
I'm still seeing "whats" going to wolfram alpha:
```
2017-03-13 15:25:52,104 - Skills - DEBUG - {"type": "intent_failure", "data": {"lang": "en-US", "utterance": "whats 10 x 6"}, "context": null}
2017-03-13 15:25:52,104 - wolfram_alpha__init__ - DEBUG - Falling back to WolframAlpha Skill!
```

**Comment by kfezer** [comment]
There is an issue with WA skill in this branch; if it's replaced with the version in dev, it works.

However, mimic can't say "times" as in (3 x 7) when the answer gets returned from WA. It get's an odd character. "Divided by" gets turned into "slash"

**Pull request merged**
