### PR TITLE
German translation of dialog messages

### PR DESCRIPTION
**Pull request by Halm1**
German translation of dialog messages

[de-de.zip](https://github.com/MycroftAI/mycroft-core/files/1673586/de-de.zip)

### CODE REVIEW

**Comment by forslund** [comment]
Hallo, vielen dank für das PR. (Sorry my german is terrible!)

It seems like something has gone wrong though. The PR is made to a feature branch and not to the dev branch. And there are lots of conflicts.

Can you update your dev branch and make a fresh Pull request? If you need assistance I'd be happy to help!

If you haven't already please head over to https://mycroft.ai/cla and sign the Contributor License Agreement so everyhing is A-OK

**Comment by forslund** [comment]
@Halm1 I'm closing this PR since it's merging things from dev into python3-full an already merged branch. Please try to create a new PR with the German dialogue files.

Thanks

**Comment by Halm1** [comment]
Hi @forslund Yes it´s fine. but i need your help to make a new PR, i am a big noob in GIT :-)

**Comment by forslund** [comment]
Sure thing. Maybe you can join up at chat.mycroft.ai and contact me there. I'm ake-mycroft

**Pull request closed without merging**
