### PR TITLE
added pocketsphinx to requirements.txt, removed compilation from dev_…

### PR DESCRIPTION
**Pull request by aatchison**
…setup.sh

Would anyone mind trying to run dev_setup.sh on a clean system, to see if this is ok?

### CODE REVIEW

**Comment by aatchison** [comment]
This works well for me, including after packaging.

**Comment by ryanleesipes** [comment]
Can you try a clean install inside the Docker container to verify? I will also try a clean install from somewhere else. @Wolfgange3311999 @ethanaward please also test this.

**Comment by aatchison** [comment]
Yes, please. I'm going to pull down a whole new checkout and nuke my virtualenvs

**Comment by aatchison** [comment]
This is working fine for me, as far as I can tell. I really don't want to mess with the docker container, but I'm going to build some debs like this for arm. (amd64 is fine)

**Comment by ryanleesipes** [comment]
I was fairly certain there was a reason we weren't doing this. @clusterfudge care to refresh my memory?

**Comment by aatchison** [comment]
I believe it had something to do with the versions being outdated on pypi?

**Comment by seanfitzgeraldsc** [comment]
the python-pocketsphinx bindings require the pocketsphinx and sphinxbase native binaries, which are not included in the pip package (i don't think they can be, as they're platform specific). Thusly, they cannot be installed into a virtualenv. I was just looking for the issue on the legacy repo, but apparently that's been kablammoed?

**Comment by aatchison** [comment]
I'm not sure, that makes sense though.

**Comment by ryanleesipes** [comment]
No kablammo. Just changed permissions on everything. I will hook you up with permissions on that repo again (unless it's because you aren't on @clusterfudge)

**Comment by aatchison** [comment]
I wondered why the Jenkins stuff couldn't access anything:D

**Comment by aatchison** [comment]
Obviously this PR isn't going to fly, have to try another approach.

**Pull request closed without merging**
