### PR TITLE
Add g++ to native dependencies

### LINKED ISSUE #1146: Issue building fann2
```  Running setup.py install for fann2
    Complete output from command /home/brokenclock/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-hokzQN/fann2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IU04Rk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/brokenclock/.virtualenvs/mycroft/include/site/python2.7/fann2:
    running swig
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/fann2
    copying fann2/__init__.py -> build/lib.linux-x86_64-2.7/fann2
    copying fann2/libfann.py -> build/lib.linux-x86_64-2.7/fann2
    running egg_info
    writing fann2.egg-info/PKG-INFO
    writing top-level names to fann2.egg-info/top_level.txt
    writing dependency_links to fann2.egg-info/dependency_links.txt
    reading manifest file 'fann2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'fann2.egg-info/SOURCES.txt'
    copying fann2/fann2.i -> build/lib.linux-x86_64-2.7/fann2
    copying fann2/fann2_wrap.cxx -> build/lib.linux-x86_64-2.7/fann2
    copying fann2/fann_cpp_subclass.h -> build/lib.linux-x86_64-2.7/fann2
    running build_ext
    building 'fann2._libfann' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/fann2
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSWIG_COMPILE -I./include -I../include -Iinclude -I/usr/include/python2.7 -c fann2/fann2_wrap.cxx -o build/temp.linux-x86_64-2.7/fann2/fann2_wrap.o
    x86_64-linux-gnu-gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/brokenclock/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-hokzQN/fann2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IU04Rk-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/brokenclock/.virtualenvs/mycroft/include/site/python2.7/fann2" failed with error code 1 in /tmp/pip-build-hokzQN/fann2
```

running dev_setup.sh couldn't build fann2

I solved this by installing g++

`sudo apt-get install g++`

might want to add that to the required dependancies

### PR DESCRIPTION
**Pull request by MatthewScholefield**
This fixes #1146. If you run across this PR and are using one of the 3 OSs below, please test and comment if the package installs correctly.

 - [x] Debian / Ubuntu
  - [x] Fedora
- [x] Arch (Untested but verified online)

### Testing instructions

```Bash
git fetch
git checkout bugfix/issue-1146
./dev_setup.sh -sm
```
Now make sure it says something like `Already installed so now going to to be downloaded` rather than something like `Could not find package g++`.

### CODE REVIEW

**Comment by forslund** [comment]
Tested and aworking in ubuntu 17.04

**Comment by penrods** [comment]
Are you waiting on further confirmation, or shall we merge this?

**Comment by MatthewScholefield** [comment]
@penrods Waiting for Arch and Fedora confirmation.

**Comment by matheuslima** [comment]
@MatthewScholefield @penrods I tested in Fedora and I see this error:
```
  gcc: error: build/temp.linux-x86_64-2.7/_imaging.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/decode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/encode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/map.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/display.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/outline.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/path.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Access.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/AlphaComposite.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Resample.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Bands.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/BcnDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/BitDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Blend.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Chops.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Convert.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/ConvertYCbCr.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Copy.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Crc32.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Crop.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Dib.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Draw.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Effects.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/EpsEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/File.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Fill.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Filter.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/FliDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Geometry.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/GetBBox.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/GifDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/GifEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/HexDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Histo.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/JpegDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/JpegEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/LzwDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Matrix.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/ModeFilter.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Negative.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Offset.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Pack.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/PackDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Palette.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Paste.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Quant.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/QuantOctree.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/QuantHash.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/QuantHeap.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/PcdDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/PcxDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/PcxEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Point.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/RankFilter.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/RawDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/RawEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Storage.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/SunRleDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/TgaRleDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Unpack.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/UnpackYCC.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/UnsharpMask.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/XbmDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/XbmEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/ZipDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/ZipEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/TiffDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Jpeg2KDecode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/Jpeg2KEncode.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/BoxBlur.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/QuantPngQuant.o: No such file or directory
  gcc: error: build/temp.linux-x86_64-2.7/libImaging/codec_fd.o: No such file or directory
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-ld: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pillow
  Running setup.py bdist_wheel for fann2
  Complete output from command /home/matheus/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools;__file__='/tmp/pip-build-PwHfsi/fann2/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp3RFfLhpip-wheel-:
  running swig
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/fann2
  copying fann2/__init__.py -> build/lib.linux-x86_64-2.7/fann2
  copying fann2/libfann.py -> build/lib.linux-x86_64-2.7/fann2
  running egg_info
  writing fann2.egg-info/PKG-INFO
  writing top-level names to fann2.egg-info/top_level.txt
  writing dependency_links to fann2.egg-info/dependency_links.txt
  reading manifest file 'fann2.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'fann2.egg-info/SOURCES.txt'
  copying fann2/fann2.i -> build/lib.linux-x86_64-2.7/fann2
  copying fann2/fann2_wrap.cxx -> build/lib.linux-x86_64-2.7/fann2
  copying fann2/fann_cpp_subclass.h -> build/lib.linux-x86_64-2.7/fann2
  running build_ext
  building 'fann2._libfann' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/fann2
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DSWIG_COMPILE -I./include -I../include -Iinclude -I/usr/include/python2.7 -c fann2/fann2_wrap.cxx -o build/temp.linux-x86_64-2.7/fann2/fann2_wrap.o
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for fann2
  Running setup.py bdist_wheel for xxhash
  Complete output from command /home/matheus/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools;__file__='/tmp/pip-build-PwHfsi/xxhash/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpacm4lMpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/xxhash
  copying xxhash/cffi.py -> build/lib.linux-x86_64-2.7/xxhash
  copying xxhash/__init__.py -> build/lib.linux-x86_64-2.7/xxhash
  running build_ext
  building 'cpython' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/xxhash
  creating build/temp.linux-x86_64-2.7/c-xxhash
  gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ic-xxhash -I/usr/include/python2.7 -c xxhash/cpython.c -o build/temp.linux-x86_64-2.7/xxhash/cpython.o -std=c99 -O3 -Wall -W -Wundef -Wno-error=declaration-after-statement
  gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for xxhash
Successfully built tornado pyyaml
Failed to build PyAudio pyalsaaudio netifaces psutil pocketsphinx pillow fann2 xxhash
Installing collected packages: PyAudio, pyee, SpeechRecognition, certifi, tornado, websocket-client, adapt-parser, pyowm, futures, requests-futures, pytz, astral, tzlocal, parsedatetime, pyyaml, feedparser, pyalsaaudio, xmlrunner, pyserial, netifaces, pyjokes, psutil, pep8, multi-key-dict, pocketsphinx, inflection, olefile, pillow, python-dateutil, protobuf, enum34, enum-compat, zeroconf, pychromecast, python-vlc, pulsectl, aiml, fann2, xxhash, padatious
  Running setup.py install for PyAudio
    Complete output from command /home/matheus/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-PwHfsi/PyAudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VmOKMe-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/matheus/.virtualenvs/mycroft/include/site/python2.7/PyAudio:
    running install
    running build
    running build_py
    running build_ext
    building '_portaudio' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-x86_64-2.7/src/_portaudiomodule.o
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/matheus/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-PwHfsi/PyAudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VmOKMe-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/matheus/.virtualenvs/mycroft/include/site/python2.7/PyAudio" failed with error code 1 in /tmp/pip-build-PwHfsi/PyAudio
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by MatthewScholefield** [comment]
@matheuslima Thanks for testing. Can you see if it works after you run:

```Bash
sudo dnf install redhat-rpm-config
```

**Comment by matheuslima** [comment]
@MatthewScholefield  After install this package and run again `./dev_setup.sh -sm`, worked

**Comment by penrods** [comment]
Can we check off Fedora now?

**Comment by MatthewScholefield** [comment]
Sure. Still have to make the change, but yeah.

**Comment by augustnmonteiro** [comment]
Are we good to merge this one?

**Comment by MatthewScholefield** [comment]
@augustnmonteiro Waiting on someone to test arch

**Comment by penrods** [comment]
So, either remove Arch or just accept it and fix it later.  This has been sitting here two weeks waiting and the vast majority of impacted user experience (Ubuntu, Fedora) has been tested.

**Comment by MatthewScholefield** [comment]
@augustnmonteiro Ok, good to merge :)

**Pull request merged**
