### PR TITLE
Messagebus interface

### PR DESCRIPTION
**Pull request by JarbasAI**
I propose two new classes, BusQuery and BusResponder

BusQuery sends a message and waits for the response
BusResponder listens for messages and sends responses

### CODE REVIEW

**Comment by forslund** [comment]
I'm not 100% sure this is a good idea. Forcing an asynchronous system into a synchronous operation will probably not be good in the long run. We've done exactly this in a couple of places but I'm starting to feel that was a mistake.

The positive side of this approach is that it's easy to understand so in that way it's very good, I need to research what sort of performance hit we might see if this is picked up in many skills.

I would in any case look into using once instead of on when setting up the waiting task (the method will be triggered only once) and look into the possibility of using the `Message.reply()` method.

**Comment by JarbasAI** [comment]
using once makes sense, will change that

the messagebus is a powerful mechanism, being able to force an asynchronous system into a synchronous operation is a very useful option to have, i have been using this in a lot of skills (which i tend to call "service_something") concurrently with success,

i agree this should not be a default, i don't like using this approach in converse method for instance, but it enables a lot more options and in the long run i think it is a useful tool to have

**Comment by augustnmonteiro** [comment]
@JarbasAI @forslund I think that in this case we should use a tool that was made for that, websockets are really good if you don't need order or run sync, there are message brokers that solve this problem I would take a look at the Redis Pub/Sub https://redis.io/topics/pubsub

**Comment by penrods** [comment]
Does https://github.com/MycroftAI/mycroft-core/pull/1423 make this obsolete?

**Comment by JarbasAl** [comment]
not exactly, #1423 solves part of what this does, but this gives more control and options

i have included this in my utils package, usage example here https://github.com/JarbasAl/mycroft_jarbas_utils/tree/master/mycroft_jarbas_utils/messagebus

**Comment by JarbasAI** [comment]
#1822 makes this obsolete

**Pull request closed without merging**
