### PR TITLE
add german noise-word-list

### PR DESCRIPTION
**Pull request by pfefferle**
## Description
It adds the german noise words, as discussed here: https://github.com/MycroftAI/mycroft-core/issues/3050

You can find the noise word discussion here: https://openvoice-tech.net/index.php?title=Mycroft_in_German

## Contributor license agreement signed?
CLA [X] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-3122)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-3122/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-3122/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-3122/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-3122/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-3122/logs/enclosure.log)

**Review by krisgesling — APPROVED** [review]
Thanks Matthias, this looks great.

One of the VK tests failed, but I'm 99.99% sure its unrelated so have triggered another run and will merge when it passes.

**Comment by pfefferle** [comment]
@krisgesling "wo"  (german  for "where") is in the list, might that cause the issue? because it seems to be a problem with skills that have intents like "where is...". But the eng noise list also includes "where"...

**Comment by krisgesling** [comment]
It shouldn't cause a problem because we don't actually test on other languages at the moment. So really this change _shouldn't_ change the test outcomes at all.

At least locally the Wikipedia Skill replies "Amerstand is the capital and most populist... "
But the speak output I can see in the logs for these tests is just "Amsterdam , lit."

This is likely going to need some deeper investigation as to what's going on since we aren't seeing the same thing without this PR.

**Comment by forslund** [comment]
@krisgesling The wiki-skill in the mycroft-skills repo seem to be outdated. The issue occurs in the current version but not in the latest. so maybe an update is in order?

**Comment by krisgesling** [comment]
Ah the Wiki Skill seems to be blocked until we release a new version of core. 
See: https://github.com/MycroftAI/mycroft-skills/pull/1563

Unfortunately that's not something we're we're going to get to before the Mark II ships next month sorry.

**Comment by pfefferle** [comment]
I saw that the french version was merged, any news for the German version? https://github.com/MycroftAI/mycroft-core/pull/3128

**Comment by krisgesling** [comment]
Yes, thanks for the nudge! 
The test issue is unrelated so I figured we should merge these in.

**Pull request merged**
