### PR TITLE
Add Mozilla TTS connection validation

### PR DESCRIPTION
**Pull request by krisgesling**
Replication of PR #2719
Original code from @JarbasAl

## Description
Validates the ability to connect to the defined Mozilla TTS instance.

## How to test
Run Mozilla TTS and configure Mycroft to use it.

## Contributor license agreement signed?
- [x] CLA (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2828))

**Review by forslund — CHANGES_REQUESTED** [review]
In the original PR (see #2719") we discussed changing the url to the root so config would be `"url": "http://0.0.0.0:5002` so the test doesn't have remove the last part of the url, instead it would be added in the `get_tts()`

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2828))

**Review by forslund — COMMENTED** [review]
Works great.

**Review by forslund — APPROVED** [review]

**Pull request merged**
