### PR TITLE
Update pyee to v7.0.1

### PR DESCRIPTION
**Pull request by forslund**
## Description
pyee has added ThreadExecutor variant of the EventEmitter which can
replace the home-spun threadpool based emitter.

Adapt has been updated to match this change.

## How to test
Make sure mycroft-core still works as expected.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2507))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2507))

**Comment by krisgesling** [comment]
Looks good, thanks Ake!

**Comment by forslund** [comment]
This version is better at flagging exceptions in event handlers so some bugs may crawl to the surface

**Comment by forslund** [comment]
Also worth looking at is replacing the ExecutorEventEmitter with the AsyncIOEventEmitter, reducing the thread count of core somewhat.

**Comment by krisgesling** [comment]
Yeah cool, I've added an internal ticket to take a look at that sometime

**Pull request merged**
