### PR TITLE
Fix broken link in Contributor Guide

### PR DESCRIPTION
**Pull request by krisgesling**
## Description
Update of the "How to Contribute Guide" in line with process changes being developed here:
https://docs.google.com/document/d/1AQa5WGuiHHGpltNXy6c0NLmFMZfMRP8U0MoqEb4lB-A/edit#

## How to test
Documentation only - review text.

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2693))

**Comment by krisgesling** [comment]
Only a broken link in a markdown file - merging.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-2693)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/core/PR-2693/logs/skills.log), [audio.log](https://reports.mycroft.ai/core/PR-2693/logs/audio.log), [voice.log](https://reports.mycroft.ai/core/PR-2693/logs/voice.log), [bus.log](https://reports.mycroft.ai/core/PR-2693/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/core/PR-2693/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2693))

**Review by ken-mycroft — APPROVED** [review]

**Pull request merged**
