### PR TITLE
Bugfix/duration stretch update

### PR DESCRIPTION
**Pull request by forslund**
## Description
Chat user *hniazi* discovered that the `duration_stretch` setting wasn't updated as expected when configuration was updated. It turned out the method looked a global scoped config and not the object specific config. This fixes that issue.

It also changes the global variable names to uppercase to make this kind of issue harder happen again.

## How to test

Add a tts section to your user's config file

```
"tts": {
  "module": "mimic",
  "mimic": {"duration_stretch": "1.3"}
}
```
then trigger a config reload
`python -m mycroft.messagebus.send "configuration.updated"`
Make mycroft talk to hear the slower speech

Change the value to something like "0.5" trigger an update again and make sure mycroft now talks really fast.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2691))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-2691))

**Comment by forslund** [comment]
What does the complex tag mean?

**Comment by krisgesling** [comment]
Mild judgement call, but anything not straightforward. 
Eg things that touch multiple areas of the codebase, might have side effects, or require someone with specific knowledge of a system to review.

Having a quick look at the changes I believe I got this one wrong :)

**Review by krisgesling — APPROVED** [review]
Looks great, and it helped me catch one of those nebulous pyee errors :tada: 

I also remembered that I converted the old "bug" label to this one which is why it got tagged "complex".

**Pull request merged**
