### PR TITLE
Fix camel case splitting

### PR DESCRIPTION
**Pull request by juliengk**
Signed-off-by: Julien Kassar <github@kassisol.com>

## Description
It returns the passed argument `PublicIPSkill` to `Public IP Skill` instead of `Public IPSkill`

Found the function to split correctly camel case in this [post](https://stackoverflow.com/questions/29916065/how-to-do-camelcase-split-in-python)

## Contributor license agreement signed?
CLA [Yes]

### CODE REVIEW

**Comment by juliengk** [comment]
I tried the suggested simpler regex. It does work for a string like `PublicIPSkill` but not for `ABCWordSkill`. The result for the latter is `ABCWord Skill`.

**Comment by forslund** [comment]
Is the python version on the Mark-1 updated to >=3.5 so type hinting is supported?

**Comment by MatthewScholefield** [comment]
@forslund Python 3.4 supports type hints. It's only assignment type hints that 3.4 doesn't support (ie. `a: int = 12`)

**Comment by forslund** [comment]
Ah gotcha

**Comment by juliengk** [comment]
that adds a leading space :)

**Comment by MatthewScholefield** [comment]
@juliengk Dammit xD, then it'd be:
```python
' '.join(re.sub(r'([a-z]?)(?:([A-Z]+)?([A-Z][a-z])|([A-Z]+))', r'\1 \2 \3\4', identifier).split())
```

**Comment by juliengk** [comment]
@MatthewScholefield  how about no regex?

```python
def camel_case_split(identifier: str) -> str:
    result = ''

    lenStr = len(identifier)-1

    i = 0
    previous = None
    for c in identifier:
        current = c.isupper()
        next = True if i < lenStr and identifier[i+1].isupper() else False

        if (i > 0) and ((previous != current and current) or (current and not next)):
            result += ' '
        result += c

        previous = current
        i += 1

    return result
```

**Comment by MatthewScholefield** [comment]
@juliengk `camel_cast_split('VALUE')` would be `VALU E` with that implementation :)

**Comment by juliengk** [comment]
ah! i haven't tried single word with that. I tried `ABCWordSkill`, `abcWordSkill` and `PublicIPSkill`

**Comment by juliengk** [comment]
```python
def camel_case_split(identifier: str) -> str:
    result = ''

    lenStr = len(identifier)-1

    i = 0
    previous = None
    for c in identifier:
        current = c.isupper()
        next = True if i < lenStr and identifier[i+1].isupper() else False

        if (i > 0) and ((previous != current and current) or (current and not next and lenStr-i > 1)):
            result += ' '
        result += c

        previous = current
        i += 1

    return result
```

**Comment by juliengk** [comment]
@MatthewScholefield Let me know whichever of the solutions you prefer, I would make the change. Thanks.

**Comment by MatthewScholefield** [comment]
@juliengk It's fine how it is :)

**Pull request merged**
