### PR TITLE
Properly call found_date check

### PR DESCRIPTION
**Pull request by forslund**
## Description
The check for no date or time in the sentence was never called, this calls it properly and adds a few simple tests.

## Contributor license agreement signed?
CLA [ Yes ]

### CODE REVIEW

**Comment by krisgesling** [comment]
Just waiting to fix Skills that are using the old behaviour to get today's datetime.
_note for myself as much as anyone else_

**Comment by davidwagnerkc** [comment]
@forslund @krisgesling Does this need to be merged for 19.08?

**Comment by forslund** [comment]
It's not strictly necessary. It makes it behave inline with the specification. But it has been broken for so long that I'm not sure it ever worked. Gez wanted to go through the skills to check that none of the default skills were abusing this mechanic before we merged it.

**Comment by davidwagnerkc** [comment]
Sounds good just wanted to check. We can finish this off post release then.

**Comment by krisgesling** [comment]
Yep, definitely leave this or the Alarm Skill will break.
I scanned the rest of the Marketplace and haven't found anyone else using the hidden "feature" :smile:

**Comment by forslund** [comment]
Closing this since lingua-franca handles this now.

**Pull request closed without merging**
