### PR TITLE
loaded skills bus messages

### PR DESCRIPTION
**Pull request by JarbasAl**
## Description
Adds bus messages for skill.loaded, skill.shutdown and skill.load.fail

## How to test
see new messages appearing in the logs

## Contributor license agreement signed?
CLA [ x] (Whether you have signed a [CLA - Contributor Licensing Agreement](https://mycroft.ai/cla/)

### CODE REVIEW

**Comment by forslund** [comment]
Part of this overlaps with work done in #1318 so I might merge this into that PR and fix the conflicts.

**Comment by JarbasAl** [comment]
i missed #1318, just needed this for the intent data PR #1351

**Comment by forslund** [comment]
My PR got merged before I had time to update it with this pr. Can you rebase this and resolve the conflict?

I also would like to have the shutdown message in the SkillManager and not within the shutdown method. (To make it more consistent)

The message names should start with `mycroft.skills`.

**Comment by JarbasAl** [comment]
i had the message there at first, but maybe skills can call the shutdown method somehow (self shutdown or other shenanigans ) and the message is still good to have

**Comment by forslund** [comment]
Even if the skills call their own shutdown method that won't unload them. They will still be registered as loaded in the skills service and hang around in memory. I'd like the message more as an indicator of what the skill load/reload system does

**Comment by forslund** [comment]
Looks good, can you fix the remaining Pep8 issue (too many blank lines after shutdown message)

**Comment by forslund** [comment]
Merged via #1396

**Pull request closed without merging**
